% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 07-Jan-2016 09:40:57
% Model: inf_minlp_10

% Objective
fun = @(x)(0.5*x(9)^10+0.25*x(10)^10+0.25*x(11)^10)^0.1;

% Bounds
lb = [1,1,1,1,0.5,0.5,0.5,0.5,0,0,0]';
ub = [10,10,10,10,0.99999,0.99999,0.99999,0.99999,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[8000000000*(6*exp(0.25*x(1))*x(1)+6*exp(0.25*x(2))*x(2)+8*exp(0.25*x(3))*x(3)+7*exp(0.25*x(4))*x(4))-x(9);
             100000*(-1000/log(x(5)))^1.5*(exp(0.25*x(1))+x(1))+230000*(-1000/log(x(6)))^1.5*(exp(0.25*x(2))+x(2))+30000*(-1000/log(x(7)))^1.5*(exp(0.25*x(3))+x(3))+230000*(-1000/log(x(8)))^1.5*(exp(0.25*x(4))+x(4))-x(10);
             (5333333333333.33-5333333333333.33*exp(x(1)*log(1-x(5))))*(1-exp(x(2)*log(1-x(6))))*(1-exp(x(3)*log(1-x(7))))*(1-exp(x(4)*log(1-x(8))))-x(11)];
cl = [-Inf,-Inf,0.75]';
cu = [500,4000000000000,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'IIIICCCCCCC';

% Starting Guess
x0 = [1,1,1,1,0.5,0.5,0.5,0.5,NaN,NaN,NaN]';

% Options
opts = struct('probname','inf_minlp_10');
opts.sense = 'max';
