% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 07-Jan-2016 10:21:00
% Model: inf_minlp_203

% Objective
fun = @(x)(10000+5000*log(1/x(2)))*x(1);

% Bounds
lb = [1,0.367879441171442]';
ub = [100,0.5]';

% Constraints
nlcon = @(x)[(10000+5000*log(1/x(2)))*x(1);
             x(1)*(1-x(2))-(4.60517018598809*x(1)*(1-x(2)))^0.5-0.5*x(1)];
cl = [-Inf,1]';
cu = [4000000,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'IC';

% Starting Guess
x0 = [1,0.367879441171442]';

% Options
opts = struct('probname','inf_minlp_203');
opts.sense = 'min';
