% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 07-Jan-2016 11:29:12
% Model: inf_minlp_365

% Objective
fun = @(x)49.8*x(1)*x(17)+53.2*x(2)*x(17)+65*x(3)*x(17)+86*x(4)*x(17)+38.2*x(5)*x(18)+60*x(6)*x(18)+81*x(7)*x(18)+45*x(9)*x(19)+76*x(10)*x(19)+61*x(13)*x(20);

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]';
ub = [0,0,0,0,0,0,0,Inf,0,0,Inf,Inf,0,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(17)+x(18)+x(19)+x(20);
             -x(1)-0.632*x(2)-0.264*x(3)-0.08*x(4)+x(21);
             -0.368*x(2)-0.368*x(3)-0.184*x(4)+x(22);
             -0.368*x(3)-0.368*x(4)+x(23);
             -0.368*x(4)+x(24);
             -0.632*x(5)-0.264*x(6)-0.08*x(7)+x(25);
             -0.368*x(5)-0.368*x(6)-0.184*x(7)+x(26);
             -0.368*x(6)-0.368*x(7)+x(27);
             -0.368*x(7)+x(28);
             -0.264*x(9)-0.08*x(10)+x(29);
             -0.368*x(9)-0.184*x(10)+x(30);
             -0.368*x(9)-0.368*x(10)+x(31);
             -0.368*x(10)+x(32);
             -0.08*x(13)+x(33);
             -0.184*x(13)+x(34);
             -0.368*x(13)+x(35);
             -0.368*x(13)+x(36);
             x(17)-(x(21)*x(17)+x(25)*x(18)+x(29)*x(19)+x(33)*x(20));
             x(18)-(x(22)*x(17)+x(26)*x(18)+x(30)*x(19)+x(34)*x(20));
             x(19)-(x(23)*x(17)+x(27)*x(18)+x(31)*x(19)+x(35)*x(20));
             x(1)+x(2)+x(3)+x(4);
             x(5)+x(6)+x(7)+x(8);
             x(9)+x(10)+x(11)+x(12);
             x(13)+x(14)+x(15)+x(16)];
cl = [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1]';
cu = [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'BBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','inf_minlp_365');
opts.sense = 'min';
