% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 13-May-2015 12:12:57
% Model: inf_lp_16

% Objective
fun = @(x)x(1);

% Bounds
lb = [0,0]';
ub = [Inf,Inf]';

% Constraints
nlcon = @(x)[-2*x(1)-4*x(2);
             -8*x(1)-20*x(2);
             x(1);
             x(2)];
cl = [-4,-24,-Inf,-Inf]';
cu = [-4,-24,3,1.2]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CC';

% Starting Guess
x0 = [NaN,NaN]';

% Options
opts = struct('probname','inf_lp_16');
opts.sense = 'max';
