% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 13-May-2015 12:12:57
% Model: inf_lp_15

% Objective
fun = @(x)x(2);

% Bounds
lb = [0,0,0,0]';
ub = [Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[-x(1)-4*x(2)-x(3);
             -2.45*x(1)-10*x(2)-2*x(4);
             -2.1*x(1)-x(2)-2*x(3)-x(4);
             -4.25*x(1)-24*x(2);
             x(2);
             x(1)];
cl = [-6,-12,-6,-24,-Inf,0.1]';
cu = [-6,-12,-6,-24,1,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','inf_lp_15');
opts.sense = 'max';
