% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-May-2015 23:17:17
% Model: inf_nlp_154

% Objective
fun = @(x)9.5*x(1)+8.5*x(2)+7.5*x(3)+6.5*x(4)+5.5*x(5)+4.5*x(6)+3.5*x(7)+2.5*x(8)+1.5*x(9)+0.5*x(10);

% Bounds
lb = [0,0,0,0,0,0,0,0,0,0]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(1)+x(2)+x(3)+x(4)+x(5)+x(6)+x(7)+x(8)+x(9)+x(10);
             (1-x(1)^2)^0.5+(4-x(2)^2)^0.5+(9-x(3)^2)^0.5+(16-x(4)^2)^0.5+(25-x(5)^2)^0.5+(36-x(6)^2)^0.5+(49-x(7)^2)^0.5+(64-x(8)^2)^0.5+(81-x(9)^2)^0.5+(100-x(10)^2)^0.5];
cl = [0,35]';
cu = [0,35]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','inf_nlp_154');
opts.sense = 'min';
