% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 13-May-2015 16:53:43
% Model: inf_lp_23

% Objective
fun = @(x)x(9);

% Bounds
lb = [0,0,0,0,0,0,0,0,0,0,0,0,0]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[-x(1)-3*x(2)-2*x(3)+2*x(4)-2*x(5)-4*x(6)+4*x(7)-4*x(8)-4*x(9)-x(10);
             -0.25*x(1)-12*x(2)-8*x(3)+8*x(4)-12*x(5)-16*x(6)+20*x(7)-20*x(8)-24*x(9)-2*x(12);
             0.166*x(1)-0.47*x(2)-0.816*x(3)+0.318*x(4)+0.302*x(7)-0.8*x(8);
             -0.333333333333333*x(1)-x(2)-x(10);
             -x(3)+x(4)-x(5)+x(10)-2*x(13);
             x(7)-x(8)-x(9)+x(11);
             -x(4)+x(6)-x(7);
             x(3)-x(4);
             -x(7)+x(8);
             x(2);
             x(6);
             x(5);
             x(9);
             x(6)+x(10);
             1.6*x(1)+x(11);
             x(12);
             x(1)];
cl = [-6,-24,0.99099,-2,0,0,0,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
cu = [-6,-24,0.99099,Inf,Inf,Inf,0,3,1.2,2,1.5,2,1,6,4,6,0.6]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','inf_lp_23');
opts.sense = 'max';
