% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-May-2015 23:08:24
% Model: inf_nlp_106

% Objective
fun = @(x)400*x(1)^0.9+22*(-14.7+x(2))^1.2+x(3)+1000;

% Bounds
lb = [8.7495087e-05,14.700000974514,0.170624356199,79.99999989633]';
ub = [8.7495087e-05,14.700000974514,0.170624356199,79.99999989633]';

% Constraints
nlcon = @(x)[x(3)*x(1)+144*x(4);
             -exp(11.86-3950/(460+x(4)))+x(2)];
cl = [11520,0]';
cu = [Inf,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCC';

% Starting Guess
x0 = [8.7495087e-05,14.700000974514,0.170624356199,79.99999989633]';

% Options
opts = struct('probname','inf_nlp_106');
opts.sense = 'min';
