% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 07-Jan-2016 10:21:00
% Model: inf_minlp_204

% Objective
fun = @(x)(-(200+x(14))*x(9))-5*x(15)*x(10)-1035*x(16)*x(11)+0.85*x(13);

% Bounds
lb = [0,0,0,0,-Inf,-Inf,-Inf,-Inf,0,0,0,0,0,0,0,0]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,100,100,100,100,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(1)-x(14);
             x(2)-5*x(15);
             x(3)-1035*x(16);
             x(4);
             -x(1)+x(2)-2700*x(6);
             -x(1)+x(3)-2700*x(7);
             -x(1)+x(4)-2700*x(8);
             x(1)-x(2)-2700*x(5);
             -x(2)+x(3)-2700*x(7);
             -x(2)+x(4)-2700*x(8);
             x(1)-x(3)-2700*x(5);
             x(2)-x(3)-2700*x(6);
             -x(3)+x(4)-2700*x(8);
             x(1)-x(4);
             x(2)-x(4);
             x(3)-x(4);
             -100000*x(5)+x(9);
             -100000*x(6)+x(10);
             -100000*x(7)+x(11);
             -100000*x(8)+x(12);
             x(5)+x(6)+x(7)+x(8);
             -450*x(9)+x(13);
             -450*x(10)+x(13);
             -450*x(11)+x(13);
             -450*x(12)+x(13);
             x(13)];
cl = [0,-200,-200,150,-2699.99,-2699.99,-2699.99,-2699.99,-2699.99,-2699.99,-2699.99,-2699.99,-2699.99,0.01,0.01,0.01,0,0,0,0,1,0,0,0,0,-Inf]';
cu = [0,-200,-200,150,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,0,0,0,0,1,Inf,Inf,Inf,Inf,50000000]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCBBBBIIIICCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','inf_minlp_204');
opts.sense = 'max';
