% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 01-Jun-2015 12:33:36
% Model: inf_nlp_87

% Objective
fun = @(x)x(4);

% Bounds
lb = [1.1275,1.282,1.018,1.0899]';
ub = [1.1275,1.282,1.018,1.0899]';

% Constraints
nlcon = @(x)[x(1)^4*x(2)^4-x(1)^4-x(2)^4*x(3);
             -x(1)-0.25*x(4);
             x(1)-0.25*x(4);
             -x(2)-0.2*x(4);
             x(2)-0.2*x(4);
             -x(3)-0.2*x(4);
             x(3)-0.2*x(4)];
cl = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
cu = [0,-1.4,1.4,-1.5,1.5,-0.8,0.8]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCC';

% Starting Guess
x0 = [1.1275,1.282,1.018,1.0899]';

% Options
opts = struct('probname','inf_nlp_87');
opts.sense = 'min';
