% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 07-Jan-2016 10:59:49
% Model: inf_minlp_32

% Objective
fun = @(x)0.00172*x(5)^2+7.6997*x(5)+0.000115*x(5)^2*x(5)+0.0435*x(6)^2+36*x(6)+0.027*x(1)^2+0.6*x(1)+0.011*x(6)*x(1)+0.1035*x(7)^2+34.5*x(7)+0.025*x(2)^2+2.203*x(2)+0.051*x(7)*x(2)+0.072*x(8)^2+20*x(8)+0.02*x(3)^2+2.3*x(3)+0.04*x(8)*x(3)+0.038*x(4)^2+2.0109*x(4)+6669.8863;

% Bounds
lb = [81.09,23.92,6.29,38.7,134.74,48.2,16.23,100.85,-Inf,-Inf,-Inf,-Inf]';
ub = [81.09,23.92,6.29,38.7,134.74,48.2,16.23,100.85,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(5)+x(6)+x(7)+x(8);
             x(1)+x(2)+x(3)+x(4);
             0.272727272727273*x(2)+x(7);
             -2.33333333333333*x(2)+x(7);
             0.25*x(2)+x(7);
             x(9)*x(6)-125.8*x(9);
             x(9)+x(10);
             x(9)*x(1)-15.9*x(9);
             x(9)*x(6)-44*x(9);
             x(10)*x(6)-125.8*x(10);
             x(10)*x(6)+0.151162790697674*x(10)*x(1)-130.698*x(10);
             x(10)*x(6)-1.16611295681063*x(10)*x(1)+46.881*x(10);
             x(10)*x(6)+0.0676818950930626*x(10)*x(1)-45.076*x(10);
             x(10)*x(1)-15.9*x(10);
             x(11)+x(12);
             x(11)*x(8)-90*x(11);
             x(11)*x(8)+0.6*x(11)*x(3)-105*x(11);
             x(12)*x(8)-90*x(12);
             x(12)*x(8)-35*x(12);
             x(12)*x(8)-2.2*x(12)*x(3)+9*x(12)];
cl = [300,150,-Inf,-83.333,20,-Inf,1,-Inf,0,-Inf,-Inf,0,0,0,1,0,-Inf,-Inf,0,0]';
cu = [300,150,60,Inf,Inf,0,1,0,Inf,0,0,Inf,Inf,Inf,1,Inf,0,0,Inf,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCBBBB';

% Starting Guess
x0 = [81.09,23.92,6.29,38.7,134.74,48.2,16.23,100.85,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','inf_minlp_32');
opts.sense = 'min';
