% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-May-2015 23:47:41
% Model: inf_nlp_27

% Objective
fun = @(x)9.5*x(1)+8.5*x(2)+7.5*x(3)+6.5*x(4)+5.5*x(5)+4.5*x(6)+3.5*x(7)+2.5*x(8)+1.5*x(9)+0.5*x(10);

% Bounds
lb = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(1)+x(2)+x(3)+x(4)+x(5)+x(6)+x(7)+x(8)+x(9)+x(10);
             x(11)^2+x(1)^2;
             x(12)^2+x(2)^2;
             x(13)^2+x(3)^2;
             x(14)^2+x(4)^2;
             x(15)^2+x(5)^2;
             x(16)^2+x(6)^2;
             x(17)^2+x(7)^2;
             x(18)^2+x(8)^2;
             x(19)^2+x(9)^2;
             x(20)^2+x(10)^2;
             x(11)+x(12)+x(13)+x(14)+x(15)+x(16)+x(17)+x(18)+x(19)+x(20)];
cl = [0,1,4,9,16,25,36,49,64,81,100,35]';
cu = [0,1,4,9,16,25,36,49,64,81,100,35]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','inf_nlp_27');
opts.sense = 'min';
