% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 08:54:44
% Model: alkyl

% Objective
fun = @(x)-6.3*x(4)*x(7)+5.04*x(1)+0.35*x(2)+x(3)+3.36*x(5);

% Bounds
lb = [0,0,0,0,0,0.85,0.9,3,1.2,1.45,0.99,0.99,0.9,0.99]';
ub = [2,1.6,1.2,5,2,0.93,0.95,12,4,1.62,1.01010101010101,1.01010101010101,1.11111111111111,1.01010101010101]';

% Constraints
nlcon = @(x)[-0.819672131147541*x(1)+x(4)-0.819672131147541*x(5);
             0.98*x(3)-(0.01*x(4)*x(9)+x(3))*x(6);
             -x(1)*x(8)+10*x(2)+x(5);
             x(4)*x(11)-(1.12+0.13167*x(8)-0.0067*x(8)*x(8))*x(1);
             x(7)*x(12)-0.01*(1.098*x(8)-0.038*x(8)*x(8))-0.325*x(6);
             x(9)*x(13)+22.2*x(10);
             x(10)*x(14)-3*x(7)];
cl = [0,0,0,0,0.57425,35.82,-1.33]';
cu = [0,0,0,0,0.57425,35.82,-1.33]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCC';

% Starting Guess
x0 = [1.745,1.2,1.1,3.048,1.974,0.893,0.928,8,3.6,1.45,1,1,1,1]';

% Options
opts = struct('probname','alkyl');
opts.sense = 'min';
