% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 13:53:51
% Model: ex14_1_1

% Objective
fun = @(x)x(3);

% Bounds
lb = [-5,-5,-Inf]';
ub = [5,5,Inf]';

% Constraints
nlcon = @(x)[2*x(2)^2+4*x(1)*x(2)-42*x(1)+4*x(1)^3-x(3);
             (-2*x(2)^2)-4*x(1)*x(2)+42*x(1)-4*x(1)^3-x(3);
             2*x(1)^2+4*x(1)*x(2)-26*x(2)+4*x(2)^3-x(3);
             (-2*x(1)^2)-4*x(1)*x(2)+26*x(2)-4*x(2)^3-x(3)];
cl = [-Inf,-Inf,-Inf,-Inf]';
cu = [14,-14,22,-22]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [NaN,NaN,NaN]';

% Options
opts = struct('probname','ex14_1_1');
opts.sense = 'min';
