% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 13:53:52
% Model: ex2_1_3

% Objective
fun = @(x)5*x(1)-0.5*(10*x(1)*x(1)+10*x(2)*x(2)+10*x(3)*x(3)+10*x(4)*x(4))+5*x(2)+5*x(3)+5*x(4)-x(5)-x(6)-x(7)-x(8)-x(9)-x(10)-x(11)-x(12)-x(13);

% Bounds
lb = [0,0,0,0,0,0,0,0,0,0,0,0,0]';
ub = [1,1,1,1,1,1,1,1,1,Inf,Inf,Inf,1]';

% Constraints
nlcon = @(x)[2*x(1)+2*x(2)+x(10)+x(11);
             2*x(1)+2*x(3)+x(10)+x(12);
             2*x(2)+2*x(3)+x(11)+x(12);
             -8*x(1)+x(10);
             -8*x(2)+x(11);
             -8*x(3)+x(12);
             -2*x(4)-x(5)+x(10);
             -2*x(6)-x(7)+x(11);
             -2*x(8)-x(9)+x(12)];
cl = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
cu = [10,10,10,0,0,0,0,0,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCC';

% Starting Guess
x0 = [1,1,1,1,1,1,1,1,1,3,3,3,1]';

% Options
opts = struct('probname','ex2_1_3');
opts.sense = 'min';
