% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 13:53:53
% Model: ex3_1_2

% Objective
fun = @(x)0.8356891*x(1)*x(5)+37.293239*x(1)+5.3578547*x(3)*x(3)-40792.141;

% Bounds
lb = [78,33,27,27,27]';
ub = [102,45,45,45,45]';

% Constraints
nlcon = @(x)[0.0056858*x(2)*x(5)-0.0022053*x(3)*x(5)+0.0006262*x(1)*x(4);
             0.0022053*x(3)*x(5)-0.0056858*x(2)*x(5)-0.0006262*x(1)*x(4);
             0.0071317*x(2)*x(5)+0.0021813*x(3)*x(3)+0.0029955*x(1)*x(2);
             (-0.0071317*x(2)*x(5))-0.0021813*x(3)*x(3)-0.0029955*x(1)*x(2);
             0.0047026*x(3)*x(5)+0.0019085*x(3)*x(4)+0.0012547*x(1)*x(3);
             (-0.0047026*x(3)*x(5))-0.0019085*x(3)*x(4)-0.0012547*x(1)*x(3)];
cl = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
cu = [6.665593,85.334407,29.48751,-9.48751,15.599039,-10.699039]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCC';

% Starting Guess
x0 = [78,33,29.9953,45,36.7758]';

% Options
opts = struct('probname','ex3_1_2');
opts.sense = 'min';
