% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 13:53:54
% Model: ex5_3_2

% Objective
fun = @(x)0.00432*x(1)+0.01517*x(2)+0.01517*x(9)+0.00432*x(13)+0.9979;

% Bounds
lb = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]';
ub = [300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,1,1,1,1]';

% Constraints
nlcon = @(x)[x(1)+x(2)+x(3)+x(4);
             x(5)-x(6)-x(7);
             x(8)-x(9)-x(10)-x(11);
             x(12)-x(13)-x(14)-x(15);
             x(16)-x(17)-x(18);
             x(13)*x(21)+0.333*x(1)-x(5);
             x(13)*x(22)-x(8)*x(20)+0.333*x(1);
             -x(8)*x(19)+0.333*x(1);
             -x(12)*x(21)-0.333*x(2);
             x(9)*x(20)-x(12)*x(22)+0.333*x(2);
             x(9)*x(19)+0.333*x(2)-x(16);
             x(14)*x(21)+0.333*x(3)+x(6);
             x(10)*x(20)+x(14)*x(22)+0.333*x(3);
             x(10)*x(19)+0.333*x(3)+x(17);
             x(19)+x(20);
             x(21)+x(22)];
cl = [300,0,0,0,0,0,0,0,0,0,0,30,50,30,1,1]';
cu = [300,0,0,0,0,0,0,0,0,0,0,30,50,30,1,1]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','ex5_3_2');
opts.sense = 'min';
