% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 13:53:54
% Model: ex5_4_4

% Objective
fun = @(x)1300*(2000/(0.333333333333333*x(1)*x(2)+0.166666666666667*x(1)+0.166666666666667*x(2)))^0.6+1300*(1000/(0.666666666666667*x(3)*x(4)+0.166666666666667*x(3)+0.166666666666667*x(4)))^0.6+1300*(1500/(0.666666666666667*x(5)*x(6)+0.166666666666667*x(5)+0.166666666666667*x(6)))^0.6;

% Bounds
lb = [10,10,10,10,10,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,100,100,100,100,100,100]';
ub = [110,110,110,110,110,110,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,200,200,200,200,200,200]';

% Constraints
nlcon = @(x)[x(7)+x(12)+x(17);
             x(7)-x(8)+x(14)+x(20);
             x(9)+x(12)-x(13)+x(19);
             x(10)+x(15)+x(17)-x(18);
             -x(8)+x(9)+x(10)+x(11);
             -x(13)+x(14)+x(15)+x(16);
             -x(18)+x(19)+x(20)+x(21);
             x(25)*x(14)+x(27)*x(20)-x(22)*x(8)+100*x(7);
             x(23)*x(9)+x(27)*x(19)-x(24)*x(13)+100*x(12);
             x(23)*x(10)+x(25)*x(15)-x(26)*x(18)+100*x(17);
             x(8)*x(23)-x(8)*x(22);
             x(13)*x(25)-x(13)*x(24);
             x(18)*x(27)-x(18)*x(26);
             x(1)+x(23);
             x(2)+x(22);
             x(3)+x(25);
             x(4)+x(24);
             x(5)+x(27);
             x(6)+x(26)];
cl = [45,0,0,0,0,0,0,0,0,0,2000,1000,1500,210,130,210,160,210,180]';
cu = [45,0,0,0,0,0,0,0,0,0,2000,1000,1500,210,130,210,160,210,180]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCCCCCCCCCCCCCC';

% Starting Guess
x0 = [10,10,10,10,10,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100,100,100,100,100,100]';

% Options
opts = struct('probname','ex5_4_4');
opts.sense = 'min';
