% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 13:53:55
% Model: ex7_3_4

% Objective
fun = @(x)x(12);

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,0,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,10,Inf]';

% Constraints
nlcon = @(x)[x(11)^4*x(10)-x(11)^2*x(8)+x(6);
             x(11)^2*x(9)-x(7);
             -x(1)-x(12);
             x(1)-x(12);
             x(2)-0.1*x(12);
             -x(2)-0.1*x(12);
             -x(3)-0.1*x(12);
             x(3)-0.1*x(12);
             -x(4)-0.01*x(12);
             x(4)-0.01*x(12);
             -x(5)-0.005*x(12);
             x(5)-0.005*x(12);
             -54.387*x(3)*x(2)+x(6);
             -0.2*(1364.67*x(3)*x(2)-147.15*x(4)*x(3)*x(2))+5.544*x(5)+x(7);
             -3*(-9.81*x(2)^2*x(3)-9.81*x(3)*x(1)*x(2)-4.312*x(3)^2*x(2)+264.896*x(3)*x(2)+x(4)*x(5)-9.274*x(5))+x(8);
             -(7*x(3)^2*x(4)*x(2)-64.918*x(3)^2*x(2)+380.067*x(3)*x(2)+3*x(5)*x(2)+3*x(5)*x(1))+x(9);
             -x(3)^2*x(2)*(7*x(1)+4*x(2))+x(10)];
cl = [0,0,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,0,0,0,0,0]';
cu = [0,0,-10,10,1,-1,-1,1,-0.2,0.2,-0.05,0.05,0,0,0,0,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','ex7_3_4');
opts.sense = 'min';
