% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 13:53:54
% Model: ex7_2_4

% Objective
fun = @(x)0.4*x(1)^0.67/x(7)^0.67+0.4*x(2)^0.67/x(8)^0.67-x(1)-x(2)+10;

% Bounds
lb = [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1]';
ub = [10,10,10,10,10,10,10,10]';

% Constraints
nlcon = @(x)[0.0588*x(5)*x(7)+0.1*x(1);
             0.0588*x(6)*x(8)+0.1*x(1)+0.1*x(2);
             4*x(3)/x(5)+2/(x(3)^0.71*x(5))+0.0588*x(7)/x(3)^1.3;
             4*x(4)/x(6)+2/(x(4)^0.71*x(6))+0.0588*x(4)^1.3*x(8)];
cl = [-Inf,-Inf,-Inf,-Inf]';
cu = [1,1,1,1]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCC';

% Starting Guess
x0 = [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1]';

% Options
opts = struct('probname','ex7_2_4');
opts.sense = 'min';
