% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 14:33:57
% Model: ex8_4_6

% Objective
fun = @(x)((-0.1622+x(1))/x(1))^2+((-0.6791+x(2))/x(2))^2+((-0.679+x(3))/x(3))^2+((-0.3875+x(4))/x(4))^2+((-0.1822+x(5))/x(5))^2+((-0.1249+x(6))/x(6))^2+((-0.0857+x(7))/x(7))^2+((-0.0616+x(8))/x(8))^2;

% Bounds
lb = [0,0,0,0,0,0,0,0,-10,-10,-10,0,0,0]';
ub = [1,1,1,1,1,1,1,1,10,10,10,0.5,0.5,0.5]';

% Constraints
nlcon = @(x)[exp(-4*x(12))*x(9)+exp(-4*x(13))*x(10)+exp(-4*x(14))*x(11)-x(1);
             exp(-8*x(12))*x(9)+exp(-8*x(13))*x(10)+exp(-8*x(14))*x(11)-x(2);
             exp(-12*x(12))*x(9)+exp(-12*x(13))*x(10)+exp(-12*x(14))*x(11)-x(3);
             exp(-24*x(12))*x(9)+exp(-24*x(13))*x(10)+exp(-24*x(14))*x(11)-x(4);
             exp(-48*x(12))*x(9)+exp(-48*x(13))*x(10)+exp(-48*x(14))*x(11)-x(5);
             exp(-72*x(12))*x(9)+exp(-72*x(13))*x(10)+exp(-72*x(14))*x(11)-x(6);
             exp(-94*x(12))*x(9)+exp(-94*x(13))*x(10)+exp(-94*x(14))*x(11)-x(7);
             exp(-118*x(12))*x(9)+exp(-118*x(13))*x(10)+exp(-118*x(14))*x(11)-x(8)];
cl = [0,0,0,0,0,0,0,0]';
cu = [0,0,0,0,0,0,0,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCC';

% Starting Guess
x0 = [0.171747132,0.843266708,0.550375356,0.301137904,0.292212117,0.224052867,0.349830504,0.856270347,0.355,2.007,-4.575,0.015,0.11,0.285]';

% Options
opts = struct('probname','ex8_4_6');
opts.sense = 'min';
