% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 14:33:58
% Model: ex9_2_6

% Objective
fun = @(x)x(1)*x(1)-2*x(1)+x(2)*x(2)-2*x(2)+x(3)*x(3)+x(4)*x(4);

% Bounds
lb = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]';
ub = [Inf,Inf,Inf,Inf,200,200,200,200,200,200,200,200,200,200,200,200]';

% Constraints
nlcon = @(x)[-x(3)+x(5);
             -x(4)+x(6);
             x(3)+x(7);
             x(4)+x(8);
             x(5)*x(11);
             x(6)*x(12);
             x(7)*x(13);
             x(8)*x(14);
             x(9)*x(15);
             x(10)*x(16);
             -2*x(1)+2*x(3)-x(11)+x(13);
             -2*x(2)+2*x(4)-x(12)+x(14)];
cl = [-0.5,-0.5,1.5,1.5,0,0,0,0,0,0,0,0]';
cu = [-0.5,-0.5,1.5,1.5,0,0,0,0,0,0,0,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','ex9_2_6');
opts.sense = 'min';
