% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 14:33:58
% Model: ex9_1_8

% Objective
fun = @(x)-2*x(1)+x(2)+0.5*x(3);

% Bounds
lb = [0,0,0,0,0,0,0,0,0,0,0,0,0,0]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(1)+x(2);
             -2*x(1)+x(3)-x(4)+x(5);
             x(1)-3*x(2)+x(4)+x(6);
             -x(3)+x(7);
             -x(4)+x(8);
             x(10)*x(5);
             x(11)*x(6);
             x(12)*x(7);
             x(13)*x(8);
             x(14)*x(9);
             x(10)-x(12);
             x(10)+x(11)-x(13)];
cl = [-Inf,-2.5,2,0,0,0,0,0,0,0,4,-1]';
cu = [2,-2.5,2,0,0,0,0,0,0,0,4,-1]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','ex9_1_8');
opts.sense = 'min';
