% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 15:30:04
% Model: haverly

% Objective
fun = @(x)x(1)-x(2);

% Bounds
lb = [0,0,0,0,0,0,0,0,0,0,0,0]';
ub = [Inf,Inf,Inf,Inf,Inf,100,200,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(1)-6*x(3)-16*x(4)-10*x(5);
             x(2)-9*x(6)-15*x(7);
             x(6)-x(8)-x(10);
             x(7)-x(9)-x(11);
             x(3)+x(4)-x(10)-x(11);
             x(5)-x(8)-x(9);
             x(12)*(x(10)+x(11))-3*x(3)-x(4);
             x(12)*x(10)-2.5*x(10)-0.5*x(8);
             x(12)*x(11)-1.5*x(11)+0.5*x(9)];
cl = [0,0,0,0,0,0,0,-Inf,-Inf]';
cu = [0,0,0,0,0,0,0,0,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1]';

% Options
opts = struct('probname','haverly');
opts.sense = 'min';
