% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 15:32:31
% Model: least

% Objective
fun = @(x)(127-exp(-5*x(3))*x(2)-x(1))^2+(151-exp(-3*x(3))*x(2)-x(1))^2+(379-exp(-x(3))*x(2)-x(1))^2+(421-exp(5*x(3))*x(2)-x(1))^2+(460-exp(3*x(3))*x(2)-x(1))^2+(426-exp(x(3))*x(2)-x(1))^2;

% Bounds
lb = [-Inf,-Inf,-5]';
ub = [Inf,Inf,5]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [500,-150,-0.2]';

% Options
opts = struct('probname','least');
opts.sense = 'min';
