% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:01:28
% Model: prob07

% Objective
fun = @(x)x(15);

% Bounds
lb = [0,0,0,100,100,100,300,300,300,300,300,5,5,5,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(1)-1.2*x(4);
             x(1)-1.5*x(5);
             x(1)-1.1*x(6);
             x(2)-1.4*x(4);
             x(2)-1.2*x(6);
             x(3)-x(4);
             x(3)-x(5);
             x(3)-x(6);
             x(8)-x(9);
             x(10)-x(11);
             x(8)-x(11);
             -x(8)+x(9);
             592*x(1)^0.65+582*x(2)^0.39+1200*x(3)^0.52+370*x(7)^0.22+250*x(8)^0.4+210*x(9)^0.62+250*x(10)^0.4+200*x(11)^0.83-x(15);
             400000*x(12)/x(4)+300000*x(13)/x(5)+100000*x(14)/x(6);
             1.2*x(4)/x(7)-x(12);
             1.2*x(4)/x(8)-x(12);
             1.2*x(4)/x(9)-x(12);
             1.4*x(4)/x(10)-x(12);
             1.4*x(4)/x(11)-x(12);
             1.5*x(5)/x(7)-x(13);
             1.5*x(5)/x(8)-x(13);
             1.5*x(5)/x(9)-x(13);
             1.5*x(5)/x(11)-x(13);
             1.1*x(6)/x(7)-x(14);
             1.1*x(6)/x(8)-x(14);
             1.1*x(6)/x(9)-x(14);
             1.2*x(6)/x(10)-x(14);
             1.2*x(6)/x(11)-x(14);
             1.2*x(4)/x(7)+1.2*x(4)/x(8)-x(12);
             1.2*x(4)/x(9)+1.4*x(4)/x(10)-x(12);
             1.4*x(4)/x(11)-x(12);
             1.5*x(5)/x(7)+1.5*x(5)/x(8)-x(13);
             1.5*x(5)/x(11)-x(13);
             1.1*x(6)/x(7)+1.1*x(6)/x(8)-x(14);
             1.1*x(6)/x(9)+1.2*x(6)/x(10)-x(14);
             1.2*x(6)/x(11)-x(14)];
cl = [0,0,0,0,0,0,0,0,-Inf,-Inf,-Inf,0,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
cu = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,0,0,0,0,0,8000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-3,-1,-4,-6,-8,-2,-2,-4]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCC';

% Starting Guess
x0 = [1100.53862181846,1279.53722102267,913.955157873337,913.955157873337,733.692414545642,913.955157873337,1399.16837300491,365.579732331283,365.579732331283,459.625873931453,459.625873931453,6.78386433964926,10.3944267123785,7.13617632404846,155153.543657587]';

% Options
opts = struct('probname','prob07');
opts.sense = 'min';
