% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:02:58
% Model: st_bpv2

% Objective
fun = @(x)x(2)*x(3)+x(2)+x(3)-x(1)*x(3);

% Bounds
lb = [0,0,0,0]';
ub = [4,4,5,5]';

% Constraints
nlcon = @(x)[-4*x(1)-x(2);
             3*x(1)-x(2);
             4*x(3)-x(4);
             -x(3)-x(4);
             4*x(3)-x(4)];
cl = [-12,-1,-Inf,-8,-1]';
cu = [Inf,Inf,12,Inf,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','st_bpv2');
opts.sense = 'min';
