% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:02:58
% Model: st_bpv1

% Objective
fun = @(x)x(1)*x(3)+x(2)*x(4);

% Bounds
lb = [0,0,0,0]';
ub = [27,16,10,10]';

% Constraints
nlcon = @(x)[x(1)+3*x(2);
             2*x(1)+x(2);
             -1.6667*x(3)+x(4);
             x(3)+x(4)];
cl = [30,20,10,-Inf]';
cu = [Inf,Inf,Inf,15]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','st_bpv1');
opts.sense = 'min';
