% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:02:58
% Model: st_bsj3

% Objective
fun = @(x)10.5*x(1)-1.5*x(1)^2-x(2)^2-3.95*x(2)-x(3)^2+3*x(3)-2*x(4)^2+5*x(4)-x(5)^2+1.5*x(5)-2.5*x(6)^2-1.5*x(6);

% Bounds
lb = [0,0,0,0,0,0]';
ub = [99,99,99,99,99,99]';

% Constraints
nlcon = @(x)[x(1)+x(2)+x(3)+x(4)+x(5)+x(6)];
cl = -Inf';
cu = 10000000000';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','st_bsj3');
opts.sense = 'min';
