% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:02:58
% Model: st_cqpjk1

% Objective
fun = @(x)2*x(1)*x(1)-1.33333*x(1)+4*x(2)*x(2)-2.66667*x(2)+6*x(3)*x(3)-4*x(3)+0.5*x(4)*x(4)-10*x(4);

% Bounds
lb = [0,-Inf,-10000,-10000]';
ub = [Inf,Inf,10000,10000]';

% Constraints
nlcon = @(x)[-x(1)-x(2)-x(3)-x(4);
             x(1)+x(2)+x(3)+x(4)];
cl = [-Inf,-Inf]';
cu = [-1,1]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','st_cqpjk1');
opts.sense = 'min';
