% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:02:58
% Model: st_e04

% Objective
fun = @(x)400*x(1)^0.9+22*(-14.7+x(2))^1.2+x(3)+1000;

% Bounds
lb = [0,14.7,0,-459.67]';
ub = [15.1,94.2,5371,80]';

% Constraints
nlcon = @(x)[x(3)*x(1)+144*x(4);
             -exp(11.86-3950/(460+x(4)))+x(2)];
cl = [11520,0]';
cu = [Inf,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCC';

% Starting Guess
x0 = [NaN,14.7,NaN,NaN]';

% Options
opts = struct('probname','st_e04');
opts.sense = 'min';
