% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:02:59
% Model: st_e37

% Objective
fun = @(x)(-1.9837+x(3)+x(4))^2+(-0.8393+exp(-x(1))*x(3)+exp(-x(2))*x(4))^2+(-0.4305+exp(-2*x(1))*x(3)+exp(-2*x(2))*x(4))^2+(-0.2441+exp(-3*x(1))*x(3)+exp(-3*x(2))*x(4))^2+(-0.1248+exp(-4*x(1))*x(3)+exp(-4*x(2))*x(4))^2+(-0.0981+exp(-5*x(1))*x(3)+exp(-5*x(2))*x(4))^2+(-0.0549+exp(-6*x(1))*x(3)+exp(-6*x(2))*x(4))^2+(-0.0174+exp(-7*x(1))*x(3)+exp(-7*x(2))*x(4))^2+(-0.0249+exp(-8*x(1))*x(3)+exp(-8*x(2))*x(4))^2+(-0.0154+exp(-9*x(1))*x(3)+exp(-9*x(2))*x(4))^2+(-0.0127+exp(-10*x(1))*x(3)+exp(-10*x(2))*x(4))^2;

% Bounds
lb = [0,0,1,1]';
ub = [100,100,1,1]';

% Constraints
nlcon = @(x)[x(1)-x(2)];
cl = -Inf';
cu = 0';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCC';

% Starting Guess
x0 = [NaN,NaN,1,1]';

% Options
opts = struct('probname','st_e37');
opts.sense = 'min';
