% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:02:58
% Model: st_e02

% Objective
fun = @(x)x(3);

% Bounds
lb = [0,0,0]';
ub = [9.422,5.9023,267.417085245]';

% Constraints
nlcon = @(x)[30*x(1)-6*x(1)*x(1)-x(3);
             20*x(2)-12*x(2)*x(2)-x(3);
             0.5*(x(1)+x(2))^2-x(3)];
cl = [-250,-300,-150]';
cu = [-250,-300,-150]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [NaN,NaN,NaN]';

% Options
opts = struct('probname','st_e02');
opts.sense = 'min';
