% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:02:59
% Model: st_e21

% Objective
fun = @(x)x(1)^0.6+x(2)^0.6+x(3)^0.4-4*x(3)+2*x(4)+5*x(5)-x(6);

% Bounds
lb = [0,0,0,0,0,0]';
ub = [3,4,4,2,2,6]';

% Constraints
nlcon = @(x)[-3*x(1)+x(2)-3*x(4);
             -2*x(2)+x(3)-2*x(5);
             4*x(4)-x(6);
             x(1)+2*x(4);
             x(2)+x(5);
             x(3)+x(6)];
cl = [0,0,0,-Inf,-Inf,-Inf]';
cu = [0,0,0,4,4,6]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','st_e21');
opts.sense = 'min';
