% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:02:59
% Model: st_e41

% Objective
fun = @(x)200*x(1)^0.6+200*x(2)^0.6+200*x(3)^0.6+300*x(4)^0.6;

% Bounds
lb = [0.5,0.5,0.5,0.5]';
ub = [1,1,1,1]';

% Constraints
nlcon = @(x)[-(-(1-x(1))^2*x(3)*(1-x(4))^2-(1-(1-(1-x(1))*(1-x(4)))*x(2))^2*(1-x(3)));
             (-(1-x(1))^2*x(3)*(1-x(4))^2)-(1-(1-(1-x(1))*(1-x(4)))*x(2))^2*(1-x(3))];
cl = [-Inf,-Inf]';
cu = [0.1,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCC';

% Starting Guess
x0 = [0.5,0.5,0.5,0.5]';

% Options
opts = struct('probname','st_e41');
opts.sense = 'min';
