% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:03:00
% Model: st_glmp_kky

% Objective
fun = @(x)x(4)*x(5)+x(6)*x(7)+x(3);

% Bounds
lb = [0,0,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [10,10,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[-5*x(1)+8*x(2);
             -5*x(1)-8*x(2);
             -6*x(1)+3*x(2);
             -4*x(1)-5*x(2);
             5*x(1)-8*x(2);
             5*x(1)+8*x(2);
             6*x(1)-3*x(2);
             4*x(1)+5*x(2);
             3*x(1)-4*x(2)-x(3);
             x(1)+2*x(2)-x(4);
             2*x(1)-x(2)-x(5);
             x(1)-2*x(2)-x(6);
             2*x(1)+x(2)-x(7)];
cl = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,0,1.5,-4,-8.5,1]';
cu = [24,100,100,-10,100,44,15,100,0,1.5,-4,-8.5,1]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','st_glmp_kky');
opts.sense = 'min';
