% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:03:02
% Model: st_qpc-m1

% Objective
fun = @(x)10*x(1)-0.34*x(1)*x(1)-0.28*x(1)*x(2)+10*x(2)-0.22*x(1)*x(3)+10*x(3)-0.24*x(1)*x(4)+10*x(4)-0.51*x(1)*x(5)+10*x(5)-0.28*x(2)*x(1)-0.34*x(2)*x(2)-0.23*x(2)*x(3)-0.24*x(2)*x(4)-0.45*x(2)*x(5)-0.22*x(3)*x(1)-0.23*x(3)*x(2)-0.35*x(3)*x(3)-0.22*x(3)*x(4)-0.34*x(3)*x(5)-0.24*x(4)*x(1)-0.24*x(4)*x(2)-0.22*x(4)*x(3)-0.2*x(4)*x(4)-0.38*x(4)*x(5)-0.51*x(5)*x(1)-0.45*x(5)*x(2)-0.34*x(5)*x(3)-0.38*x(5)*x(4)-0.99*x(5)*x(5);

% Bounds
lb = [0,0,0,0,0]';
ub = [Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(1)+x(2)+2*x(3)+x(4)+x(5);
             2*x(1)+3*x(2)+x(5);
             x(2)+4*x(3)-x(4)+2*x(5);
             8*x(1)-x(2)-x(3)+6*x(4);
             -2*x(1)-x(2)-3*x(3)-x(4)-x(5)];
cl = [10,8,12,20,-30]';
cu = [Inf,Inf,Inf,Inf,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','st_qpc-m1');
opts.sense = 'min';
