% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:04:31
% Model: wall

% Objective
fun = @(x)x(1);

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(1)*x(2);
             x(3)/x(1)/x(4);
             x(5)/x(2)/x(6);
             x(6)*x(4);
             x(1)-x(2)+1e-7*x(3)-1e-5*x(5);
             2*x(1)-2*x(2)+1e-7*x(3)-0.01*x(4)-1e-5*x(5)+0.01*x(6)];
cl = [1,4.8,0.98,1,0,0]';
cu = [1,4.8,0.98,1,0,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCC';

% Starting Guess
x0 = [1,1,1,1,1,1]';

% Options
opts = struct('probname','wall');
opts.sense = 'min';
