% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 07-Jan-2016 11:23:48
% Model: inf_minlp_354

% Objective
fun = @(x)113.902929*x(1)*x(3)+110.73895875*x(2)*x(4);

% Bounds
lb = [-Inf,-Inf,0,0]';
ub = [Inf,Inf,2,2]';

% Constraints
nlcon = @(x)[-(x(3)*x(1)+x(4)*x(2));
             -(x(3)*x(1)+x(4)*x(2));
             113.902929*x(1)*x(3);
             113.902929*x(1)*x(3);
             110.73895875*x(2)*x(4);
             110.73895875*x(2)*x(4);
             -16.4475829476*x(1)*x(3);
             -15.9907056435*x(2)*x(4);
             -15.9907056435*x(2)*x(4);
             x(1)+x(2)];
cl = [-2.6,-Inf,-Inf,40,-Inf,40,-8.1748,-Inf,-9.6748,-Inf]';
cu = [Inf,4.7,67,Inf,67,Inf,Inf,-8.1748,Inf,1]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'BBCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','inf_minlp_354');
opts.sense = 'max';
