% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 07-Jan-2016 10:54:33
% Model: inf_minlp_307

% Objective
fun = @(x)x(238)+x(239)+x(240);

% Bounds
lb = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,100,100,100,100,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(2);
             x(2);
             x(3);
             x(2)-x(3);
             x(3);
             x(41);
             x(42);
             x(43);
             x(44);
             x(41)-x(45)-x(46)-x(47)-x(48)-x(49)-x(50)-x(51)-x(52)-x(53)-x(54)-x(55)-x(56)-x(57)-x(58)-x(59)-x(60)-x(61)-x(62)-x(63)-x(64)-x(65)-x(66)-x(67)-x(68)-x(69)-x(70)-x(71)-x(72)-x(73)-x(74);
             x(41);
             x(42)-x(75)-x(76)-x(77)-x(78)-x(79)-x(80)-x(81)-x(82)-x(83)-x(84)-x(85)-x(86)-x(87)-x(88)-x(89)-x(90)-x(91)-x(92)-x(93)-x(94)-x(95)-x(96)-x(97)-x(98)-x(99)-x(100)-x(101)-x(102)-x(103)-x(104);
             x(42);
             x(43)-x(105)-x(106)-x(107)-x(108)-x(109)-x(110)-x(111)-x(112)-x(113)-x(114)-x(115)-x(116)-x(117)-x(118)-x(119)-x(120)-x(121)-x(122)-x(123)-x(124)-x(125)-x(126)-x(127)-x(128)-x(129)-x(130)-x(131)-x(132)-x(133)-x(134)-x(135)-x(136)-x(137)-x(138)-x(139);
             x(43);
             x(44)-x(140)-x(141)-x(142)-x(143)-x(144)-x(145)-x(146)-x(147)-x(148)-x(149)-x(150)-x(151)-x(152)-x(153)-x(154)-x(155)-x(156)-x(157)-x(158)-x(159)-x(160)-x(161)-x(162)-x(163)-x(164)-x(165)-x(166)-x(167)-x(168)-x(169)-x(170)-x(171)-x(172)-x(173)-x(174)-x(175)-x(176)-x(177)-x(178)-x(179)-x(180)-x(181)-x(182)-x(183)-x(184)-x(185)-x(186)-x(187)-x(188)-x(189)-x(190)-x(191)-x(192)-x(193)-x(194)-x(195)-x(196)-x(197)-x(198)-x(199)-x(200)-x(201)-x(202)-x(203)-x(204);
             x(44);
             x(38);
             x(39);
             x(40);
             -x(38)-x(39)-x(40);
             x(47)+x(48)+x(49)+x(52)+x(57)+x(62)+x(67)+x(72)+x(77)+x(170)+x(171)+x(175)+x(176)+x(180)+x(181)+x(185)+x(186)+x(200)+x(201);
             x(45)+x(46)+x(47)+x(48)+x(49)+x(50)+x(51)+x(52)+x(53)+x(54)+x(55)+x(56)+x(57)+x(58)+x(59)+x(60)+x(61)+x(62)+x(63)+x(64)+x(65)+x(66)+x(67)+x(68)+x(69)+x(70)+x(71)+x(72)+x(73)+x(74)+x(75)+x(76)+x(77)+x(78)+x(79)+x(80)+x(81)+x(82)+x(83)+x(84)+x(85)+x(86)+x(87)+x(88)+x(89)+x(90)+x(91)+x(92)+x(93)+x(94)+x(95)+x(96)+x(97)+x(98)+x(99)+x(100)+x(101)+x(102)+x(103)+x(104)+x(105)+x(106)+x(107)+x(108)+x(109)+x(110)+x(111)+x(112)+x(113)+x(114)+x(115)+x(116)+x(117)+x(118)+x(119)+x(120)+x(121)+x(122)+x(123)+x(124)+x(125)+x(126)+x(127)+x(128)+x(129)+x(130)+x(131)+x(132)+x(133)+x(134)+x(135)+x(136)+x(137)+x(138)+x(139)+x(140)+x(141)+x(142)+x(143)+x(144)+x(145)+x(146)+x(147)+x(148)+x(149)+x(150)+x(151)+x(152)+x(153)+x(154)+x(155)+x(156)+x(157)+x(158)+x(159)+x(160)+x(161)+x(162)+x(163)+x(164)+x(165)+x(166)+x(167)+x(168)+x(169)+x(170)+x(171)+x(172)+x(173)+x(174)+x(175)+x(176)+x(177)+x(178)+x(179)+x(180)+x(181)+x(182)+x(183)+x(184)+x(185)+x(186)+x(187)+x(188)+x(189)+x(190)+x(191)+x(192)+x(193)+x(194)+x(195)+x(196)+x(197)+x(198)+x(199)+x(200)+x(201)+x(202)+x(203)+x(204);
             x(45)+x(46)+x(47)+x(48)+x(49)-5*x(205);
             x(50)+x(51)+x(52)+x(53)+x(54)-5*x(206);
             x(55)+x(56)+x(57)+x(58)+x(59)-5*x(207);
             x(60)+x(61)+x(62)+x(63)+x(64)-5*x(208);
             x(65)+x(66)+x(67)+x(68)+x(69)-5*x(209);
             x(70)+x(71)+x(72)+x(73)+x(74)-5*x(210);
             x(75)+x(76)+x(77)+x(78)+x(79)-5*x(211);
             x(80)+x(81)+x(82)+x(83)+x(84)-5*x(212);
             x(85)+x(86)+x(87)+x(88)+x(89)-5*x(213);
             x(90)+x(91)+x(92)+x(93)+x(94)-5*x(214);
             x(95)+x(96)+x(97)+x(98)+x(99)-5*x(215);
             x(100)+x(101)+x(102)+x(103)+x(104)-5*x(216);
             x(105)+x(106)+x(107)+x(108)+x(109)-5*x(217);
             x(110)+x(111)+x(112)+x(113)+x(114)-5*x(218);
             x(115)+x(116)+x(117)+x(118)+x(119)-5*x(219);
             x(120)+x(121)+x(122)+x(123)+x(124)-5*x(220);
             x(125)+x(126)+x(127)+x(128)+x(129)-5*x(221);
             x(130)+x(131)+x(132)+x(133)+x(134)-5*x(222);
             x(135)+x(136)+x(137)+x(138)+x(139)-5*x(223);
             x(140)+x(141)+x(142)+x(143)+x(144)-5*x(224);
             x(145)+x(146)+x(147)+x(148)+x(149)-5*x(225);
             x(150)+x(151)+x(152)+x(153)+x(154)-5*x(226);
             x(155)+x(156)+x(157)+x(158)+x(159)-5*x(227);
             x(160)+x(161)+x(162)+x(163)+x(164)-5*x(228);
             x(165)+x(166)+x(167)+x(168)+x(169)-5*x(229);
             x(170)+x(171)+x(172)+x(173)+x(174)-5*x(230);
             x(175)+x(176)+x(177)+x(178)+x(179)-5*x(231);
             x(180)+x(181)+x(182)+x(183)+x(184)-5*x(232);
             x(185)+x(186)+x(187)+x(188)+x(189)-5*x(233);
             x(190)+x(191)+x(192)+x(193)+x(194)-5*x(234);
             x(195)+x(196)+x(197)+x(198)+x(199)-5*x(235);
             x(200)+x(201)+x(202)+x(203)+x(204)-5*x(236);
             1.62074554294976*x(41)+x(241);
             0.94921689606075*x(42)+x(242);
             0.349907274572238*x(43)+x(243);
             0.5871645822324*x(44)+x(244);
             -((-2.13117512451205+0.00168259523489029*x(3))*(1-x(237))+(22.8100580110211-0.00103776424071979*x(3))*x(237))+x(248);
             x(3)-9000*x(237);
             0.0210592818784879*x(38)+x(245);
             0.00997605746209098*x(39)+x(246);
             -0.00999100809271655*x(40)+x(247);
             -x(241)-x(242)-x(243)-x(244)-x(245)-x(246)-x(247)-x(248)+x(249);
             x(1)-0.007969122*x(2)-0.307681209*x(249);
             -x(41);
             x(1);
             -1319976000*x(4)-1319976000*x(5)+x(238);
             -0.0161290322580645*x(6)-0.032258064516129*x(7)-0.032258064516129*x(8)-0.032258064516129*x(9)-0.032258064516129*x(10)-0.032258064516129*x(11)-0.032258064516129*x(12)-0.032258064516129*x(13)-0.032258064516129*x(14)-0.032258064516129*x(15)-0.032258064516129*x(16)-0.032258064516129*x(17)-0.032258064516129*x(18)-0.032258064516129*x(19)-0.032258064516129*x(20)-0.032258064516129*x(21)-0.032258064516129*x(22)-0.032258064516129*x(23)-0.032258064516129*x(24)-0.032258064516129*x(25)-0.032258064516129*x(26)-0.032258064516129*x(27)-0.032258064516129*x(28)-0.032258064516129*x(29)-0.032258064516129*x(30)-0.032258064516129*x(31)-0.032258064516129*x(32)-0.032258064516129*x(33)-0.032258064516129*x(34)-0.032258064516129*x(35)-0.032258064516129*x(36)-0.0161290322580645*x(37)+x(239);
             -0.00189393939393939*x(205)-0.00378787878787879*x(206)-0.00568181818181818*x(207)-0.00757575757575758*x(208)-0.00946969696969697*x(209)-0.0113636363636364*x(210)-0.0132575757575758*x(211)-0.0151515151515152*x(212)-0.0170454545454545*x(213)-0.0189393939393939*x(214)-0.0208333333333333*x(215)-0.0227272727272727*x(216)-0.0246212121212121*x(217)-0.0265151515151515*x(218)-0.0284090909090909*x(219)-0.0303030303030303*x(220)-0.0321969696969697*x(221)-0.0340909090909091*x(222)-0.0359848484848485*x(223)-0.0378787878787879*x(224)-0.0397727272727273*x(225)-0.0416666666666667*x(226)-0.0435606060606061*x(227)-0.0454545454545455*x(228)-0.0473484848484848*x(229)-0.0492424242424242*x(230)-0.0511363636363636*x(231)-0.053030303030303*x(232)-0.0549242424242424*x(233)-0.0568181818181818*x(234)-0.0587121212121212*x(235)-0.0606060606060606*x(236)+x(240);
             -x(1)+x(4)-x(5);
             x(6)-x(7)-x(205)+x(206);
             x(7)-x(8)-x(206)+x(207);
             x(8)-x(9)-x(207)+x(208);
             x(9)-x(10)-x(208)+x(209);
             x(10)-x(11)-x(209)+x(210);
             x(11)-x(12)-x(210)+x(211);
             x(12)-x(13)-x(211)+x(212);
             x(13)-x(14)-x(212)+x(213);
             x(14)-x(15)-x(213)+x(214);
             x(15)-x(16)-x(214)+x(215);
             x(16)-x(17)-x(215)+x(216);
             x(17)-x(18)-x(216)+x(217);
             x(18)-x(19)-x(217)+x(218);
             x(19)-x(20)-x(218)+x(219);
             x(20)-x(21)-x(219)+x(220);
             x(21)-x(22)-x(220)+x(221);
             x(22)-x(23)-x(221)+x(222);
             x(23)-x(24)-x(222)+x(223);
             x(24)-x(25)-x(223)+x(224);
             x(25)-x(26)-x(224)+x(225);
             x(26)-x(27)-x(225)+x(226);
             x(27)-x(28)-x(226)+x(227);
             x(28)-x(29)-x(227)+x(228);
             x(29)-x(30)-x(228)+x(229);
             x(30)-x(31)-x(229)+x(230);
             x(31)-x(32)-x(230)+x(231);
             x(32)-x(33)-x(231)+x(232);
             x(33)-x(34)-x(232)+x(233);
             x(34)-x(35)-x(233)+x(234);
             x(35)-x(36)-x(234)+x(235);
             x(36)-x(37)-x(235)+x(236)];
cl = [-Inf,-Inf,-Inf,63438,6852.274,-Inf,-Inf,-Inf,-Inf,0,-Inf,0,-Inf,0,-Inf,0,-Inf,-Inf,-Inf,-Inf,-600,0,100,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,0.00372771474878444,-0.244518272425249,-0.0445082053255887,-0.0038165697845106,0,0,0.137519216594714,0.0575,0.00932460785293236,0,-6.143686166,-Inf,-Inf,0,0,0,-12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]';
cu = [150000,133278.6,21200,63438,Inf,22,29,35,55,0,25,0,29,0,35,0,55,3157,3139,3014,-600,0,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00372771474878444,-0.244518272425249,-0.0445082053255887,-0.0038165697845106,0,Inf,0.137519216594714,0.0575,0.00932460785293236,0,-6.143686166,-10,24,0,0,0,-12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCIIIIBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','inf_minlp_307');
opts.sense = 'min';
