% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-May-2015 23:46:35
% Model: inf_nlp_24

% Objective
fun = @(x)(3.5+x(7)*x(3)+3*x(3)+0.5*x(7)+x(8)*x(5)+4*x(5)+0.5*x(8))*x(1)+(3.5+x(7)*x(4)+3*x(4)+0.5*x(7)+x(8)*x(6)+4*x(6)+0.5*x(8))*x(2)-(x(9)*(x(3)+x(5))+x(10)*(x(4)+x(6)))-((0.447213595499958-x(3)^0.5)*x(16)+(0.948683298050514-x(4)^0.5)*x(17)+(0.447213595499958-x(5)^0.5)*x(18)+(0.836660026534076-x(6)^0.5)*x(19))-((5-(x(3)^2+x(5)^2))*x(11)+(5-(x(4)^2+x(6)^2))*x(12))-((5-x(7)^2)*x(13)+(7-x(8)^2)*x(14))-(6-(x(7)^0.5+x(8)^0.5))*x(15);

% Bounds
lb = [0,0,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,0,0,0,0,0,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(1)+x(2);
             x(1)*x(3)+0.5*x(1)+2*x(13)*x(7)+2*x(15)*x(7);
             x(2)*x(4)+0.5*x(2)+2*x(13)*x(7)+2*x(15)*x(7);
             x(1)*x(5)+0.5*x(1)+2*x(14)*x(8)+2*x(15)*x(8);
             x(2)*x(6)+0.5*x(2)+2*x(14)*x(8)+2*x(15)*x(8);
             x(1)*x(7)+3*x(1)+2*x(16)*x(3)+2*x(11)*x(3)-x(9);
             x(2)*x(7)+3*x(2)+2*x(17)*x(4)+2*x(12)*x(4)-x(10);
             x(1)*x(8)+4*x(1)+2*x(18)*x(5)+2*x(11)*x(5)-x(9);
             x(2)*x(8)+4*x(2)+2*x(19)*x(6)+2*x(12)*x(6)-x(10)];
cl = [1,0,0,0,0,0,0,0,0]';
cu = [1,0,0,0,0,0,0,0,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','inf_nlp_24');
opts.sense = 'max';
