% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 07-Jan-2016 11:26:26
% Model: inf_minlp_357

% Objective
fun = @(x)20*x(5)+40*x(11);

% Bounds
lb = [0,0,0,0,0,0,0,0,0,0,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(2);
             x(3);
             x(4);
             x(2);
             x(3);
             x(4);
             x(1);
             x(11)+x(12);
             x(11)+x(12);
             x(13)+x(15);
             x(14)+x(16);
             x(13)+x(15);
             x(14)+x(16);
             x(5)-100000000*x(11);
             x(6)-100000000*x(12);
             x(7)-100000000*x(13);
             x(8)-100000000*x(14);
             x(9)-100000000*x(15);
             x(10)-100000000*x(16);
             -100000000*x(5)+x(11);
             -100000000*x(6)+x(12);
             -100000000*x(7)+x(13);
             -100000000*x(8)+x(14);
             -100000000*x(9)+x(15);
             -100000000*x(10)+x(16);
             x(1)-x(2)-100000000*x(11);
             -x(1)+x(2)-100000000*x(12);
             x(2)-x(3)-100000000*x(13);
             x(2)-x(4)-100000000*x(14);
             -x(2)+x(3)-100000000*x(15);
             -x(2)+x(4)-100000000*x(16);
             -x(1)+x(2)+100000000*x(11);
             x(1)-x(2)+100000000*x(12);
             -x(2)+x(3)+100000000*x(13);
             -x(2)+x(4)+100000000*x(14);
             x(2)-x(3)+100000000*x(15);
             x(2)-x(4)+100000000*x(16);
             x(7)-x(9);
             x(8)-x(10);
             x(5)-x(6)-x(7)-x(8)+x(9)+x(10);
             x(5);
             x(5);
             x(1)*x(1)-x(2)*x(2)-0.249149*x(5)*x(5);
             x(2)*x(2)-x(1)*x(1)-0.249149*x(6)*x(6);
             x(2)*x(2)-x(3)*x(3)-0.249149*x(7)*x(7);
             x(2)*x(2)-x(4)*x(4)-0.249149*x(8)*x(8);
             x(3)*x(3)-x(2)*x(2)-0.249149*x(9)*x(9);
             x(4)*x(4)-x(2)*x(2)-0.249149*x(10)*x(10)];
cl = [4000,4000,4000,-Inf,-Inf,-Inf,7500,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,2000000,3000000,0,0,-Inf,0,0,0,0,0,0]';
cu = [Inf,Inf,Inf,7500,7500,7500,7500,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,100000000,100000000,100000000,100000000,100000000,100000000,2000000,3000000,0,Inf,8000000,0,0,0,0,0,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCBBBBBB';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','inf_minlp_357');
opts.sense = 'min';
