% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 07-Jan-2016 10:30:45
% Model: inf_minlp_262

% Objective
fun = @(x)x(18)+x(19)+x(20)+x(21)+x(22)+x(23)+x(24)+x(25)+x(26)+x(27)+x(28)+x(29)+x(30)+x(31)+x(32)+x(33)+x(34)+x(35)+x(36)+x(37)+x(38)+x(39)+x(40)+x(41)+x(42)+x(43)+x(44)+x(45)+x(46)+x(47)+x(48)+x(49)+x(50)+x(51);

% Bounds
lb = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,0,Inf,0,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,0,Inf,0,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(18)+x(35);
             x(19)+x(36);
             x(20)+x(37);
             x(21)+x(38);
             x(22)+x(39);
             x(23)+x(40);
             x(24)+x(41);
             x(25)+x(42);
             x(26)+x(43);
             x(27)+x(44);
             x(28)+x(45);
             x(29)+x(46);
             x(30)+x(47);
             x(31)+x(48);
             x(32)+x(49);
             x(33)+x(50);
             x(34)+x(51);
             x(1)-1000*x(18)-1000*x(35);
             x(2)-1000*x(19)-1000*x(36);
             x(3)-1000*x(20)-1000*x(37);
             x(4)-1000*x(21)-1000*x(38);
             x(5)-1000*x(22)-1000*x(39);
             x(6)-1000*x(23)-1000*x(40);
             x(7)-1000*x(24)-1000*x(41);
             x(8)-1000*x(25)-1000*x(42);
             x(9)-1000*x(26)-1000*x(43);
             x(10)-1000*x(27)-1000*x(44);
             x(11)-1000*x(28)-1000*x(45);
             x(12)-1000*x(29)-1000*x(46);
             x(13)-1000*x(30)-1000*x(47);
             x(14)-1000*x(31)-1000*x(48);
             x(15)-1000*x(32)-1000*x(49);
             x(16)-1000*x(33)-1000*x(50);
             x(17)-1000*x(34)-1000*x(51);
             -x(18)+x(52)+x(53);
             -x(18)+x(54)+x(55);
             -x(18)+x(56)+x(57);
             -x(19)+x(58)+x(59);
             -x(19)+x(60)+x(61);
             -x(19)+x(62)+x(63);
             -x(20)+x(64)+x(65);
             -x(20)+x(66)+x(67);
             -x(21)+x(68)+x(69);
             -x(21)+x(70)+x(71);
             -x(22)+x(72)+x(73);
             -x(22)+x(74)+x(75);
             -x(23)+x(76)+x(77);
             -x(23)+x(78)+x(79);
             -x(24)+x(80)+x(81);
             -x(24)+x(82)+x(83);
             -x(25)+x(84)+x(85);
             -x(25)+x(86)+x(87);
             -x(26)+x(88)+x(89);
             -x(26)+x(90)+x(91);
             -x(27)+x(92)+x(93);
             -x(27)+x(94)+x(95);
             -x(28)+x(96)+x(97);
             -x(28)+x(98)+x(99);
             -x(28)+x(100)+x(101);
             -x(29)+x(102)+x(103);
             -x(29)+x(104)+x(105);
             -x(29)+x(106)+x(107);
             -x(30)+x(108)+x(109);
             -x(30)+x(110)+x(111);
             -x(30)+x(112)+x(113);
             -x(31)+x(114)+x(115);
             -x(31)+x(120)+x(121);
             -x(31)+x(116)+x(117);
             -x(31)+x(118)+x(119);
             -x(32)+x(122)+x(123);
             -x(32)+x(128)+x(129);
             -x(32)+x(124)+x(125);
             -x(32)+x(126)+x(127);
             -x(33)+x(130)+x(131);
             -x(33)+x(136)+x(137);
             -x(33)+x(132)+x(133);
             -x(33)+x(134)+x(135);
             -x(34)+x(138)+x(139);
             -x(34)+x(144)+x(145);
             -x(34)+x(140)+x(141);
             -x(34)+x(142)+x(143);
             2*x(52)*x(1)+2*x(146)*x(1)+2*x(58)*x(2)+2*x(152)*x(2)+26*x(74)*x(5)+26*x(168)*x(5)+26*x(78)*x(6)+26*x(172)*x(6)+26*x(82)*x(7)+26*x(176)*x(7)+26*x(86)*x(8)+26*x(180)*x(8)+26*x(90)*x(9)+26*x(184)*x(9)+26*x(94)*x(10)+26*x(188)*x(10)+26*x(98)*x(11)+26*x(192)*x(11)+26*x(104)*x(12)+26*x(198)*x(12)+26*x(110)*x(13)+26*x(204)*x(13)+26*x(116)*x(14)+26*x(210)*x(14)+26*x(124)*x(15)+26*x(218)*x(15)+26*x(132)*x(16)+26*x(226)*x(16)+26*x(140)*x(17)+26*x(234)*x(17);
             2*x(54)*x(1)+2*x(148)*x(1)+26*x(70)*x(4)+26*x(164)*x(4)+26*x(120)*x(14)+26*x(214)*x(14)+26*x(128)*x(15)+26*x(222)*x(15);
             2*x(60)*x(2)+2*x(154)*x(2)+26*x(136)*x(16)+26*x(230)*x(16)+26*x(144)*x(17)+26*x(238)*x(17);
             2*x(56)*x(1)+2*x(150)*x(1)-26*x(67)*x(3)-26*x(161)*x(3);
             2*x(35)*x(1)+26*x(45)*x(11)+26*x(46)*x(12)+26*x(47)*x(13)+26*x(48)*x(14)+26*x(49)*x(15)+26*x(50)*x(16)+26*x(51)*x(17);
             (-22*x(65)*x(3))-22*x(159)*x(3)-4*x(69)*x(4)-4*x(163)*x(4)-8*x(73)*x(5)-8*x(167)*x(5)-22*x(77)*x(6)-22*x(171)*x(6)-22*x(81)*x(7)-22*x(175)*x(7)-2*x(85)*x(8)-2*x(179)*x(8)-16*x(89)*x(9)-16*x(183)*x(9)-16*x(93)*x(10)-16*x(187)*x(10)-8*x(97)*x(11)-8*x(191)*x(11)-6*x(103)*x(12)-6*x(197)*x(12)-22*x(109)*x(13)-22*x(203)*x(13)-12*x(115)*x(14)-12*x(209)*x(14)+12*x(123)*x(15)+12*x(217)*x(15)-2*x(131)*x(16)-2*x(225)*x(16)+2*x(139)*x(17)+2*x(233)*x(17);
             5*x(53)*x(1)-5*x(147)*x(1)+3*x(55)*x(1)-3*x(149)*x(1)+11*x(57)*x(1)-11*x(151)*x(1)+7*x(35)*x(1)-7*x(18)*x(1)+5*x(59)*x(2)-5*x(153)*x(2)+4*x(61)*x(2)-4*x(155)*x(2)+8*x(63)*x(2)-8*x(157)*x(2)+5*x(36)*x(2)-5*x(19)*x(2)-143*x(65)*x(3)+143*x(159)*x(3)-143*x(67)*x(3)+143*x(161)*x(3)+11*x(20)*x(3)-11*x(20)*x(3)-26*x(69)*x(4)+26*x(163)*x(4)+39*x(71)*x(4)-39*x(165)*x(4)-52*x(73)*x(5)+52*x(167)*x(5)+65*x(75)*x(5)-65*x(169)*x(5)-143*x(77)*x(6)+143*x(171)*x(6)+65*x(79)*x(6)-65*x(173)*x(6)+91*x(23)*x(6)-91*x(40)*x(6)-143*x(81)*x(7)+143*x(81)*x(7)+65*x(83)*x(7)-65*x(177)*x(7)+91*x(24)*x(7)-91*x(41)*x(7)-13*x(85)*x(8)+13*x(179)*x(8)+65*x(87)*x(8)-65*x(181)*x(8)-104*x(89)*x(9)+104*x(89)*x(9)+65*x(91)*x(9)-65*x(185)*x(9)+91*x(26)*x(9)-91*x(43)*x(9)-104*x(93)*x(10)+104*x(187)*x(10)+65*x(95)*x(10)-65*x(189)*x(10)+91*x(27)*x(10)-91*x(44)*x(10)-52*x(97)*x(11)+52*x(191)*x(11)+104*x(101)*x(11)-104*x(195)*x(11)+65*x(99)*x(11)-65*x(193)*x(11)-39*x(103)*x(12)+39*x(197)*x(12)+104*x(107)*x(12)-104*x(201)*x(12)+65*x(105)*x(12)-65*x(199)*x(12)-13*x(29)*x(12)+13*x(46)*x(12)-143*x(109)*x(13)+143*x(203)*x(13)+104*x(113)*x(13)-104*x(207)*x(13)+65*x(111)*x(13)-65*x(205)*x(13)+91*x(30)*x(13)-91*x(47)*x(13)-78*x(115)*x(14)+78*x(209)*x(14)+104*x(119)*x(14)-104*x(213)*x(14)+65*x(117)*x(14)-65*x(211)*x(14)+39*x(121)*x(14)-39*x(215)*x(14)-13*x(31)*x(14)+13*x(48)*x(14)+78*x(123)*x(15)-78*x(217)*x(15)+104*x(127)*x(15)-104*x(221)*x(15)+65*x(125)*x(15)-65*x(219)*x(15)+39*x(129)*x(15)-39*x(223)*x(15)-91*x(32)*x(15)+91*x(49)*x(15)-13*x(131)*x(16)+13*x(225)*x(16)+104*x(135)*x(16)-104*x(229)*x(16)+65*x(133)*x(16)-65*x(227)*x(16)+52*x(137)*x(16)-52*x(231)*x(16)-52*x(33)*x(16)+52*x(50)*x(16)+13*x(139)*x(17)-13*x(233)*x(17)+104*x(143)*x(17)-104*x(237)*x(17)+65*x(141)*x(17)-65*x(235)*x(17)+52*x(145)*x(17)-52*x(239)*x(17)-65*x(34)*x(17)+65*x(51)*x(17);
             5*x(147)*x(1)+3*x(149)*x(1)+11*x(151)*x(1)-7*x(35)*x(1)+5*x(153)*x(2)+4*x(155)*x(2)+8*x(157)*x(2)-5*x(36)*x(2)+143*x(65)*x(3)+143*x(67)*x(3)+143*x(37)*x(3)+26*x(69)*x(4)+39*x(165)*x(4)+52*x(73)*x(5)+65*x(169)*x(5)+143*x(77)*x(6)+65*x(173)*x(6)+91*x(40)*x(6)+143*x(81)*x(7)+65*x(177)*x(7)+91*x(41)*x(7)+13*x(85)*x(8)+65*x(181)*x(8)+104*x(89)*x(9)+65*x(185)*x(9)+91*x(43)*x(9)+104*x(93)*x(10)+65*x(189)*x(10)+91*x(44)*x(10)+52*x(97)*x(11)+104*x(195)*x(11)+65*x(193)*x(11)+39*x(103)*x(12)+104*x(201)*x(12)+65*x(199)*x(12)-13*x(46)*x(12)+143*x(109)*x(13)+104*x(207)*x(13)+65*x(205)*x(13)+91*x(47)*x(13)+78*x(115)*x(14)+104*x(213)*x(14)+65*x(211)*x(14)+39*x(215)*x(14)-13*x(48)*x(14)-78*x(123)*x(15)+104*x(221)*x(15)+65*x(219)*x(15)+39*x(223)*x(15)-91*x(49)*x(15)+13*x(131)*x(16)+104*x(229)*x(16)+65*x(227)*x(16)+52*x(231)*x(16)-52*x(50)*x(16)-13*x(139)*x(17)+104*x(237)*x(17)+65*x(235)*x(17)+52*x(239)*x(17)-65*x(51)*x(17);
             -x(35)+x(146)+x(147);
             -x(35)+x(148)+x(149);
             -x(35)+x(150)+x(151);
             -x(36)+x(152)+x(153);
             -x(36)+x(154)+x(155);
             -x(36)+x(156)+x(157);
             -x(37)+x(158)+x(159);
             -x(37)+x(160)+x(161);
             -x(38)+x(162)+x(163);
             -x(38)+x(164)+x(165);
             -x(39)+x(166)+x(167);
             -x(39)+x(168)+x(169);
             -x(40)+x(170)+x(171);
             -x(40)+x(172)+x(173);
             -x(41)+x(174)+x(175);
             -x(41)+x(176)+x(177);
             -x(42)+x(178)+x(179);
             -x(42)+x(180)+x(181);
             -x(43)+x(182)+x(183);
             -x(43)+x(184)+x(185);
             -x(44)+x(186)+x(187);
             -x(44)+x(188)+x(189);
             -x(45)+x(190)+x(191);
             -x(45)+x(192)+x(193);
             -x(45)+x(194)+x(195);
             -x(46)+x(196)+x(197);
             -x(46)+x(198)+x(199);
             -x(46)+x(200)+x(201);
             -x(47)+x(202)+x(203);
             -x(47)+x(204)+x(205);
             -x(47)+x(206)+x(207);
             -x(48)+x(208)+x(209);
             -x(48)+x(214)+x(215);
             -x(48)+x(210)+x(211);
             -x(48)+x(212)+x(213);
             -x(49)+x(216)+x(217);
             -x(49)+x(222)+x(223);
             -x(49)+x(218)+x(219);
             -x(49)+x(220)+x(221);
             -x(50)+x(224)+x(225);
             -x(50)+x(230)+x(231);
             -x(50)+x(226)+x(227);
             -x(50)+x(228)+x(229);
             -x(51)+x(232)+x(233);
             -x(51)+x(238)+x(239);
             -x(51)+x(234)+x(235);
             -x(51)+x(236)+x(237)];
cl = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,26,0,0,0,0,-6,-13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]';
cu = [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,26,0,0,0,0,-6,-13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','inf_minlp_262');
opts.sense = 'min';
