% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 07-Jan-2016 10:11:18
% Model: inf_minlp_178

% Objective
fun = @(x)0.00184*x(1)*x(1)+9.2*x(1)+0.00184*x(2)*x(2)+9.2*x(2)+0.00184*x(3)*x(3)+9.2*x(3)+0.00184*x(4)*x(4)+9.2*x(4)+0.00184*x(5)*x(5)+9.2*x(5)+0.00184*x(6)*x(6)+9.2*x(6)+3450;

% Bounds
lb = [150,150,150,150,150,150,0,0,0,0,0,0,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,100000,60000,60000,60000,60000,60000,-Inf,-Inf]';
ub = [1500,1500,1500,1500,1500,1500,1000,1000,1000,1000,1000,1000,1100,1100,1100,1100,1100,1100,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,100000,120000,120000,120000,120000,60000,Inf,Inf]';

% Constraints
nlcon = @(x)[-x(1)-x(19);
             -x(2)-x(20);
             -x(3)-x(21);
             -x(4)-x(22);
             -x(5)-x(23);
             -x(6)-x(24);
             -x(25)-x(31)+x(37);
             -x(26)-x(32)+x(38);
             -x(27)-x(33)+x(39);
             -x(28)-x(34)+x(40);
             -x(29)-x(35)+x(41);
             -x(30)-x(36)+x(42);
             x(49)+x(50);
             x(37)+x(43)-x(44);
             x(38)+x(44)-x(45);
             x(39)+x(45)-x(46);
             x(40)+x(46)-x(47);
             x(41)+x(47)-x(48);
             x(42)+x(48);
             -x(7)-x(13)+x(19);
             -x(8)-x(14)+x(20);
             -x(9)-x(15)+x(21);
             -x(10)-x(16)+x(22);
             -x(11)-x(17)+x(23);
             -x(12)-x(18)+x(24);
             -x(49)*(330+4.97*x(7))+x(25);
             -x(49)*(330+4.97*x(8))+x(26);
             -x(49)*(330+4.97*x(9))+x(27);
             -x(49)*(330+4.97*x(10))+x(28);
             -x(49)*(330+4.97*x(11))+x(29);
             -x(49)*(330+4.97*x(12))+x(30);
             -(-6700+(-50+0.05*x(13))*(-1000+x(13))+12*x(13))*x(50)+x(31);
             -(-6700+(-50+0.05*x(14))*(-1000+x(14))+12*x(14))*x(50)+x(32);
             -(-6700+(-50+0.05*x(15))*(-1000+x(15))+12*x(15))*x(50)+x(33);
             -(-6700+(-50+0.05*x(16))*(-1000+x(16))+12*x(16))*x(50)+x(34);
             -(-6700+(-50+0.05*x(17))*(-1000+x(17))+12*x(17))*x(50)+x(35);
             -(-6700+(-50+0.05*x(18))*(-1000+x(18))+12*x(18))*x(50)+x(36)];
cl = [-1200,-1500,-1100,-1800,-950,-1300,0,0,0,0,0,0,1,2000,2000,2000,2000,2000,2000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]';
cu = [-1200,-1500,-1100,-1800,-950,-1300,0,0,0,0,0,0,1,2000,2000,2000,2000,2000,2000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBB';

% Starting Guess
x0 = [150,150,150,150,150,150,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100000,60000,60000,60000,60000,60000,NaN,NaN]';

% Options
opts = struct('probname','inf_minlp_178');
opts.sense = 'min';
