% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 07-Jan-2016 10:28:19
% Model: inf_minlp_253

% Objective
fun = @(x)((x(14)-x(7))/x(14))^2+((x(15)-x(8))/x(15))^2+((x(16)-x(9))/x(16))^2;

% Bounds
lb = [0,0,0,0,0,0,353,1,0,3.3e-05,10,2700,14,0,0,0]';
ub = [6,6,6,6,6,6,583,1.5,0.01,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(15);
             x(14);
             x(16);
             -14*x(1)-28*x(2)-44*x(3)-16*x(4)-43*x(5)-30*x(6)+x(13);
             -x(12)/x(13)+x(7);
             -2700*x(1)-27000*x(2)-8000*x(3)-4000*x(4)-12000*x(5)-13000*x(6)+x(12);
             -3.3e-5*x(1)-0.11*x(2)-0.075*x(3)-0.02*x(4)-0.75*x(5)-0.75*x(6)+x(10);
             -15.85*x(1)-13.4*x(2)-23*x(3)-10*x(4)-24.9*x(5)-19.15*x(6)+x(11);
             -x(13)/x(11)+x(8);
             -18*x(10)/x(13)+x(9)];
cl = [1.5,383,0.005,0,0,0,0,0,0,0]';
cu = [1.5,383,0.005,0,0,0,0,0,0,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'IIIIIICCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,353,1,NaN,3.3e-05,10,2700,14,383,1.5,0.005]';

% Options
opts = struct('probname','inf_minlp_253');
opts.sense = 'min';
