% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 13-May-2015 18:54:19
% Model: inf_lp_42

% Objective
fun = @(x)-0.1*x(3)+0.5*x(5);

% Bounds
lb = [0.5,0.5,-Inf,-Inf,-Inf]';
ub = [4,5,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[4*x(1)+3*x(2);
             -5*x(1)+2*x(2);
             0.166666666666667*x(1)-x(2);
             0.5*x(1)+0.25*x(2)-0.5*x(3)-x(4)+x(5);
             -5*x(1)-0.25*x(2)+5*x(3)+x(4)-x(5);
             -2.25*x(1)-2*x(2)+0.5*x(3)+4.5*x(4)-x(5);
             22.5*x(1)+2*x(2)-5*x(3)-4.5*x(4)+x(5);
             4*x(1)+16*x(2)-0.5*x(3)-8*x(4)+x(5);
             -40*x(1)-16*x(2)+5*x(3)+8*x(4)-x(5)];
cl = [12,10,-Inf,0.125,-1.25,-1,10,8,-80]';
cu = [Inf,Inf,-2.5,Inf,Inf,Inf,Inf,Inf,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCC';

% Starting Guess
x0 = [0.5,0.5,NaN,NaN,NaN]';

% Options
opts = struct('probname','inf_lp_42');
opts.sense = 'min';
