% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-May-2015 23:16:42
% Model: inf_nlp_132

% Objective
fun = @(x)24.55*x(1)+26.75*x(2)+39*x(3)+40.5*x(4);

% Bounds
lb = [0.963083088314,0.002644687941,0.033362566918,0.000911328296]';
ub = [0.963083088314,0.002644687941,0.033362566918,0.000911328296]';

% Constraints
nlcon = @(x)[x(1)+x(2)+x(3)+x(4);
             12*x(1)-1.645*(0.28*x(1)^2+0.19*x(2)^2+20.5*x(3)^2+0.62*x(4)^2)^0.5+11.9*x(2)+41.8*x(3)+52.1*x(4);
             2.3*x(1)+5.6*x(2)+11.1*x(3)+1.3*x(4)];
cl = [1,21,5]';
cu = [1,Inf,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCC';

% Starting Guess
x0 = [0.963083088314,0.002644687941,0.033362566918,0.000911328296]';

% Options
opts = struct('probname','inf_nlp_132');
opts.sense = 'min';
