% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-May-2015 17:31:43
% Model: inf_mip_87

% Objective
fun = @(x)29.35*x(1)+29.35*x(2)+29.35*x(3)+29.35*x(4)+29.35*x(5)+29.35*x(6)+26.84*x(7)+26.84*x(8)+26.84*x(9)+26.84*x(10)+26.84*x(11)+26.84*x(12)+27.05*x(13)+26.74*x(14)+27.05*x(15)+27.05*x(16)+27.05*x(17)+26.74*x(18)+25.34*x(19)+25.34*x(20)+25.34*x(21)+25.34*x(22)+25.34*x(23)+25.34*x(24)+25.94*x(25)+25.94*x(26)+25.91*x(27)+25.94*x(28)+25.94*x(29)+25.91*x(30)+25.84*x(31)+25.84*x(32)+25.84*x(33)+25.84*x(34)+25.84*x(35)+25.84*x(36)+26.56*x(37)+26.56*x(38)+26.39*x(39)+26.56*x(40)+26.56*x(41)+26.39*x(42)+24.94*x(43)+24.94*x(44)+24.94*x(45)+24.94*x(46)+24.94*x(47)+24.94*x(48)+25.84*x(49)+25.84*x(50)+25.84*x(51)+25.84*x(52)+25.84*x(53)+25.84*x(54)+32.66*x(55)+32.66*x(56)+32.66*x(57)+32.66*x(58)+32.66*x(59)+32.66*x(60)+31.94*x(61)+31.94*x(62)+31.94*x(63)+31.94*x(64)+31.94*x(65)+31.94*x(66)+0.61*x(68)+0.61*x(69)+0.61*x(71)+0.61*x(72)+0.61*x(74)+0.61*x(75)+0.61*x(77)+0.61*x(79)+0.61*x(80)+0.61*x(81);

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(1)+x(2)+x(3)+x(4)+x(5)+x(6);
             x(1)-x(7);
             x(2)-x(8);
             x(3)-x(9);
             x(4)-x(10);
             x(5)-x(11);
             x(6)-x(12);
             x(7)-x(13);
             x(8)-x(14);
             x(9)-x(15);
             x(10)-x(16);
             x(11)-x(17);
             x(12)-x(18);
             x(13)-x(19);
             x(14)-x(20);
             x(15)-x(21);
             x(16)-x(22);
             x(17)-x(23);
             x(18)-x(24);
             x(19)-x(25);
             x(20)-x(26);
             x(21)-x(27);
             x(22)-x(28);
             x(23)-x(29);
             x(24)-x(30);
             x(25)-x(31);
             x(26)-x(32);
             x(27)-x(33);
             x(28)-x(34);
             x(29)-x(35);
             x(30)-x(36);
             x(31)-x(37);
             x(32)-x(38);
             x(33)-x(39);
             x(34)-x(40);
             x(35)-x(41);
             x(36)-x(42);
             x(37);
             x(38);
             x(39);
             x(40);
             x(41);
             x(42);
             x(43)-x(49);
             x(44)-x(50);
             x(45)-x(51);
             x(46)-x(52);
             x(47)-x(53);
             x(48)-x(54);
             x(49)-x(55);
             x(50)-x(56);
             x(51)-x(57);
             x(52)-x(58);
             x(53)-x(59);
             x(54)-x(60);
             x(55)-x(61);
             x(56)-x(62);
             x(57)-x(63);
             x(58)-x(64);
             x(59)-x(65);
             x(60)-x(66);
             x(1);
             x(2);
             x(3);
             x(4);
             x(5);
             x(6);
             2*x(7)+2*x(13)+x(19)+2*x(25)+2*x(31)+2*x(37)+2*x(49)+2*x(55)+x(61);
             2*x(8)+2*x(14)+x(20)+2*x(26)+2*x(32)+2*x(38)+2*x(50)+2*x(56)+x(62);
             2*x(9)+2*x(15)+x(21)+2*x(27)+2*x(33)+2*x(39)+2*x(51)+2*x(57)+x(63);
             2*x(10)+2*x(16)+x(22)+2*x(28)+2*x(34)+2*x(40)+2*x(52)+2*x(58)+x(64);
             2*x(11)+2*x(17)+x(23)+2*x(29)+2*x(35)+2*x(41)+2*x(53)+2*x(59)+x(65);
             2*x(12)+2*x(18)+x(24)+2*x(30)+2*x(36)+2*x(42)+2*x(54)+2*x(60)+x(66);
             -x(67)+x(83);
             -x(68)+x(84);
             -x(69)+x(85);
             -x(70)+x(86);
             -x(71)+x(87);
             -x(72)+x(88);
             -x(73)+x(89);
             -x(74)+x(90);
             -x(75)+x(91);
             -x(76)+x(92);
             -x(77)+x(93);
             -x(78)+x(94);
             -x(79)+x(95);
             -x(80)+x(96);
             -x(81)+x(97);
             -x(82)+x(98);
             x(83);
             x(84);
             x(85);
             x(86);
             x(87);
             x(88);
             x(89);
             x(90);
             x(91);
             x(92);
             x(93);
             x(94);
             x(95);
             x(96);
             x(97);
             x(98)];
cl = [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,0,8,13,0,20,23,0,29,35,0,40,0,45,49,11,0]';
cu = [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7,7,7,7,7,7,17,17,17,17,17,17,0,10,15,0,22,25,0,31,37,0,42,0,47,51,13,0,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','inf_mip_87');
opts.sense = 'min';
