% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 07-Jan-2016 09:54:30
% Model: inf_minlp_145

% Objective
fun = @(x)x(183)+x(184)+x(185)+x(186)+x(187)+x(188)+x(189)+x(190)+x(191)+x(192)+x(193)+x(194)+x(195);

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(1);
             x(2);
             x(3);
             x(4);
             x(5);
             x(6);
             x(7);
             x(8);
             x(9);
             x(10);
             x(11);
             x(12);
             x(13);
             x(1);
             x(2);
             x(3);
             x(4);
             x(5);
             x(6);
             x(7);
             x(8);
             x(9);
             x(10);
             x(11);
             x(12);
             x(13);
             x(14)+x(15)+x(16)+x(17)+x(18)+x(19)+x(20)+x(21)+x(22)+x(23)+x(24)+x(25)+x(26);
             x(27)+x(28)+x(29)+x(30)+x(31)+x(32)+x(33)+x(34)+x(35)+x(36)+x(37)+x(38)+x(39);
             x(40)+x(41)+x(42)+x(43)+x(44)+x(45)+x(46)+x(47)+x(48)+x(49)+x(50)+x(51)+x(52);
             x(53)+x(54)+x(55)+x(56)+x(57)+x(58)+x(59)+x(60)+x(61)+x(62)+x(63)+x(64)+x(65);
             x(66)+x(67)+x(68)+x(69)+x(70)+x(71)+x(72)+x(73)+x(74)+x(75)+x(76)+x(77)+x(78);
             x(79)+x(80)+x(81)+x(82)+x(83)+x(84)+x(85)+x(86)+x(87)+x(88)+x(89)+x(90)+x(91);
             x(92)+x(93)+x(94)+x(95)+x(96)+x(97)+x(98)+x(99)+x(100)+x(101)+x(102)+x(103)+x(104);
             x(105)+x(106)+x(107)+x(108)+x(109)+x(110)+x(111)+x(112)+x(113)+x(114)+x(115)+x(116)+x(117);
             x(118)+x(119)+x(120)+x(121)+x(122)+x(123)+x(124)+x(125)+x(126)+x(127)+x(128)+x(129)+x(130);
             x(131)+x(132)+x(133)+x(134)+x(135)+x(136)+x(137)+x(138)+x(139)+x(140)+x(141)+x(142)+x(143);
             x(144)+x(145)+x(146)+x(147)+x(148)+x(149)+x(150)+x(151)+x(152)+x(153)+x(154)+x(155)+x(156);
             x(157)+x(158)+x(159)+x(160)+x(161)+x(162)+x(163)+x(164)+x(165)+x(166)+x(167)+x(168)+x(169);
             x(170)+x(171)+x(172)+x(173)+x(174)+x(175)+x(176)+x(177)+x(178)+x(179)+x(180)+x(181)+x(182);
             x(14)+x(27)+x(40)+x(53)+x(66)+x(79)+x(92)+x(105)+x(118)+x(131)+x(144)+x(157)+x(170);
             x(15)+x(28)+x(41)+x(54)+x(67)+x(80)+x(93)+x(106)+x(119)+x(132)+x(145)+x(158)+x(171);
             x(16)+x(29)+x(42)+x(55)+x(68)+x(81)+x(94)+x(107)+x(120)+x(133)+x(146)+x(159)+x(172);
             x(17)+x(30)+x(43)+x(56)+x(69)+x(82)+x(95)+x(108)+x(121)+x(134)+x(147)+x(160)+x(173);
             x(18)+x(31)+x(44)+x(57)+x(70)+x(83)+x(96)+x(109)+x(122)+x(135)+x(148)+x(161)+x(174);
             x(19)+x(32)+x(45)+x(58)+x(71)+x(84)+x(97)+x(110)+x(123)+x(136)+x(149)+x(162)+x(175);
             x(20)+x(33)+x(46)+x(59)+x(72)+x(85)+x(98)+x(111)+x(124)+x(137)+x(150)+x(163)+x(176);
             x(21)+x(34)+x(47)+x(60)+x(73)+x(86)+x(99)+x(112)+x(125)+x(138)+x(151)+x(164)+x(177);
             x(22)+x(35)+x(48)+x(61)+x(74)+x(87)+x(100)+x(113)+x(126)+x(139)+x(152)+x(165)+x(178);
             x(23)+x(36)+x(49)+x(62)+x(75)+x(88)+x(101)+x(114)+x(127)+x(140)+x(153)+x(166)+x(179);
             x(24)+x(37)+x(50)+x(63)+x(76)+x(89)+x(102)+x(115)+x(128)+x(141)+x(154)+x(167)+x(180);
             x(25)+x(38)+x(51)+x(64)+x(77)+x(90)+x(103)+x(116)+x(129)+x(142)+x(155)+x(168)+x(181);
             x(26)+x(39)+x(52)+x(65)+x(78)+x(91)+x(104)+x(117)+x(130)+x(143)+x(156)+x(169)+x(182);
             (x(1)*x(27)+x(2)*x(28)+x(3)*x(29)+x(4)*x(30)+x(5)*x(31)+x(6)*x(32)+x(7)*x(33)+x(8)*x(34)+x(9)*x(35)+x(10)*x(36)+x(11)*x(37)+x(12)*x(38)+x(13)*x(39)-(x(1)*x(14)+x(2)*x(15)+x(3)*x(16)+x(4)*x(17)+x(5)*x(18)+x(6)*x(19)+x(7)*x(20)+x(8)*x(21)+x(9)*x(22)+x(10)*x(23)+x(11)*x(24)+x(12)*x(25)+x(13)*x(26)))*x(184);
             (x(1)*x(40)+x(2)*x(41)+x(3)*x(42)+x(4)*x(43)+x(5)*x(44)+x(6)*x(45)+x(7)*x(46)+x(8)*x(47)+x(9)*x(48)+x(10)*x(49)+x(11)*x(50)+x(12)*x(51)+x(13)*x(52)-(x(1)*x(27)+x(2)*x(28)+x(3)*x(29)+x(4)*x(30)+x(5)*x(31)+x(6)*x(32)+x(7)*x(33)+x(8)*x(34)+x(9)*x(35)+x(10)*x(36)+x(11)*x(37)+x(12)*x(38)+x(13)*x(39)))*x(185);
             (x(1)*x(53)+x(2)*x(54)+x(3)*x(55)+x(4)*x(56)+x(5)*x(57)+x(6)*x(58)+x(7)*x(59)+x(8)*x(60)+x(9)*x(61)+x(10)*x(62)+x(11)*x(63)+x(12)*x(64)+x(13)*x(65)-(x(1)*x(40)+x(2)*x(41)+x(3)*x(42)+x(4)*x(43)+x(5)*x(44)+x(6)*x(45)+x(7)*x(46)+x(8)*x(47)+x(9)*x(48)+x(10)*x(49)+x(11)*x(50)+x(12)*x(51)+x(13)*x(52)))*x(186);
             (x(1)*x(66)+x(2)*x(67)+x(3)*x(68)+x(4)*x(69)+x(5)*x(70)+x(6)*x(71)+x(7)*x(72)+x(8)*x(73)+x(9)*x(74)+x(10)*x(75)+x(11)*x(76)+x(12)*x(77)+x(13)*x(78)-(x(1)*x(53)+x(2)*x(54)+x(3)*x(55)+x(4)*x(56)+x(5)*x(57)+x(6)*x(58)+x(7)*x(59)+x(8)*x(60)+x(9)*x(61)+x(10)*x(62)+x(11)*x(63)+x(12)*x(64)+x(13)*x(65)))*x(187);
             (x(1)*x(79)+x(2)*x(80)+x(3)*x(81)+x(4)*x(82)+x(5)*x(83)+x(6)*x(84)+x(7)*x(85)+x(8)*x(86)+x(9)*x(87)+x(10)*x(88)+x(11)*x(89)+x(12)*x(90)+x(13)*x(91)-(x(1)*x(66)+x(2)*x(67)+x(3)*x(68)+x(4)*x(69)+x(5)*x(70)+x(6)*x(71)+x(7)*x(72)+x(8)*x(73)+x(9)*x(74)+x(10)*x(75)+x(11)*x(76)+x(12)*x(77)+x(13)*x(78)))*x(188);
             (x(1)*x(92)+x(2)*x(93)+x(3)*x(94)+x(4)*x(95)+x(5)*x(96)+x(6)*x(97)+x(7)*x(98)+x(8)*x(99)+x(9)*x(100)+x(10)*x(101)+x(11)*x(102)+x(12)*x(103)+x(13)*x(104)-(x(1)*x(79)+x(2)*x(80)+x(3)*x(81)+x(4)*x(82)+x(5)*x(83)+x(6)*x(84)+x(7)*x(85)+x(8)*x(86)+x(9)*x(87)+x(10)*x(88)+x(11)*x(89)+x(12)*x(90)+x(13)*x(91)))*x(189);
             (x(1)*x(105)+x(2)*x(106)+x(3)*x(107)+x(4)*x(108)+x(5)*x(109)+x(6)*x(110)+x(7)*x(111)+x(8)*x(112)+x(9)*x(113)+x(10)*x(114)+x(11)*x(115)+x(12)*x(116)+x(13)*x(117)-(x(1)*x(92)+x(2)*x(93)+x(3)*x(94)+x(4)*x(95)+x(5)*x(96)+x(6)*x(97)+x(7)*x(98)+x(8)*x(99)+x(9)*x(100)+x(10)*x(101)+x(11)*x(102)+x(12)*x(103)+x(13)*x(104)))*x(190);
             (x(1)*x(118)+x(2)*x(119)+x(3)*x(120)+x(4)*x(121)+x(5)*x(122)+x(6)*x(123)+x(7)*x(124)+x(8)*x(125)+x(9)*x(126)+x(10)*x(127)+x(11)*x(128)+x(12)*x(129)+x(13)*x(130)-(x(1)*x(105)+x(2)*x(106)+x(3)*x(107)+x(4)*x(108)+x(5)*x(109)+x(6)*x(110)+x(7)*x(111)+x(8)*x(112)+x(9)*x(113)+x(10)*x(114)+x(11)*x(115)+x(12)*x(116)+x(13)*x(117)))*x(191);
             (x(1)*x(131)+x(2)*x(132)+x(3)*x(133)+x(4)*x(134)+x(5)*x(135)+x(6)*x(136)+x(7)*x(137)+x(8)*x(138)+x(9)*x(139)+x(10)*x(140)+x(11)*x(141)+x(12)*x(142)+x(13)*x(143)-(x(1)*x(118)+x(2)*x(119)+x(3)*x(120)+x(4)*x(121)+x(5)*x(122)+x(6)*x(123)+x(7)*x(124)+x(8)*x(125)+x(9)*x(126)+x(10)*x(127)+x(11)*x(128)+x(12)*x(129)+x(13)*x(130)))*x(192);
             (x(1)*x(144)+x(2)*x(145)+x(3)*x(146)+x(4)*x(147)+x(5)*x(148)+x(6)*x(149)+x(7)*x(150)+x(8)*x(151)+x(9)*x(152)+x(10)*x(153)+x(11)*x(154)+x(12)*x(155)+x(13)*x(156)-(x(1)*x(131)+x(2)*x(132)+x(3)*x(133)+x(4)*x(134)+x(5)*x(135)+x(6)*x(136)+x(7)*x(137)+x(8)*x(138)+x(9)*x(139)+x(10)*x(140)+x(11)*x(141)+x(12)*x(142)+x(13)*x(143)))*x(193);
             (x(1)*x(157)+x(2)*x(158)+x(3)*x(159)+x(4)*x(160)+x(5)*x(161)+x(6)*x(162)+x(7)*x(163)+x(8)*x(164)+x(9)*x(165)+x(10)*x(166)+x(11)*x(167)+x(12)*x(168)+x(13)*x(169)-(x(1)*x(144)+x(2)*x(145)+x(3)*x(146)+x(4)*x(147)+x(5)*x(148)+x(6)*x(149)+x(7)*x(150)+x(8)*x(151)+x(9)*x(152)+x(10)*x(153)+x(11)*x(154)+x(12)*x(155)+x(13)*x(156)))*x(194);
             (x(1)*x(170)+x(2)*x(171)+x(3)*x(172)+x(4)*x(173)+x(5)*x(174)+x(6)*x(175)+x(7)*x(176)+x(8)*x(177)+x(9)*x(178)+x(10)*x(179)+x(11)*x(180)+x(12)*x(181)+x(13)*x(182)-(x(1)*x(157)+x(2)*x(158)+x(3)*x(159)+x(4)*x(160)+x(5)*x(161)+x(6)*x(162)+x(7)*x(163)+x(8)*x(164)+x(9)*x(165)+x(10)*x(166)+x(11)*x(167)+x(12)*x(168)+x(13)*x(169)))*x(195)];
cl = [3,4,9,11,14,18,22,28,32,37,40,48,52,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,6,6,6,6,6,6,6,6,6,6,6,6]';
cu = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,10,7,15,20,16,23,30,40,35,45,50,55,60,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','inf_minlp_145');
opts.sense = 'max';
