% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 01-Jun-2015 14:34:35
% Model: inf_nlp_99

% Objective
fun = @(x)log(x(1))*x(1)+log(x(2))*x(2)-log(x(3)-x(5))+x(3)-log(1+x(5)/x(3))*x(4)/x(5)+5.0464317551216*x(1)+0.366877055769689*x(2)-1;

% Bounds
lb = [0.0772,0.9228,0.1641,0.4121,0.0766]';
ub = [0.0772,0.9228,0.1641,0.4121,0.0766]';

% Constraints
nlcon = @(x)[x(3)^3-x(3)^2+(-x(5)^2-x(5)+x(4))*x(3)-x(4)*x(5);
             -(1.04633*x(1)*x(1)+0.579822*x(1)*x(2)+0.579822*x(2)*x(1)+0.379615*x(2)*x(2))+x(4);
             -0.0771517*x(1)-0.0765784*x(2)+x(5);
             x(1)+x(2)];
cl = [0,0,0,1]';
cu = [0,0,0,1]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCC';

% Starting Guess
x0 = [0.0772,0.9228,0.1641,0.4121,0.0766]';

% Options
opts = struct('probname','inf_nlp_99');
opts.sense = 'min';
