% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-May-2015 16:38:07
% Model: inf_mip_39

% Objective
fun = @(x)x(1)+x(2)+x(3)+x(4)+x(5)+x(6)+x(7)+x(8)+x(9)+x(10)+x(11)+x(12)+x(13)+x(14)+x(15)+x(16)+x(17)+x(18)+x(19)+x(20)+x(21)+x(22)+x(23)+x(24)+x(25)+x(26)+x(27)+x(28)+x(29)+x(30)-0.01*x(87)-0.01*x(88);

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(1)+x(2)+x(3);
             x(1)+x(3)+x(4)-3.1*x(53);
             x(2)+x(5)+x(7);
             x(4)+x(12)+x(13)+x(14)+x(15)+x(16)-6.1*x(62);
             x(12)+x(13)-2.1*x(63);
             x(12)+x(14)+x(15)-3.1*x(64);
             x(12)+x(14)+x(15)+x(18)+x(23)-5.1*x(65);
             x(12)+x(16)+x(17)-3.1*x(66);
             x(10)+x(16)+x(17)-3.1*x(67);
             x(15)+x(18)+x(19)-3.1*x(68);
             x(18)+x(19)+x(20)-3.1*x(69);
             x(10)+x(19)+x(20)-3.1*x(70);
             x(15)+x(23)+x(24)-3.1*x(73);
             x(1)+x(2)+x(3)-3.1*x(51);
             x(1)+x(2)+x(4)+x(5)+x(6)-5.1*x(52);
             x(1)+x(3)+x(4);
             x(2)+x(3)+x(4)+x(6)+x(12)-5.1*x(54);
             x(2)+x(5)+x(7)-3.1*x(55);
             x(2)+x(4)+x(6)+x(7)+x(8)+x(9)+x(10)+x(28)-8.1*x(56);
             x(5)+x(6)+x(7)-3.1*x(57);
             x(6)+x(8)+x(28)-3.1*x(58);
             x(6)+x(9)+x(10)+x(11)-4.1*x(59);
             x(6)+x(9)+x(10)+x(17)+x(20)+x(21)+x(22)-7.1*x(60);
             x(9)+x(11)-2.1*x(61);
             x(4)+x(12)+x(13)+x(14)+x(15)+x(16);
             x(12)+x(13);
             x(12)+x(14)+x(15);
             x(12)+x(14)+x(15)+x(18)+x(23);
             x(12)+x(16)+x(17);
             x(10)+x(16)+x(17);
             x(15)+x(18)+x(19);
             x(18)+x(19)+x(20);
             x(10)+x(19)+x(20);
             x(10)+x(21)+x(22)-3.1*x(71);
             x(10)+x(21)+x(22)+x(24)-4.1*x(72);
             x(15)+x(23)+x(24);
             x(22)+x(23)+x(24)+x(25)-4.1*x(74);
             x(24)+x(25)+x(26)+x(27)-4.1*x(75);
             x(25)+x(26)-2.1*x(76);
             x(25)+x(27)+x(28)+x(29)+x(30)-5.1*x(77);
             x(6)+x(8)+x(27)+x(28)-4.1*x(78);
             x(27)+x(29)+x(30)-3.1*x(79);
             x(27)+x(29)+x(30)-3.1*x(80);
             x(1)+x(2)+x(4)+x(5)+x(6)-x(52);
             x(2)+x(3)+x(4)+x(6)+x(12)-x(54);
             x(2)+x(4)+x(6)+x(7)+x(8)+x(9)+x(10)+x(28)-x(56);
             x(5)+x(6)+x(7)-x(57);
             x(6)+x(8)+x(28)-x(58);
             x(6)+x(9)+x(10)+x(11)-x(59);
             x(6)+x(9)+x(10)+x(17)+x(20)+x(21)+x(22)-x(60);
             x(9)+x(11)-x(61);
             x(10)+x(21)+x(22)-x(71);
             x(10)+x(21)+x(22)+x(24)-x(72);
             x(22)+x(23)+x(24)+x(25)-x(74);
             x(24)+x(25)+x(26)+x(27)-x(75);
             x(25)+x(26)-x(76);
             x(25)+x(27)+x(28)+x(29)+x(30)-x(77);
             x(6)+x(8)+x(27)+x(28)-x(78);
             x(27)+x(29)+x(30)-x(79);
             x(27)+x(29)+x(30)-x(80);
             x(81);
             x(81);
             x(82);
             x(82);
             x(83);
             x(83);
             x(84);
             x(84);
             x(85);
             x(85);
             x(86);
             x(86);
             x(31)+x(32)+x(33)+x(34)+x(35)+x(52)+x(54)+x(57)-x(81);
             x(36)+x(37)+x(38)+x(61)-x(82);
             x(39)+x(40)+x(71)+x(72)-x(83);
             x(41)+x(42)+x(43)+x(76)-x(84);
             x(44)+x(45)+x(46)+x(79)+x(80)-x(85);
             x(47)+x(48)+x(49)+x(50)-x(86);
             x(31)+x(36)+x(47);
             x(32)+x(48);
             x(33)+x(37);
             x(34)+x(38)+x(39);
             x(40)+x(41);
             x(42)+x(44);
             x(43)+x(45)+x(49);
             x(35)+x(46)+x(50);
             -3*x(1)-5*x(2)-3*x(3)-5*x(4)-3*x(5)-8*x(6)-3*x(7)-3*x(8)-4*x(9)-7*x(10)-2*x(11)-6*x(12)-2*x(13)-3*x(14)-5*x(15)-3*x(16)-3*x(17)-3*x(18)-3*x(19)-3*x(20)-3*x(21)-4*x(22)-3*x(23)-4*x(24)-4*x(25)-2*x(26)-5*x(27)-4*x(28)-3*x(29)-3*x(30)+x(87);
             x(51)+x(52)+x(53)+x(54)+x(55)+x(56)+x(57)+x(58)+x(59)+x(60)+x(61)+x(62)+x(63)+x(64)+x(65)+x(66)+x(67)+x(68)+x(69)+x(70)+x(71)+x(72)+x(73)+x(74)+x(75)+x(76)+x(77)+x(78)+x(79)+x(80)+x(88)];
cl = [1,-Inf,1,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,1,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,1,1,1,1,1,1,1,1,1,-Inf,-Inf,1,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,-Inf,0,-Inf,1,-Inf,0,-Inf,1,-Inf,-1,-Inf,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,30]';
cu = [Inf,0.9,Inf,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,Inf,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,0.9,0.9,Inf,0.9,0.9,0.9,0.9,0.9,0.9,0.9,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,7,Inf,3,Inf,3,Inf,3,Inf,4,Inf,3,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,0,30]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','inf_mip_39');
opts.sense = 'min';
