% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 20:48:52
% Model: catena

% Objective
fun = @(x)222.954545454545*x(13)+445.909090909091*x(14)+445.909090909091*x(15)+445.909090909091*x(16)+445.909090909091*x(17)+445.909090909091*x(18)+445.909090909091*x(19)+445.909090909091*x(20)+445.909090909091*x(21)+445.909090909091*x(22)+445.909090909091*x(23)+222.954545454545*x(24);

% Bounds
lb = [0,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,6.6,0,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,0,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [0,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,6.6,0,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,0,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[(x(2)-x(1))^2+(x(14)-x(13))^2+(x(26)-x(25))^2;
             (x(3)-x(2))^2+(x(15)-x(14))^2+(x(27)-x(26))^2;
             (x(4)-x(3))^2+(x(16)-x(15))^2+(x(28)-x(27))^2;
             (x(5)-x(4))^2+(x(17)-x(16))^2+(x(29)-x(28))^2;
             (x(6)-x(5))^2+(x(18)-x(17))^2+(x(30)-x(29))^2;
             (x(7)-x(6))^2+(x(19)-x(18))^2+(x(31)-x(30))^2;
             (x(8)-x(7))^2+(x(20)-x(19))^2+(x(32)-x(31))^2;
             (x(9)-x(8))^2+(x(21)-x(20))^2+(x(33)-x(32))^2;
             (x(10)-x(9))^2+(x(22)-x(21))^2+(x(34)-x(33))^2;
             (x(11)-x(10))^2+(x(23)-x(22))^2+(x(35)-x(34))^2;
             (x(12)-x(11))^2+(x(24)-x(23))^2+(x(36)-x(35))^2];
cl = [1,1,1,1,1,1,1,1,1,1,1]';
cu = [1,1,1,1,1,1,1,1,1,1,1]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','catena');
opts.sense = 'min';
