% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 00:23:17
% Model: eigmaxc

% Objective
fun = @(x)-x(1);

% Bounds
lb = [-Inf,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1]';
ub = [Inf,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]';

% Constraints
nlcon = @(x)[x(2)*x(2)+x(3)*x(3)+x(4)*x(4)+x(5)*x(5)+x(6)*x(6)+x(7)*x(7)+x(8)*x(8)+x(9)*x(9)+x(10)*x(10)+x(11)*x(11)+x(12)*x(12)+x(13)*x(13)+x(14)*x(14)+x(15)*x(15)+x(16)*x(16)+x(17)*x(17)+x(18)*x(18)+x(19)*x(19)+x(20)*x(20)+x(21)*x(21)+x(22)*x(22);
             x(2)*x(1)-10*x(2)-x(3);
             x(3)*x(1)-9*x(3)-x(2)-x(4);
             x(4)*x(1)-8*x(4)-x(3)-x(5);
             x(5)*x(1)-7*x(5)-x(4)-x(6);
             x(6)*x(1)-6*x(6)-x(5)-x(7);
             x(7)*x(1)-5*x(7)-x(6)-x(8);
             x(8)*x(1)-4*x(8)-x(7)-x(9);
             x(9)*x(1)-3*x(9)-x(8)-x(10);
             x(10)*x(1)-2*x(10)-x(9)-x(11);
             x(11)*x(1)-x(11)-x(10)-x(12);
             x(12)*x(1)-x(11)-x(13);
             x(13)*x(1)+x(13)-x(12)-x(14);
             x(14)*x(1)+2*x(14)-x(13)-x(15);
             x(15)*x(1)+3*x(15)-x(14)-x(16);
             x(16)*x(1)+4*x(16)-x(15)-x(17);
             x(17)*x(1)+5*x(17)-x(16)-x(18);
             x(18)*x(1)+6*x(18)-x(17)-x(19);
             x(19)*x(1)+7*x(19)-x(18)-x(20);
             x(20)*x(1)+8*x(20)-x(19)-x(21);
             x(21)*x(1)+9*x(21)-x(20)-x(22);
             x(22)*x(1)+10*x(22)-x(21)];
cl = [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]';
cu = [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','eigmaxc');
opts.sense = 'min';
