% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 00:56:37
% Model: expfit

% Objective
fun = @(x)(-0.25+exp(0.25*x(2))*x(1))^2+(-0.5+exp(0.5*x(2))*x(1))^2+(-0.75+exp(0.75*x(2))*x(1))^2+(-1+exp(x(2))*x(1))^2+(-1.25+exp(1.25*x(2))*x(1))^2+(-1.5+exp(1.5*x(2))*x(1))^2+(-1.75+exp(1.75*x(2))*x(1))^2+(-2+exp(2*x(2))*x(1))^2+(-2.25+exp(2.25*x(2))*x(1))^2+(-2.5+exp(2.5*x(2))*x(1))^2;

% Bounds
lb = [-Inf,-Inf]';
ub = [Inf,Inf]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CC';

% Starting Guess
x0 = [NaN,NaN]';

% Options
opts = struct('probname','expfit');
opts.sense = 'min';
