% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 01:46:38
% Model: growth

% Objective
fun = @(x)(-8+exp(2.07944154167984*x(2)+4.32407712526381*x(3))*x(1))^2+(-8.4305+exp(2.19722457733622*x(2)+4.82779584325033*x(3))*x(1))^2+(-9.5294+exp(2.30258509299405*x(2)+5.3018981104784*x(3))*x(1))^2+(-10.4627+exp(2.39789527279837*x(2)+5.74990173930877*x(3))*x(1))^2+(-12+exp(2.484906649788*x(2)+6.17476105816062*x(3))*x(1))^2+(-13.0205+exp(2.56494935746154*x(2)+6.57896520634235*x(3))*x(1))^2+(-14.5949+exp(2.63905732961526*x(2)+6.96462358899602*x(3))*x(1))^2+(-16.1078+exp(2.70805020110221*x(2)+7.33353589168972*x(3))*x(1))^2+(-18.0596+exp(2.77258872223978*x(2)+7.68724822269122*x(3))*x(1))^2+(-20.4569+exp(2.89037175789616*x(2)+8.35424889884376*x(3))*x(1))^2+(-24.25+exp(2.99573227355399*x(2)+8.97441185481296*x(3))*x(1))^2+(-32.9863+exp(3.2188758248682*x(2)+10.3611615759209*x(3))*x(1))^2;

% Bounds
lb = [-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [NaN,NaN,NaN]';

% Options
opts = struct('probname','growth');
opts.sense = 'min';
