% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 01:46:38
% Model: haifas

% Objective
fun = @(x)x(1);

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[-5*x(2)*x(2)+x(1)+x(5);
             -(3.2*x(3)*x(3)+3.2*x(3)*x(6)+0.8*x(6)*x(6))+x(1)+x(5);
             -(20*x(5)*x(5)-40*x(5)*x(6)+20*x(6)*x(6)-x(5))+x(1);
             -(3.2*x(2)*x(2)-3.2*x(2)*x(5)+0.8*x(5)*x(5)-x(5))+x(1);
             -5*x(3)*x(3)+x(1)+x(5);
             -(3.2*x(4)*x(4)+3.2*x(4)*x(7)+0.8*x(7)*x(7))+x(1)+x(5);
             -(20*x(6)*x(6)-40*x(6)*x(7)+20*x(7)*x(7))+x(1)+x(5);
             -(3.2*x(3)*x(3)-3.2*x(3)*x(6)+0.8*x(6)*x(6))+x(1)+x(5);
             -5*x(4)*x(4)+x(1)+x(5)];
cl = [0,0,0,0,0,0,0,0,0]';
cu = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','haifas');
opts.sense = 'min';
