% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 12:35:50
% Model: hatfldg

% Objective
fun = @(x)-0;

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(2)*(x(1)-x(3))+x(2)-x(13);
             x(3)*(x(2)-x(4))+x(3)-x(13);
             x(4)*(x(3)-x(5))+x(4)-x(13);
             x(5)*(x(4)-x(6))+x(5)-x(13);
             x(6)*(x(5)-x(7))+x(6)-x(13);
             x(7)*(x(6)-x(8))+x(7)-x(13);
             x(8)*(x(7)-x(9))+x(8)-x(13);
             x(9)*(x(8)-x(10))+x(9)-x(13);
             x(10)*(x(9)-x(11))+x(10)-x(13);
             x(11)*(x(10)-x(12))+x(11)-x(13);
             x(12)*(x(11)-x(13))+x(12)-x(13);
             x(13)*(x(12)-x(14))+x(13)-x(13);
             x(14)*(x(13)-x(15))+x(14)-x(13);
             x(15)*(x(14)-x(16))+x(15)-x(13);
             x(16)*(x(15)-x(17))+x(16)-x(13);
             x(17)*(x(16)-x(18))+x(17)-x(13);
             x(18)*(x(17)-x(19))+x(18)-x(13);
             x(19)*(x(18)-x(20))+x(19)-x(13);
             x(20)*(x(19)-x(21))+x(20)-x(13);
             x(21)*(x(20)-x(22))+x(21)-x(13);
             x(22)*(x(21)-x(23))+x(22)-x(13);
             x(23)*(x(22)-x(24))+x(23)-x(13);
             x(24)*(x(23)-x(25))+x(24)-x(13);
             x(1)-x(1)*x(2)-x(13);
             x(24)*x(25)+x(25)-x(13)];
cl = [-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1]';
cu = [-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCCCCCCCCCCCC';

% Starting Guess
x0 = [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]';

% Options
opts = struct('probname','hatfldg');
opts.sense = 'min';
