% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 12:35:51
% Model: himmelbd

% Objective
fun = @(x)-0;

% Bounds
lb = -Inf';
ub = Inf';

% Constraints
nlcon = @(x)[84*x(1)-193.666666666667*x(1)*x(1)+49*x(1)*x(1)+(4.08333333333333-4.08333333333333*x(1)*x(1))*(0.0833333333333333-0.0833333333333333*x(1)*x(1))];
cl = 487.333333333333';
cu = 487.333333333333';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'C';

% Starting Guess
x0 = 21';

% Options
opts = struct('probname','himmelbd');
opts.sense = 'min';
