% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 01:46:40
% Model: hs021

% Objective
fun = @(x)0.01*x(1)^2+x(2)^2-100;

% Bounds
lb = [2,-50]';
ub = [50,50]';

% Constraints
nlcon = @(x)[10*x(1)-x(2)];
cl = 10';
cu = Inf';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CC';

% Starting Guess
x0 = [2,NaN]';

% Options
opts = struct('probname','hs021');
opts.sense = 'min';
