% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 01:46:42
% Model: hs055

% Objective
fun = @(x)exp(x(1)*x(4))+x(1)+2*x(2)+4*x(5);

% Bounds
lb = [0,0,0,0,0,0]';
ub = [0.6,1000000,1000000,1,1000000,1000000]';

% Constraints
nlcon = @(x)[x(1)+2*x(2)+5*x(5);
             x(1)+x(2)+x(3);
             x(4)+x(5)+x(6);
             x(1)+x(4);
             x(2)+x(5);
             x(3)+x(6)];
cl = [6,3,2,1,2,2]';
cu = [6,3,2,1,2,2]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','hs055');
opts.sense = 'min';
