% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 01:46:45
% Model: hs086

% Objective
fun = @(x)30*x(1)*x(1)-20*x(2)*x(1)-10*x(3)*x(1)+32*x(4)*x(1)-10*x(5)*x(1)+39*x(2)*x(2)-20*x(1)*x(2)-6*x(3)*x(2)-31*x(4)*x(2)+32*x(5)*x(2)-10*x(1)*x(3)-6*x(2)*x(3)+10*x(3)*x(3)-6*x(4)*x(3)-10*x(5)*x(3)+32*x(1)*x(4)-31*x(2)*x(4)-6*x(3)*x(4)+39*x(4)*x(4)-20*x(5)*x(4)+32*x(2)*x(5)-10*x(1)*x(5)-10*x(3)*x(5)-20*x(4)*x(5)+30*x(5)*x(5)+4*x(1)^3-15*x(1)+8*x(2)^3-27*x(2)+10*x(3)^3-36*x(3)+6*x(4)^3-18*x(4)+2*x(5)^3-12*x(5);

% Bounds
lb = [0,0,0,0,0]';
ub = [Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[-16*x(1)+2*x(2)+x(4);
             -2*x(2)+4*x(4)+2*x(5);
             -3.5*x(1)+2*x(3);
             -2*x(2)-4*x(4)-x(5);
             -9*x(2)-2*x(3)+x(4)-2.8*x(5);
             2*x(1)-4*x(3);
             -x(1)-x(2)-x(3)-x(4)-x(5);
             -x(1)-2*x(2)-3*x(3)-2*x(4)-x(5);
             x(1)+2*x(2)+3*x(3)+4*x(4)+5*x(5);
             x(1)+x(2)+x(3)+x(4)+x(5)];
cl = [-40,-2,-0.25,-4,-4,-1,-40,-60,5,1]';
cu = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','hs086');
opts.sense = 'min';
