% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 01:47:03
% Model: hs108

% Objective
fun = @(x)-0.5*(x(1)*x(4)-x(2)*x(3)+x(3)*x(9)-x(5)*x(9)+x(5)*x(8)-x(6)*x(7));

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,0]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[(-x(3)^2)-x(4)^2;
             (-x(5)^2)-x(6)^2;
             -x(9)^2;
             (-x(1)^2)-(x(2)-x(9))^2;
             (-(x(1)-x(5))^2)-(x(2)-x(6))^2;
             (-(x(1)-x(7))^2)-(x(2)-x(8))^2;
             (-(x(3)-x(7))^2)-(x(4)-x(8))^2;
             (-(x(3)-x(5))^2)-(x(4)-x(6))^2;
             (-x(7)^2)-(x(8)-x(9))^2;
             x(1)*x(4)-x(2)*x(3);
             x(3)*x(9);
             -x(5)*x(9);
             x(5)*x(8)-x(6)*x(7)];
cl = [-1,-1,-1,-1,-1,-1,-1,-1,-1,0,0,0,0]';
cu = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','hs108');
opts.sense = 'min';
