% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 01:47:04
% Model: hs114

% Objective
fun = @(x)-0.063*x(8)*x(11)+5.04*x(5)+0.035*x(6)+10*x(7)+3.36*x(9);

% Bounds
lb = [0,0,0,0,1e-05,1e-05,1e-05,1e-05,1e-05,85,90,3,1.2,145]';
ub = [Inf,Inf,Inf,Inf,2000,16000,120,5000,2000,93,95,12,4,162]';

% Constraints
nlcon = @(x)[x(1)+0.9*x(13)+0.222*x(14);
             x(2)-3*x(11)+0.99*x(14);
             -(0.13167*x(5)*x(12)+1.12*x(5)-0.00667*x(12)^2*x(5))+x(3)+0.99*x(8);
             -(1.098*x(12)-0.038*x(12)^2)+x(4)-0.325*x(10)+0.99*x(11);
             -x(1)+0.211111111111111*x(13);
             -x(2)+0.0201010101010102*x(14);
             -x(3)+0.0201010101010102*x(8);
             -x(4)+0.0201010101010102*x(11);
             -x(5)+1.22*x(8)-x(9);
             98000*x(7)/(x(8)*x(13)+1000*x(7))-x(10);
             (x(6)+x(9))/x(5)-x(12)];
cl = [35.82,-133,0,57.425,0,0,0,0,0,0,0]';
cu = [35.82,-133,0,57.425,Inf,Inf,Inf,Inf,0,0,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,1e-05,1e-05,1e-05,1e-05,1e-05,85,90,3,1.2,145]';

% Options
opts = struct('probname','hs114');
opts.sense = 'min';
