% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 01:47:04
% Model: hs116

% Objective
fun = @(x)x(11)+x(12)+x(13);

% Bounds
lb = [0.1,0.1,0.1,0.0001,0.1,0.1,0.1,0.1,500,0.1,1,0.0001,0.0001]';
ub = [1,1,1,0.1,0.9,0.9,1000,1000,1000,500,150,150,150]';

% Constraints
nlcon = @(x)[-x(2)+x(3);
             -x(1)+x(2);
             -0.002*x(7)+0.002*x(8);
             x(11)+x(12)+x(13);
             1.231059*x(3)*x(10)-1.262626*x(10)+x(13);
             (-0.975*x(2)*x(5))-0.03475*x(2)+x(5)+0.00975*x(2)^2;
             (-0.975*x(3)*x(6))-0.03475*x(3)+x(6)+0.00975*x(3)^2;
             (-0.975*x(1)*x(4))-0.03475*x(1)+x(4)+0.00975*x(1)^2;
             1.231059*x(2)*x(9)-1.262626*x(9)+x(12);
             1.231059*x(1)*x(8)-1.262626*x(8)+x(11);
             x(5)*x(7)-x(1)*x(8)-x(4)*x(7)+x(4)*x(8);
             (-0.002*(x(2)*x(9)+x(5)*x(8)-x(1)*x(8)-x(6)*x(9)))-x(5)-x(6);
             x(2)*x(9)-x(3)*x(10)-x(6)*x(9)-500*x(2)+500*x(6)+x(2)*x(10);
             x(2)-0.002*(x(2)*x(10)-x(3)*x(10));
             x(11)+x(12)+x(13)];
cl = [0,0,-1,50,0,0,0,0,0,0,0,-1,0,0.9,-Inf]';
cu = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,250]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCC';

% Starting Guess
x0 = [0.1,0.1,0.1,0.0001,0.1,0.1,0.1,0.1,500,0.1,1,0.0001,0.0001]';

% Options
opts = struct('probname','hs116');
opts.sense = 'min';
