% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 12:37:29
% Model: lewispol

% Objective
fun = @(x)x(2)^2+x(3)^2+x(4)^2+x(5)^2+x(6)^2+x(7)^2+x(1)^2;

% Bounds
lb = [0,-1,-1,-1,-1,-1,-1]';
ub = [1,1,1,1,1,1,1]';

% Constraints
nlcon = @(x)[x(2)+x(3)+x(4)+x(5)+x(6)+x(7);
             (1+x(2)+x(3)+x(4)+x(5)+x(6)+x(7))^2;
             (6+x(3)+2*x(4)+3*x(5)+4*x(6)+5*x(7))^2;
             (30+4*x(4)+9*x(5)+16*x(6)+25*x(7))^2;
             0.001*(x(2)^3-x(2))-x(1);
             0.001*(x(3)^3-x(3))-x(1);
             0.001*(x(4)^3-x(4))-x(1);
             0.001*(x(5)^3-x(5))-x(1);
             0.001*(x(6)^3-x(6))-x(1);
             0.001*(x(7)^3-x(7))-x(1)];
cl = [-1,0,0,0,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
cu = [-1,0,0,0,0,0,0,0,0,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCC';

% Starting Guess
x0 = [NaN,NaN,1,1,NaN,1,NaN]';

% Options
opts = struct('probname','lewispol');
opts.sense = 'min';
