% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 04:56:51
% Model: lsqfit

% Objective
fun = @(x)0.5*((-0.25+0.1*x(1)+x(2))^2+(-0.3+0.3*x(1)+x(2))^2+(-0.625+0.5*x(1)+x(2))^2+(-0.701+0.7*x(1)+x(2))^2+(-1+0.9*x(1)+x(2))^2);

% Bounds
lb = [0,-Inf]';
ub = [Inf,Inf]';

% Constraints
nlcon = @(x)[x(1)+x(2)];
cl = 0.85';
cu = 0.85';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CC';

% Starting Guess
x0 = [NaN,NaN]';

% Options
opts = struct('probname','lsqfit');
opts.sense = 'min';
