% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 12:40:54
% Model: mconcon

% Objective
fun = @(x)-x(1)-x(2)-x(3)-x(4)-x(5)-x(6)-x(7);

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [914.73,Inf,904.73,Inf,904.73,Inf,914.73,Inf,Inf,Inf,Inf,Inf,Inf,Inf,400]';

% Constraints
nlcon = @(x)[(x(1)^2)^0.5*x(1)-(x(2)^2)^0.5*x(2)-0.597053452*exp(0.8539*log((x(8)^2)^0.5))*x(8);
             (x(3)^2)^0.5*x(3)-(x(4)^2)^0.5*x(4)-0.597053452*exp(0.8539*log((x(9)^2)^0.5))*x(9);
             (x(4)^2)^0.5*x(4)-(x(5)^2)^0.5*x(5)-0.597053452*exp(0.8539*log((x(10)^2)^0.5))*x(10);
             (x(6)^2)^0.5*x(6)-(x(7)^2)^0.5*x(7)-0.597053452*exp(0.8539*log((x(11)^2)^0.5))*x(11);
             x(8)-x(14);
             -x(8)+x(12);
             x(9)-x(12);
             -x(9)+x(10);
             -x(10)-x(13);
             x(11)+x(13);
             -x(11)-x(15)];
cl = [0,0,0,0,0,0,0,-1000,0,0,0]';
cu = [0,0,0,0,0,0,0,-1000,0,0,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCC';

% Starting Guess
x0 = [914.73,965,904.73,965,904.73,965,914.73,100,100,-100,-100,1000,1000,1000,400]';

% Options
opts = struct('probname','mconcon');
opts.sense = 'min';
