% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 04:58:06
% Model: median_exp

% Objective
fun = @(x)(1e-10+x(1))^0.5+(1e-10+x(2))^0.5+(1e-10+x(3))^0.5+(1e-10+x(4))^0.5+(1e-10+x(5))^0.5+(1e-10+x(6))^0.5+(1e-10+x(7))^0.5+(1e-10+x(8))^0.5+(1e-10+x(9))^0.5+(1e-10+x(10))^0.5+(1e-10+x(11))^0.5+(1e-10+x(12))^0.5+(1e-10+x(13))^0.5+(1e-10+x(14))^0.5+(1e-10+x(15))^0.5+(1e-10+x(16))^0.5+(1e-10+x(17))^0.5+(1e-10+x(18))^0.5+(1e-10+x(19))^0.5;

% Bounds
lb = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[exp((-0.171747132+x(20))^2-x(1));
             exp((-0.843266708+x(20))^2-x(2));
             exp((-0.550375356+x(20))^2-x(3));
             exp((-0.301137904+x(20))^2-x(4));
             exp((-0.292212117+x(20))^2-x(5));
             exp((-0.224052867+x(20))^2-x(6));
             exp((-0.349830504+x(20))^2-x(7));
             exp((-0.856270347+x(20))^2-x(8));
             exp((-0.067113723+x(20))^2-x(9));
             exp((-0.500210669+x(20))^2-x(10));
             exp((-0.998117627+x(20))^2-x(11));
             exp((-0.578733378+x(20))^2-x(12));
             exp((-0.991133039+x(20))^2-x(13));
             exp((-0.762250467+x(20))^2-x(14));
             exp((-0.130692483+x(20))^2-x(15));
             exp((-0.639718759+x(20))^2-x(16));
             exp((-0.159517864+x(20))^2-x(17));
             exp((-0.250080533+x(20))^2-x(18));
             exp((-0.668928609+x(20))^2-x(19))];
cl = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
cu = [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','median_exp');
opts.sense = 'min';
