% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 13:54:58
% Model: optmass

% Objective
fun = @(x)0.335*(x(36)^2+x(48)^2)-(x(12)^2+x(24)^2);

% Bounds
lb = [0,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,0,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,0.01,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,0,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [0,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,0,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,0.01,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,0,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[-x(1)+x(2)-0.1*x(25)-0.005*x(49);
             -x(2)+x(3)-0.1*x(26)-0.005*x(50);
             -x(3)+x(4)-0.1*x(27)-0.005*x(51);
             -x(4)+x(5)-0.1*x(28)-0.005*x(52);
             -x(5)+x(6)-0.1*x(29)-0.005*x(53);
             -x(6)+x(7)-0.1*x(30)-0.005*x(54);
             -x(7)+x(8)-0.1*x(31)-0.005*x(55);
             -x(8)+x(9)-0.1*x(32)-0.005*x(56);
             -x(9)+x(10)-0.1*x(33)-0.005*x(57);
             -x(10)+x(11)-0.1*x(34)-0.005*x(58);
             -x(11)+x(12)-0.1*x(35)-0.005*x(59);
             -x(13)+x(14)-0.1*x(37)-0.005*x(60);
             -x(14)+x(15)-0.1*x(38)-0.005*x(61);
             -x(15)+x(16)-0.1*x(39)-0.005*x(62);
             -x(16)+x(17)-0.1*x(40)-0.005*x(63);
             -x(17)+x(18)-0.1*x(41)-0.005*x(64);
             -x(18)+x(19)-0.1*x(42)-0.005*x(65);
             -x(19)+x(20)-0.1*x(43)-0.005*x(66);
             -x(20)+x(21)-0.1*x(44)-0.005*x(67);
             -x(21)+x(22)-0.1*x(45)-0.005*x(68);
             -x(22)+x(23)-0.1*x(46)-0.005*x(69);
             -x(23)+x(24)-0.1*x(47)-0.005*x(70);
             -x(25)+x(26)-0.1*x(49);
             -x(26)+x(27)-0.1*x(50);
             -x(27)+x(28)-0.1*x(51);
             -x(28)+x(29)-0.1*x(52);
             -x(29)+x(30)-0.1*x(53);
             -x(30)+x(31)-0.1*x(54);
             -x(31)+x(32)-0.1*x(55);
             -x(32)+x(33)-0.1*x(56);
             -x(33)+x(34)-0.1*x(57);
             -x(34)+x(35)-0.1*x(58);
             -x(35)+x(36)-0.1*x(59);
             -x(37)+x(38)-0.1*x(60);
             -x(38)+x(39)-0.1*x(61);
             -x(39)+x(40)-0.1*x(62);
             -x(40)+x(41)-0.1*x(63);
             -x(41)+x(42)-0.1*x(64);
             -x(42)+x(43)-0.1*x(65);
             -x(43)+x(44)-0.1*x(66);
             -x(44)+x(45)-0.1*x(67);
             -x(45)+x(46)-0.1*x(68);
             -x(46)+x(47)-0.1*x(69);
             -x(47)+x(48)-0.1*x(70);
             x(49)^2+x(60)^2;
             x(50)^2+x(61)^2;
             x(51)^2+x(62)^2;
             x(52)^2+x(63)^2;
             x(53)^2+x(64)^2;
             x(54)^2+x(65)^2;
             x(55)^2+x(66)^2;
             x(56)^2+x(67)^2;
             x(57)^2+x(68)^2;
             x(58)^2+x(69)^2;
             x(59)^2+x(70)^2];
cl = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
cu = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','optmass');
opts.sense = 'min';
