% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 14:33:19
% Model: pentagon

% Objective
fun = @(x)1/((x(1)-x(2))^2+(x(4)-x(5))^2)^8+1/((x(1)-x(3))^2+(x(4)-x(6))^2)^8+1/((x(3)-x(2))^2+(x(6)-x(5))^2)^8;

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[0.309016994374947*x(1)+0.951056516295154*x(4);
             -0.809016994374947*x(1)+0.587785252292473*x(4);
             -0.809016994374948*x(1)-0.587785252292473*x(4);
             0.309016994374947*x(1)-0.951056516295154*x(4);
             x(1)-2.44921270764475e-16*x(4);
             0.309016994374947*x(2)+0.951056516295154*x(5);
             -0.809016994374947*x(2)+0.587785252292473*x(5);
             -0.809016994374948*x(2)-0.587785252292473*x(5);
             0.309016994374947*x(2)-0.951056516295154*x(5);
             x(2)-2.44921270764475e-16*x(5);
             0.309016994374947*x(3)+0.951056516295154*x(6);
             -0.809016994374947*x(3)+0.587785252292473*x(6);
             -0.809016994374948*x(3)-0.587785252292473*x(6);
             0.309016994374947*x(3)-0.951056516295154*x(6);
             x(3)-2.44921270764475e-16*x(6)];
cl = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
cu = [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCC';

% Starting Guess
x0 = [-1,NaN,1,NaN,-1,1]';

% Options
opts = struct('probname','pentagon');
opts.sense = 'min';
