% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 15:19:29
% Model: recipe

% Objective
fun = @(x)-0;

% Bounds
lb = [-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(1);
             x(2);
             x(3)/(x(2)-x(1))];
cl = [5,0,0]';
cu = [5,0,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [2,5,1]';

% Options
opts = struct('probname','recipe');
opts.sense = 'min';
