% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 05:03:35
% Model: s234

% Objective
fun = @(x)(x(2)-x(1))^4+x(1)-1;

% Bounds
lb = [0.2,0.2]';
ub = [2,2]';

% Constraints
nlcon = @(x)[(-x(1)^2)-x(2)^2];
cl = -1';
cu = Inf';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CC';

% Starting Guess
x0 = [0.2,0.2]';

% Options
opts = struct('probname','s234');
opts.sense = 'min';
