% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 05:03:36
% Model: s253

% Objective
fun = @(x)((-x(1))^2+(-x(2))^2+(-x(3))^2)^0.5+((10-x(1))^2+(-x(2))^2+(-x(3))^2)^0.5+((10-x(1))^2+(10-x(2))^2+(-x(3))^2)^0.5+((-x(1))^2+(10-x(2))^2+(-x(3))^2)^0.5+((-x(1))^2+(-x(2))^2+(10-x(3))^2)^0.5+((10-x(1))^2+(-x(2))^2+(10-x(3))^2)^0.5+((10-x(1))^2+(10-x(2))^2+(10-x(3))^2)^0.5+((-x(1))^2+(10-x(2))^2+(10-x(3))^2)^0.5;

% Bounds
lb = [0,0,0]';
ub = [42,42,42]';

% Constraints
nlcon = @(x)[-3*x(1)-3*x(3)];
cl = -30';
cu = Inf';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [NaN,NaN,NaN]';

% Options
opts = struct('probname','s253');
opts.sense = 'min';
