% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 05:03:37
% Model: s270

% Objective
fun = @(x)x(1)*x(2)*x(3)*x(4)-3*x(1)*x(2)*x(4)-4*x(1)*x(2)*x(3)+12*x(1)*x(2)-x(2)*x(3)*x(4)+3*x(2)*x(4)+4*x(2)*x(3)-12*x(2)-2*x(1)*x(3)*x(4)+6*x(1)*x(4)+8*x(1)*x(3)-24*x(1)+2*x(3)*x(4)-6*x(4)-8*x(3)+1.5*x(5)^4-5.75*x(5)^3+5.25*x(5)^2+24;

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[(-x(1)^2)-x(2)^2-x(3)^2-x(4)^2-x(5)^2;
             x(1);
             x(2);
             x(3);
             x(4)];
cl = [-34,1,2,3,4]';
cu = [Inf,Inf,Inf,Inf,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','s270');
opts.sense = 'min';
