% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 05:03:38
% Model: s279

% Objective
fun = @(x)2.71785714285714*x(1)+1.82896825396825*x(2)+1.42896825396825*x(3)+1.18654401154401*x(4)+1.01987734487734*x(5)+0.896800421800422*x(6)+0.801562326562327*x(7)+0.72537185037185*x(8);

% Bounds
lb = [0,0,0,0,0,0,0,0]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[2.71785714285714*x(1);
             1.82896825396825*x(2);
             1.42896825396825*x(3);
             1.18654401154401*x(4);
             1.01987734487734*x(5);
             0.896800421800422*x(6);
             0.801562326562327*x(7);
             0.72537185037185*x(8)];
cl = [2.71785714285714,1.82896825396825,1.42896825396825,1.18654401154401,1.01987734487734,0.896800421800422,0.801562326562327,0.72537185037185]';
cu = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','s279');
opts.sense = 'min';
