% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 05:03:40
% Model: s326

% Objective
fun = @(x)x(1)^2+x(2)^2-16*x(1)-10*x(2);

% Bounds
lb = [0,0]';
ub = [Inf,Inf]';

% Constraints
nlcon = @(x)[6*x(1)-x(1)^2-4*x(2);
             x(1)*x(2)-3*x(2)-exp((-3)+x(1))];
cl = [-11,-1]';
cu = [Inf,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CC';

% Starting Guess
x0 = [NaN,NaN]';

% Options
opts = struct('probname','s326');
opts.sense = 'min';
