% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 05:03:42
% Model: s359

% Objective
fun = @(x)8720288.849*x(1)-150512.5253*x(2)+156.6950325*x(3)-476470.3222*x(4)-729482.8271*x(5)+121725;

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[2.4*x(1)-x(2);
             -1.2*x(1)+x(2);
             60*x(1)-x(3);
             -20*x(1)+x(3);
             9.3*x(1)-x(4);
             -9*x(1)+x(4);
             7*x(1)-x(5);
             -6.5*x(1)+x(5);
             -145421.402*x(1)+2931.1506*x(2)-40.427932*x(3)+5106.192*x(4)+15711.36*x(5);
             -155011.1084*x(1)+4360.53352*x(2)+12.9492344*x(3)+10236.884*x(4)+13176.786*x(5);
             -326669.5104*x(1)+7390.68412*x(2)-27.8986976*x(3)+16643.076*x(4)+30988.146*x(5);
             145421.402*x(1)-2931.1506*x(2)+40.427932*x(3)-5106.192*x(4)-15711.36*x(5);
             155011.1084*x(1)-4360.53352*x(2)-12.9492344*x(3)-10236.884*x(4)-13176.786*x(5);
             326669.5104*x(1)-7390.68412*x(2)+27.8986976*x(3)-16643.076*x(4)-30988.146*x(5)];
cl = [0,0,0,0,0,0,0,0,0,0,0,-294000,-294000,-294000]';
cu = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','s359');
opts.sense = 'min';
