% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 15:19:42
% Model: s365mod

% Objective
fun = @(x)x(1)*x(3);

% Bounds
lb = [0.5,-Inf,0.5,-Inf,1,-Inf,1,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[-((x(2)*x(2))^0.5+x(3)^2)+x(8);
             -((x(3)*x(3))^0.5+(x(2)-x(1))^2)+x(9);
             (x(4)-x(6))^2+(x(5)-x(7))^2;
             x(3)*x(4)-x(2)*x(5)-x(8);
             x(3)*x(6)-x(2)*x(7)-x(8);
             x(1)*x(3)+(x(2)-x(1))*x(5)-x(3)*x(4)-x(9);
             x(1)*x(3)+(x(2)-x(1))*x(7)-x(3)*x(6)-x(9)];
cl = [0,0,4,0,0,0,0]';
cu = [0,0,Inf,Inf,Inf,Inf,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCC';

% Starting Guess
x0 = [3,0.01,2,-1.5,1.5,5,1,NaN,NaN]';

% Options
opts = struct('probname','s365mod');
opts.sense = 'min';
