% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 05:03:43
% Model: s367

% Objective
fun = @(x)(-x(1)*x(3))-5*x(1)-4*x(3)-5*x(5)/(1+x(5))-8*x(6)/(1+x(6))-10*(exp(-2*x(7))-2*exp(-x(7)))-5*x(2)-6*x(4)-10;

% Bounds
lb = [0,0,0,0,0,0,0]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[-x(1)-x(2)-x(3)-x(4)-x(5)-x(6)-x(7);
             -x(1)-x(2)-x(3)-x(4);
             (-x(6)^2)-x(7)^2-x(1)-x(3)-x(5);
             2*x(4)+x(5)+0.8*x(6)+x(7);
             x(2)^2+x(3)^2+x(5)^2+x(6)^2];
cl = [-10,-5,-5,5,5]';
cu = [Inf,Inf,Inf,5,5]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','s367');
opts.sense = 'min';
