% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 05:03:43
% Model: s372

% Objective
fun = @(x)x(4)^2+x(5)^2+x(6)^2+x(7)^2+x(8)^2+x(9)^2;

% Bounds
lb = [-Inf,-Inf,-Inf,0,0,0,0,0,0]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[exp(-5*x(3))*x(2)+x(1)+x(4);
             exp(-3*x(3))*x(2)+x(1)+x(5);
             exp(-x(3))*x(2)+x(1)+x(6);
             exp(x(3))*x(2)+x(1)+x(7);
             exp(3*x(3))*x(2)+x(1)+x(8);
             exp(5*x(3))*x(2)+x(1)+x(9);
             -exp(-5*x(3))*x(2)-x(1)+x(4);
             -exp(-3*x(3))*x(2)-x(1)+x(5);
             -exp(-x(3))*x(2)-x(1)+x(6);
             -exp(x(3))*x(2)-x(1)+x(7);
             -exp(3*x(3))*x(2)-x(1)+x(8);
             -exp(5*x(3))*x(2)-x(1)+x(9)];
cl = [127,151,379,421,460,426,-127,-151,-379,-421,-460,-426]';
cu = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','s372');
opts.sense = 'min';
