% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 01-Feb-2014 16:48:17
% Model: synthes1

% Objective
fun = @(x)(-18*log(1+x(2)))-19.2*log(1+x(1)-x(2))+10*x(1)-7*x(3)+5*x(4)+6*x(5)+8*x(6)+10;

% Bounds
lb = [0,0,0,0,0,0]';
ub = [2,2,1,1,1,1]';

% Constraints
nlcon = @(x)[-(0.8*log(1+x(2))+0.96*log(1+x(1)-x(2)))+0.8*x(3);
             -(log(1+x(2))+1.2*log(1+x(1)-x(2)))+x(3)+2*x(6);
             x(1)-x(2);
             -x(2)+2*x(4);
             -x(1)+x(2)+2*x(5);
             -x(4)-x(5)];
cl = [-Inf,-Inf,0,0,0,-1]';
cu = [0,2,Inf,Inf,Inf,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','synthes1');
opts.sense = 'min';
