% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:11:31
% Model: aljazzaf

% Objective
fun = @(x)100*(-0.5+x(1))^2+50.005*(1+x(2))^2+0.0100000000000051*(-1+x(3))^2;

% Bounds
lb = [0,0,0]';
ub = [Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[5000.5*x(2)^2+10000*(-1+x(3))^2-x(1)];
cl = -1';
cu = -1';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [NaN,NaN,NaN]';

% Options
opts = struct('probname','aljazzaf');
opts.sense = 'min';
