% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 18:22:38
% Model: biggsc4

% Objective
fun = @(x)(-x(1)*x(3))-x(2)*x(4);

% Bounds
lb = [0,0,0,0]';
ub = [5,5,5,5]';

% Constraints
nlcon = @(x)[x(1)+x(2);
             x(1)+x(2);
             x(1)+x(3);
             x(1)+x(3);
             x(1)+x(4);
             x(1)+x(4);
             x(2)+x(3);
             x(2)+x(3);
             x(2)+x(4);
             x(2)+x(4);
             x(3)+x(4);
             x(3)+x(4);
             x(1)+x(2)+x(3)+x(4)];
cl = [-Inf,2.5,-Inf,2.5,-Inf,2.5,-Inf,2,-Inf,2,-Inf,1.5,5]';
cu = [7.5,Inf,7.5,Inf,7.5,Inf,7,Inf,7,Inf,6.5,Inf,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','biggsc4');
opts.sense = 'min';
