% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 20:48:52
% Model: cantilvr

% Objective
fun = @(x)0.0624*x(1)+0.0624*x(2)+0.0624*x(3)+0.0624*x(4)+0.0624*x(5);

% Bounds
lb = [1e-06,1e-06,1e-06,1e-06,1e-06]';
ub = [Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[61/x(1)^3+37/x(2)^3+19/x(3)^3+7/x(4)^3+1/x(5)^3];
cl = -Inf';
cu = 1';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCC';

% Starting Guess
x0 = [1e-06,1e-06,1e-06,1e-06,1e-06]';

% Options
opts = struct('probname','cantilvr');
opts.sense = 'min';
