% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 00:56:47
% Model: fccu

% Objective
fun = @(x)5*(-31+x(1))^2+(-36+x(2))^2+(-20+x(3))^2+3.00000003*(-3+x(4))^2+3.00000003*(-5+x(5))^2+3.00000003*(-3.5+x(6))^2+(-4.2+x(7))^2+(-0.9+x(8))^2+(-3.9+x(9))^2+(-2.2+x(10))^2+(-22.8+x(11))^2+(-6.8+x(12))^2+(-19+x(13))^2+(-8.5+x(14))^2+3.00000003*(-2.2+x(15))^2+3.00000003*(-2.5+x(16))^2+(-10.8+x(17))^2+3.00000003*(-6.5+x(18))^2+3.00000003*(-6.5+x(19))^2;

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(1)-x(2)+x(9);
             x(2)-x(3)-x(4)-x(5)-x(6)-x(7);
             x(7)-x(8)-x(9);
             x(3)-x(10)-x(11)+x(14);
             x(11)-x(12)-x(13);
             x(13)-x(14)-x(17);
             x(12)-x(15)-x(16);
             x(17)-x(18)-x(19)];
cl = [0,0,0,0,0,0,0,0]';
cu = [0,0,0,0,0,0,0,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','fccu');
opts.sense = 'min';
