% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 00:59:17
% Model: gottfr

% Objective
fun = @(x)-0;

% Bounds
lb = [-Inf,-Inf]';
ub = [Inf,Inf]';

% Constraints
nlcon = @(x)[x(1)-(0.1136*x(1)+0.3408*x(2))*(1-x(1));
             (15*x(1)-7.5*x(2))*(1-x(2))+x(2)];
cl = [0,0]';
cu = [0,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CC';

% Starting Guess
x0 = [NaN,NaN]';

% Options
opts = struct('probname','gottfr');
opts.sense = 'min';
