% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 01:46:42
% Model: hs059

% Objective
fun = @(x)0.0020567*x(1)^3+3.8112*x(1)-1.0345e-5*x(1)^4-0.030234*x(1)*x(2)+6.8306*x(2)+0.00128134*x(1)^2*x(2)+2.266e-7*x(1)^4*x(2)-0.25645*x(2)^2+0.0034604*x(2)^3-1.3514e-5*x(2)^4+28.106/(1+x(2))+5.2375e-6*x(1)^2*x(2)^2+6.3e-8*x(1)^3*x(2)^2-7e-10*x(1)^3*x(2)^3-0.0003405*x(2)^2*x(1)+1.6638e-6*x(2)^3*x(1)+2.8673*exp(0.0005*x(1)*x(2))-3.5256e-5*x(1)^3*x(2)-0.12694*x(1)^2-75.196;

% Bounds
lb = [0,0]';
ub = [75,65]';

% Constraints
nlcon = @(x)[x(1)*x(2);
             -0.008*x(1)^2+x(2);
             (-50+x(2))^2-5*x(1)];
cl = [700,0,-275]';
cu = [Inf,Inf,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CC';

% Starting Guess
x0 = [NaN,NaN]';

% Options
opts = struct('probname','hs059');
opts.sense = 'min';
