% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 01:46:44
% Model: hs071

% Objective
fun = @(x)x(1)*x(4)*(x(1)+x(2)+x(3))+x(3);

% Bounds
lb = [1,1,1,1]';
ub = [5,5,5,5]';

% Constraints
nlcon = @(x)[x(1)*x(2)*x(3)*x(4);
             x(1)^2+x(2)^2+x(3)^2+x(4)^2];
cl = [25,40]';
cu = [Inf,40]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCC';

% Starting Guess
x0 = [1,1,1,1]';

% Options
opts = struct('probname','hs071');
opts.sense = 'min';
