% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 01:46:49
% Model: hs100lnp

% Objective
fun = @(x)(-10+x(1))^2+5*(-12+x(2))^2+x(3)^4+3*(-11+x(4))^2+10*x(5)^6+7*x(6)^2+x(7)^4-4*x(6)*x(7)-10*x(6)-8*x(7);

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[2*x(1)^2+3*x(2)^4+4*x(4)^2+x(3)+5*x(5);
             (-4*x(1)^2)-x(2)^2+3*x(1)*x(2)-2*x(3)^2-5*x(6)+11*x(7)];
cl = [127,0]';
cu = [127,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','hs100lnp');
opts.sense = 'min';
