% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 04:56:54
% Model: makela3

% Objective
fun = @(x)x(1);

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(2)^2-x(1);
             x(3)^2-x(1);
             x(4)^2-x(1);
             x(5)^2-x(1);
             x(6)^2-x(1);
             x(7)^2-x(1);
             x(8)^2-x(1);
             x(9)^2-x(1);
             x(10)^2-x(1);
             x(11)^2-x(1);
             x(12)^2-x(1);
             x(13)^2-x(1);
             x(14)^2-x(1);
             x(15)^2-x(1);
             x(16)^2-x(1);
             x(17)^2-x(1);
             x(18)^2-x(1);
             x(19)^2-x(1);
             x(20)^2-x(1);
             x(21)^2-x(1)];
cl = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
cu = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','makela3');
opts.sense = 'min';
