% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 12:40:50
% Model: masa

% Objective
fun = @(x)x(1)+x(4);

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,1e-08,1e-08,1e-08,1e-07]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[2*x(2);
             -x(1)+x(5);
             -x(3)+x(6);
             x(6)*x(8)-x(4)+x(7);
             x(5)*x(8)-x(2)];
cl = [2,0,0,0,0]';
cu = [2,0,0,0,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCC';

% Starting Guess
x0 = [1,1,NaN,1,1e-08,1e-08,1e-08,1e-07]';

% Options
opts = struct('probname','masa');
opts.sense = 'min';
