% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 04:57:52
% Model: matrix2

% Objective
fun = @(x)(x(1)-x(4))^2+2*(x(2)-x(5))^2+(x(3)-x(6))^2;

% Bounds
lb = [0,-Inf,0,-Inf,-Inf,0]';
ub = [Inf,Inf,Inf,0,Inf,Inf]';

% Constraints
nlcon = @(x)[x(1)*x(3)-x(2)^2;
             x(4)*x(6)-x(5)^2];
cl = [0,-Inf]';
cu = [Inf,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','matrix2');
opts.sense = 'min';
