% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 12:41:23
% Model: mistake

% Objective
fun = @(x)0.5*x(2)*x(3)-0.5*x(1)*x(4)-0.5*x(3)*x(9)+0.5*x(5)*x(9)-0.5*x(5)*x(8)+0.5*x(6)*x(7);

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,0]';
ub = [Inf,Inf,Inf,Inf,Inf,0.6,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[-(x(3)*x(3)+x(4)*x(4));
             -(x(5)*x(5)+x(6)*x(6));
             -x(9)*x(9);
             -(x(1)*x(1)+(x(2)-x(9))*(x(2)-x(9)));
             -((x(1)-x(5))*(x(1)-x(5))+(x(2)-x(6))*(x(2)-x(6)));
             -((x(1)-x(7))*(x(1)-x(7))+(x(2)-x(8))*(x(2)-x(8)));
             -((x(3)-x(5))*(x(3)-x(5))+(x(4)-x(6))*(x(4)-x(6)));
             -((x(3)-x(7))*(x(3)-x(7))+(x(4)-x(8))*(x(4)-x(8)));
             -(x(7)*x(7)+x(8)*x(9));
             -x(8)*x(9);
             -(x(5)*x(8)-x(6)*x(7));
             -(x(1)*x(4)-x(2)*x(3));
             x(5)*x(9)];
cl = [-1,-1,-1,-1,-1,-1,-1,-1,-1,-Inf,-Inf,-Inf,0]';
cu = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,0,0,0,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCC';

% Starting Guess
x0 = [1,1,1,1,1,0.6,1,1,1]';

% Options
opts = struct('probname','mistake');
opts.sense = 'min';
