% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 13:52:25
% Model: nuffield_continuum

% Objective
fun = @(x)-(1.5*(1-x(2))^2-1.25*((1-x(2))^2+(1-x(1))^2)-3*x(1)-3*(0.0416666666666667*x(1)^3+(0.25-0.25*(1-x(2))^2)*(1-x(1))+0.5*(1-x(2))^2*(1-0.5*x(1)-0.5*x(2))-0.166666666666667*(1-x(2))^3))-4.5;

% Bounds
lb = [0,0]';
ub = [1,1]';

% Constraints
nlcon = @(x)[x(1)-x(2)];
cl = -Inf';
cu = 0';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CC';

% Starting Guess
x0 = [0.03,0.1]';

% Options
opts = struct('probname','nuffield_continuum');
opts.sense = 'min';
