% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 05:03:33
% Model: s203

% Objective
fun = @(x)x(1)^2+x(2)^2+x(3)^2;

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[(1-x(5))*x(4)+x(1);
             (1-x(5)^2)*x(4)+x(2);
             (1-x(5)^3)*x(4)+x(3)];
cl = [1.5,2.25,2.625]';
cu = [1.5,2.25,2.625]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','s203');
opts.sense = 'min';
