% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 05:03:36
% Model: s262

% Objective
fun = @(x)-0.5*x(1)-x(2)-0.5*x(3)-x(4);

% Bounds
lb = [0,0,0,0]';
ub = [Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[-x(1)-x(2)-x(3)-x(4);
             -0.2*x(1)-0.5*x(2)-x(3)-2*x(4);
             -2*x(1)-x(2)-0.5*x(3)-0.2*x(4);
             x(1)+x(2)+x(3)-2*x(4)];
cl = [-10,-10,-10,6]';
cu = [Inf,Inf,Inf,6]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','s262');
opts.sense = 'min';
