% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 05:03:38
% Model: s280

% Objective
fun = @(x)2.92896825396825*x(1)+2.01987734487735*x(2)+1.60321067821068*x(3)+1.34680042180042*x(4)+1.16822899322899*x(5)+1.03489565989566*x(6)+0.930728993228993*x(7)+0.846695379783615*x(8)+0.777250935339171*x(9)+0.718771403175428*x(10);

% Bounds
lb = [0,0,0,0,0,0,0,0,0,0]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[2.92896825396825*x(1);
             2.01987734487735*x(2);
             1.60321067821068*x(3);
             1.34680042180042*x(4);
             1.16822899322899*x(5);
             1.03489565989566*x(6);
             0.930728993228993*x(7);
             0.846695379783615*x(8);
             0.777250935339171*x(9);
             0.718771403175428*x(10)];
cl = [2.92896825396825,2.01987734487735,1.60321067821068,1.34680042180042,1.16822899322899,1.03489565989566,0.930728993228993,0.846695379783615,0.777250935339171,0.718771403175428]';
cu = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','s280');
opts.sense = 'min';
