% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 05:03:39
% Model: s314

% Objective
fun = @(x)(-2+x(3))^2+(-1+x(4))^2+0.04/(0.0001+x(1))+5*x(2)^2;

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf]';
ub = [-0.5,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[-(-0.25*x(3)^2-x(4)^2)+x(1);
             x(2)-x(3)+2*x(4)];
cl = [1,1]';
cu = [1,1]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCC';

% Starting Guess
x0 = [-0.5,NaN,NaN,NaN]';

% Options
opts = struct('probname','s314');
opts.sense = 'min';
