% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 05:03:41
% Model: s335

% Objective
fun = @(x)-0.001*x(1)-x(2);

% Bounds
lb = [-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[1000*x(1)^2+100*x(2)^2-x(3);
             100*x(1)^2+400*x(2)^2+x(3)];
cl = [0,0.01]';
cu = [0,0.01]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [NaN,NaN,NaN]';

% Options
opts = struct('probname','s335');
opts.sense = 'min';
