% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 05:03:41
% Model: s337

% Objective
fun = @(x)9*x(1)^2+x(2)^2+9*x(3)^2;

% Bounds
lb = [-Inf,1,-Inf]';
ub = [Inf,Inf,1]';

% Constraints
nlcon = @(x)[x(1)*x(2)];
cl = 1';
cu = Inf';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [NaN,1,NaN]';

% Options
opts = struct('probname','s337');
opts.sense = 'min';
