% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 05:03:41
% Model: s339

% Objective
fun = @(x)0.2/(x(1)*x(2)*x(3))+4/x(1)+3/x(3);

% Bounds
lb = [1e-05,1e-05,1e-05]';
ub = [Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[(-2*x(1)*x(3))-x(1)*x(2)];
cl = -10';
cu = Inf';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [1e-05,1e-05,1e-05]';

% Options
opts = struct('probname','s339');
opts.sense = 'min';
