% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 05:03:46
% Model: s381

% Objective
fun = @(x)0.8*x(1)+1.1*x(2)+0.85*x(3)+3.45*x(4)+2*x(5)+2.1*x(6)+3*x(7)+0.8*x(8)+0.45*x(9)+0.72*x(10)+1.8*x(11)+3*x(12)+0.6*x(13);

% Bounds
lb = [0,0,0,0,0,0,0,0,0,0,0,0,0]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[11.6*x(1)+13.7*x(2)+9.5*x(3)+48.5*x(4)+31.9*x(5)+51.1*x(6)+65.5*x(7)+21.8*x(11)+46.9*x(12);
             0.05*x(1)+0.07*x(2)+0.33*x(4)+1.27*x(6)+1.27*x(7)+23.35*x(8)+35.84*x(9)+0.81*x(10)+1.79*x(11)+7.34*x(12);
             0.35*x(1)+0.37*x(2)+0.1*x(3)+0.62*x(4)+1.03*x(6)+1.69*x(7)+18.21*x(8)+0.01*x(9)+0.08*x(10)+0.31*x(11)+1.59*x(12)+22.45*x(13);
             x(1)+x(2)+x(3)+x(4)+x(5)+x(6)+x(7)+x(8)+x(9)+x(10)+x(11)+x(12)+x(13)];
cl = [18,1,0.9,1]';
cu = [Inf,Inf,Inf,1]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','s381');
opts.sense = 'min';
