% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 01-Feb-2014 15:52:05
% Model: stancmin

% Objective
fun = @(x)-(-11+3*x(1)+6*x(2)+2*x(3))/(1+x(1)+4*x(2)+x(3));

% Bounds
lb = [0,0,0]';
ub = [Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[3*x(1)+4*x(2)+x(3);
             x(1)+4*x(2)+x(3)];
cl = [-Inf,-Inf]';
cu = [2,1]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [50,50,50]';

% Options
opts = struct('probname','stancmin');
opts.sense = 'min';
