% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 01-Feb-2014 23:37:25
% Model: weeds

% Objective
fun = @(x)(5.308-x(1)/(1+x(4)))^2+(7.24-x(1)/(1+x(5)))^2+(9.638-x(1)/(1+x(6)))^2+(12.866-x(1)/(1+x(7)))^2+(17.069-x(1)/(1+x(8)))^2+(23.192-x(1)/(1+x(9)))^2+(31.443-x(1)/(1+x(10)))^2+(38.558-x(1)/(1+x(11)))^2+(50.156-x(1)/(1+x(12)))^2+(62.948-x(1)/(1+x(13)))^2+(75.995-x(1)/(1+x(14)))^2+(91.972-x(1)/(1+x(15)))^2;

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,3,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[-exp((-x(2))-x(3))+x(4);
             -exp((-x(2))-2*x(3))+x(5);
             -exp((-x(2))-3*x(3))+x(6);
             -exp((-x(2))-4*x(3))+x(7);
             -exp((-x(2))-5*x(3))+x(8);
             -exp((-x(2))-6*x(3))+x(9);
             -exp((-x(2))-7*x(3))+x(10);
             -exp((-x(2))-8*x(3))+x(11);
             -exp((-x(2))-9*x(3))+x(12);
             -exp((-x(2))-10*x(3))+x(13);
             -exp((-x(2))-11*x(3))+x(14);
             -exp((-x(2))-12*x(3))+x(15)];
cl = [0,0,0,0,0,0,0,0,0,0,0,0]';
cu = [0,0,0,0,0,0,0,0,0,0,0,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCC';

% Starting Guess
x0 = [1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','weeds');
opts.sense = 'min';
