% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 01-Feb-2014 23:37:27
% Model: womflet

% Objective
fun = @(x)x(3);

% Bounds
lb = [-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[(-x(2)^2)-5*x(1)/(0.1+x(1))-0.5*x(1)+x(3);
             (-x(2)^2)-5*x(1)/(0.1+x(1))+0.5*x(1)+x(3);
             x(2)^2+5*x(1)/(0.1+x(1))+0.5*x(1)+x(3)];
cl = [0,0,0]';
cu = [Inf,Inf,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [3,1,7.5]';

% Options
opts = struct('probname','womflet');
opts.sense = 'min';
