% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 13:52:45
% Model: chem

% Objective
fun = @(x)(-6.05576803624071+log(x(1)/x(11)))*x(1)+(-17.1307680362407+log(x(2)/x(11)))*x(2)+(-34.0207680362407+log(x(3)/x(11)))*x(3)+(-5.88076803624071+log(x(4)/x(11)))*x(4)+(-24.6877680362407+log(x(5)/x(11)))*x(5)+(-14.9527680362407+log(x(6)/x(11)))*x(6)+(-24.0667680362407+log(x(7)/x(11)))*x(7)+(-10.6747680362407+log(x(8)/x(11)))*x(8)+(-26.6287680362407+log(x(9)/x(11)))*x(9)+(-22.1447680362407+log(x(10)/x(11)))*x(10);

% Bounds
lb = [0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.01]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(1)+2*x(2)+2*x(3)+x(6)+x(10);
             x(4)+2*x(5)+x(6)+x(7);
             x(3)+x(7)+x(8)+2*x(9)+x(10);
             -x(1)-x(2)-x(3)-x(4)-x(5)-x(6)-x(7)-x(8)-x(9)-x(10)+x(11)];
cl = [2,1,1,0]';
cu = [2,1,1,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCC';

% Starting Guess
x0 = [0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.01]';

% Options
opts = struct('probname','chem');
opts.sense = 'min';
