% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 13:53:51
% Model: ex14_1_8

% Objective
fun = @(x)x(3);

% Bounds
lb = [0,0,-Inf]';
ub = [1,1,Inf]';

% Constraints
nlcon = @(x)[exp(10*x(1)/(1+0.01*x(1)))*(0.0476666666666666-0.0649999999999999*x(1))-x(1)-x(3);
             x(1)-exp(10*x(1)/(1+0.01*x(1)))*(0.0476666666666666-0.0649999999999999*x(1))-x(3);
             exp(10*x(2)/(1+0.01*x(2)))*(0.143-0.13*x(1)-0.195*x(2))+x(1)-3*x(2)-x(3);
             (-exp(10*x(2)/(1+0.01*x(2)))*(0.143-0.13*x(1)-0.195*x(2)))-x(1)+3*x(2)-x(3)];
cl = [-Inf,-Inf,-Inf,-Inf]';
cu = [0,0,0,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [NaN,NaN,NaN]';

% Options
opts = struct('probname','ex14_1_8');
opts.sense = 'min';
