% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 13:53:53
% Model: ex2_1_6

% Objective
fun = @(x)48*x(1)-0.5*(100*x(1)*x(1)+100*x(2)*x(2)+100*x(3)*x(3)+100*x(4)*x(4)+100*x(5)*x(5)+100*x(6)*x(6)+100*x(7)*x(7)+100*x(8)*x(8)+100*x(9)*x(9)+100*x(10)*x(10))+42*x(2)+48*x(3)+45*x(4)+44*x(5)+41*x(6)+47*x(7)+42*x(8)+45*x(9)+46*x(10);

% Bounds
lb = [0,0,0,0,0,0,0,0,0,0]';
ub = [1,1,1,1,1,1,1,1,1,1]';

% Constraints
nlcon = @(x)[-2*x(1)-6*x(2)-x(3)-3*x(5)-3*x(6)-2*x(7)-6*x(8)-2*x(9)-2*x(10);
             6*x(1)-5*x(2)+8*x(3)-3*x(4)+x(6)+3*x(7)+8*x(8)+9*x(9)-3*x(10);
             -5*x(1)+6*x(2)+5*x(3)+3*x(4)+8*x(5)-8*x(6)+9*x(7)+2*x(8)-9*x(10);
             9*x(1)+5*x(2)-9*x(4)+x(5)-8*x(6)+3*x(7)-9*x(8)-9*x(9)-3*x(10);
             -8*x(1)+7*x(2)-4*x(3)-5*x(4)-9*x(5)+x(6)-7*x(7)-x(8)+3*x(9)-2*x(10)];
cl = [-Inf,-Inf,-Inf,-Inf,-Inf]';
cu = [-4,22,-6,-23,-12]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCC';

% Starting Guess
x0 = [1,NaN,NaN,1,1,1,NaN,1,1,1]';

% Options
opts = struct('probname','ex2_1_6');
opts.sense = 'min';
