% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 13:53:53
% Model: ex2_1_5

% Objective
fun = @(x)(-0.5*(10*x(1)*x(1)+10*x(2)*x(2)+10*x(3)*x(3)+10*x(4)*x(4)+10*x(5)*x(5)+10*x(6)*x(6)+10*x(7)*x(7)))-20*x(1)-80*x(2)-20*x(3)-50*x(4)-60*x(5)-90*x(6)+10*x(8)+10*x(9)+10*x(10);

% Bounds
lb = [0,0,0,0,0,0,0,0,0,0]';
ub = [1,1,1,1,1,1,1,1,1,1]';

% Constraints
nlcon = @(x)[-2*x(1)-6*x(2)-x(3)-3*x(5)-3*x(6)-2*x(7)-6*x(8)-2*x(9)-2*x(10);
             6*x(1)-5*x(2)+8*x(3)-3*x(4)+x(6)+3*x(7)+8*x(8)+9*x(9)-3*x(10);
             -5*x(1)+6*x(2)+5*x(3)+3*x(4)+8*x(5)-8*x(6)+9*x(7)+2*x(8)-9*x(10);
             9*x(1)+5*x(2)-9*x(4)+x(5)-8*x(6)+3*x(7)-9*x(8)-9*x(9)-3*x(10);
             -8*x(1)+7*x(2)-4*x(3)-5*x(4)-9*x(5)+x(6)-7*x(7)-x(8)+3*x(9)-2*x(10);
             -7*x(1)-5*x(2)-2*x(3)-6*x(5)-6*x(6)-7*x(7)-6*x(8)+7*x(9)+7*x(10);
             x(1)-3*x(2)-3*x(3)-4*x(4)-x(5)-4*x(7)+x(8)+6*x(9);
             x(1)-2*x(2)+6*x(3)+9*x(4)-7*x(6)+9*x(7)-9*x(8)-6*x(9)+4*x(10);
             -4*x(1)+6*x(2)+7*x(3)+2*x(4)+2*x(5)+6*x(7)+6*x(8)-7*x(9)+4*x(10);
             x(1)+x(2)+x(3)+x(4)+x(5)+x(6)+x(7)+x(8)+x(9)+x(10);
             -x(1)-x(2)-x(3)-x(4)-x(5)-x(6)-x(7)-x(8)-x(9)-x(10)];
cl = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
cu = [-4,22,-6,-23,-12,-3,1,12,15,9,-1]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCC';

% Starting Guess
x0 = [1,0.90755,NaN,1,0.71509,1,NaN,0.91698,1,1]';

% Options
opts = struct('probname','ex2_1_5');
opts.sense = 'min';
