% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 13:53:53
% Model: ex3_1_4

% Objective
fun = @(x)-2*x(1)+x(2)-x(3);

% Bounds
lb = [0,0,0]';
ub = [2,Inf,3]';

% Constraints
nlcon = @(x)[x(1)*(4*x(1)-2*x(2)+2*x(3))+x(2)*(2*x(2)-2*x(1)-x(3))+x(3)*(2*x(1)-x(2)+2*x(3))-20*x(1)+9*x(2)-13*x(3);
             x(1)+x(2)+x(3);
             3*x(2)+x(3)];
cl = [-24,-Inf,-Inf]';
cu = [Inf,4,6]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [0.5,NaN,3]';

% Options
opts = struct('probname','ex3_1_4');
opts.sense = 'min';
