% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 13:53:54
% Model: ex5_4_3

% Objective
fun = @(x)1300*(1000/(0.0333333333333333*x(1)*x(2)+0.166666666666667*x(1)+0.166666666666667*x(2)))^0.6+1300*(600/(0.0333333333333333*x(3)*x(4)+0.166666666666667*x(3)+0.166666666666667*x(4)))^0.6;

% Bounds
lb = [10,10,10,10,0,0,0,0,0,0,0,0,150,150,150,150]';
ub = [350,350,200,200,10,10,10,10,10,10,10,10,310,310,310,310]';

% Constraints
nlcon = @(x)[x(5)+x(9);
             x(5)-x(6)+x(11);
             x(7)+x(9)-x(10);
             -x(6)+x(7)+x(8);
             -x(10)+x(11)+x(12);
             x(16)*x(11)-x(13)*x(6)+150*x(5);
             x(15)*x(7)-x(14)*x(10)+150*x(9);
             x(6)*x(15)-x(6)*x(13);
             x(10)*x(16)-x(10)*x(14);
             x(1)+x(15);
             x(2)+x(13);
             x(3)+x(16);
             x(4)+x(14)];
cl = [10,0,0,0,0,0,0,1000,600,500,250,350,200]';
cu = [10,0,0,0,0,0,0,1000,600,500,250,350,200]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCCC';

% Starting Guess
x0 = [10,10,10,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,150,150,150,150]';

% Options
opts = struct('probname','ex5_4_3');
opts.sense = 'min';
