% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 13:53:54
% Model: ex6_1_4

% Objective
fun = @(x)(0.28809+log(x(1)))*x(1)+(-0.29158+log(x(2)))*x(2)+(0.59336+log(x(3)))*x(3)+x(1)*(1.44805026165593*x(5)+0.989428667054834*x(6))+x(2)*(1.12676386427658*x(4)+1.00363012835441*x(6))+x(3)*(0.0347225450624344*x(4)+0.82681418300153*x(5));

% Bounds
lb = [1e-06,1e-06,1e-06,0,0,0]';
ub = [1,1,1,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(4)*(x(1)+0.145002897355373*x(2)+0.989528214945409*x(3))-x(1);
             x(5)*(0.293701311601799*x(1)+x(2)+0.646291923054068*x(3))-x(2);
             x(6)*(0.619143628558899*x(1)+0.239837817616513*x(2)+x(3))-x(3);
             x(1)+x(2)+x(3)];
cl = [0,0,0,1]';
cu = [0,0,0,1]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCC';

% Starting Guess
x0 = [7e-05,0.99686,0.00307,0.000474076675116379,0.997993046160137,0.0126755759820888]';

% Options
opts = struct('probname','ex6_1_4');
opts.sense = 'min';
