% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 13:53:55
% Model: ex7_3_5

% Objective
fun = @(x)x(4);

% Bounds
lb = [-Inf,-Inf,0,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,10,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(3)^8*x(13)-x(3)^6*x(11)+x(3)^4*x(9)-x(3)^2*x(7)+x(5);
             x(3)^6*x(12)-x(3)^4*x(10)+x(3)^2*x(8)-x(6);
             -x(1)-0.145*x(4);
             x(1)-0.145*x(4);
             -x(2)-0.15*x(4);
             x(2)-0.15*x(4);
             -4.53*x(1)^2+x(5);
             -(5.28*x(1)^2+0.364*x(1))+x(6);
             -(5.72*x(1)^2*x(2)+1.13*x(1)^2+0.425*x(1))+x(7);
             -(6.93*x(1)^2*x(2)+0.0911*x(1))+x(8);
             -(1.45*x(1)^2*x(2)+0.168*x(1)*x(2))+x(9);
             -(1.56*x(1)^2*x(2)^2+0.00084*x(1)^2*x(2)+0.0135*x(1)*x(2))+x(10);
             -(0.125*x(1)^2*x(2)^2+1.68e-5*x(1)^2*x(2)+0.000539*x(1)*x(2))+x(11);
             -(0.005*x(1)^2*x(2)^2+1.08e-5*x(1)*x(2))+x(12);
             -0.0001*x(1)^2*x(2)^2+x(13)];
cl = [0,0,-Inf,-Inf,-Inf,-Inf,0,0,0,0.00422,0.000338,1.35e-05,2.7e-07,0,0]';
cu = [0,0,-0.175,0.175,-0.2,0.2,0,0,0,0.00422,0.000338,1.35e-05,2.7e-07,0,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','ex7_3_5');
opts.sense = 'min';
