% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 13:53:55
% Model: ex8_1_7

% Objective
fun = @(x)(-1+x(1))^2+(x(1)-x(2))^2+(x(2)-x(3))^3+(x(3)-x(4))^4+(x(4)-x(5))^4;

% Bounds
lb = [-5,-5,-5,-5,-5]';
ub = [5,5,5,5,5]';

% Constraints
nlcon = @(x)[x(2)^2+x(3)^3+x(1);
             (-x(3)^3)-x(2)^2-x(1);
             -x(3)^2+x(2)+x(4);
             x(3)^2-x(2)-x(4);
             0.5*x(1)*x(5)+0.5*x(1)*x(5)];
cl = [-Inf,-Inf,-Inf,-Inf,2]';
cu = [6.24264068711929,-6.24264068711929,0.82842712474619,-0.82842712474619,2]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','ex8_1_7');
opts.sense = 'min';
