% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 14:33:58
% Model: ex9_1_1

% Objective
fun = @(x)-3*x(1)+2*x(2)-x(3);

% Bounds
lb = [-Inf,-Inf,0,0,0,0,0,0,0,0,0,0,0]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(1)+4*x(2)-2*x(3)+x(4);
             3*x(1)-2*x(2)+8*x(3)+x(5);
             x(1)-3*x(2)-2*x(3)+x(6);
             -x(1)+x(7);
             x(1)+x(8);
             x(9)*x(4);
             x(10)*x(5);
             x(11)*x(6);
             x(12)*x(7);
             x(13)*x(8);
             x(9)+3*x(10)+x(11)-x(12)+x(13);
             2*x(10)-3*x(11)];
cl = [16,48,-12,0,4,0,0,0,0,0,1,0]';
cu = [16,48,-12,0,4,0,0,0,0,0,1,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','ex9_1_1');
opts.sense = 'min';
