% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 15:30:04
% Model: house

% Objective
fun = @(x)-x(7)-x(8);

% Bounds
lb = [-Inf,-Inf,-Inf,40,-Inf,56,-Inf,-Inf]';
ub = [Inf,Inf,Inf,68,Inf,100,3000,Inf]';

% Constraints
nlcon = @(x)[-(x(1)*x(2)+x(5)*x(4))+x(7);
             -x(1)*x(3)+x(8);
             -x(2)-x(5)+x(6);
             x(1)-0.333333333333333*x(4);
             x(1)-0.5*x(4);
             x(2)*(x(4)-x(1));
             -0.5*x(2)+x(3)-x(5);
             -0.5*x(2)+x(5)];
cl = [0,0,0,0,-Inf,1500,0,0]';
cu = [0,0,0,Inf,0,Inf,0,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCC';

% Starting Guess
x0 = [30,NaN,NaN,68,NaN,56,NaN,NaN]';

% Options
opts = struct('probname','house');
opts.sense = 'min';
