% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:02:57
% Model: sambal

% Objective
fun = @(x)0.0666666666666667*(15-x(1))^2+0.333333333333333*(3-x(2))^2+0.00769230769230769*(130-x(3))^2+0.0125*(80-x(4))^2+0.0666666666666667*(15-x(7))^2+0.00769230769230769*(130-x(8))^2+0.05*(20-x(9))^2+0.04*(25-x(10))^2+0.025*(40-x(11))^2+0.0181818181818182*(55-x(12))^2+0.00454545454545455*(220-x(13))^2+0.00526315789473684*(190-x(16))^2+0.00952380952380952*(105-x(17))^2;

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[-x(1)-x(2)-x(3)-x(4)+x(13);
             -x(5)+x(14);
             -x(6)+x(15);
             -x(7)-x(8)-x(9)+x(16);
             -x(10)-x(11)-x(12)+x(17);
             -x(5)-x(6)+x(13);
             -x(1)-x(7)-x(10)+x(14);
             -x(2)-x(8)-x(11)+x(15);
             -x(3)-x(12)+x(16);
             -x(4)-x(9)+x(17)];
cl = [0,0,0,0,0,0,0,0,0,0]';
cu = [0,0,0,0,0,0,0,0,0,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCCCC';

% Starting Guess
x0 = [15,3,130,80,NaN,NaN,15,130,20,25,40,55,220,NaN,NaN,190,105]';

% Options
opts = struct('probname','sambal');
opts.sense = 'min';
