% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:02:59
% Model: st_e42

% Objective
fun = @(x)x(1)+x(2);

% Bounds
lb = [0,0,0,0,-1,-1,0]';
ub = [Inf,Inf,1,1,1,1,3]';

% Constraints
nlcon = @(x)[51.5712*x(3)*x(5)+20.7324*x(3)-25.7856*x(5)+14.9251*x(3)*x(7)-22.2988*x(7)-10.1409*x(6)*x(7)+42.3401*x(6)-x(1)+x(2)-6.6425*x(4);
             x(3)];
cl = [-72.82,1]';
cu = [-72.82,1]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','st_e42');
opts.sense = 'min';
