% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:02:58
% Model: st_e06

% Objective
fun = @(x)-0;

% Bounds
lb = [0,0,0]';
ub = [12.5,37.5,50]';

% Constraints
nlcon = @(x)[x(3)*x(3)-0.000169*x(2)^3*x(1);
             x(1)+x(2)+x(3);
             -3*x(1)+x(2)];
cl = [0,50,0]';
cu = [0,50,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [NaN,NaN,NaN]';

% Options
opts = struct('probname','st_e06');
opts.sense = 'min';
