% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:02:58
% Model: st_e03

% Objective
fun = @(x)-0.063*x(4)*x(7)+5.04*x(1)+0.035*x(2)+10*x(3)+3.36*x(5);

% Bounds
lb = [1,1,0,1,0,85,90,3,1.2,145]';
ub = [2000,16000,120,5000,2000,93,95,12,4,162]';

% Constraints
nlcon = @(x)[x(1)-1.22*x(4)+x(5);
             x(9)+0.222*x(10);
             3*x(7)-x(10);
             0.038*x(8)^2-1.098*x(8)-0.325*x(6)+x(7);
             x(4)*x(9)*x(6)+1000*x(3)*x(6)-98000*x(3);
             -x(1)*x(8)+x(2)+x(5);
             0.13167*x(8)*x(1)+1.12*x(1)-0.00667*x(8)^2*x(1)-x(4)];
cl = [0,35.82,133,57.425,0,0,0]';
cu = [0,35.82,133,57.425,0,0,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCC';

% Starting Guess
x0 = [1,1,NaN,1,NaN,85,90,3,1.2,145]';

% Options
opts = struct('probname','st_e03');
opts.sense = 'min';
