% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:03:00
% Model: st_fp8

% Objective
fun = @(x)300*x(1)-7*x(1)^2-4*x(2)^2+270*x(2)-6*x(3)^2+460*x(3)-8*x(4)^2+800*x(4)-12*x(5)^2+740*x(5)-9*x(6)^2+600*x(6)-14*x(7)^2+540*x(7)-7*x(8)^2+380*x(8)-13*x(9)^2+300*x(9)-12*x(10)^2+490*x(10)-8*x(11)^2+380*x(11)-4*x(12)^2+760*x(12)-7*x(13)^2+430*x(13)-9*x(14)^2+250*x(14)-16*x(15)^2+390*x(15)-8*x(16)^2+600*x(16)-4*x(17)^2+210*x(17)-10*x(18)^2+830*x(18)-21*x(19)^2+470*x(19)-13*x(20)^2+680*x(20)-17*x(21)^2+360*x(21)-9*x(22)^2+290*x(22)-8*x(23)^2+400*x(23)-4*x(24)^2+310*x(24);

% Bounds
lb = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[-x(1)-x(5)-x(9)-x(13)-x(17)-x(21);
             x(1)+x(5)+x(9)+x(13)+x(17)+x(21);
             -x(2)-x(6)-x(10)-x(14)-x(18)-x(22);
             x(2)+x(6)+x(10)+x(14)+x(18)+x(22);
             -x(3)-x(7)-x(11)-x(15)-x(19)-x(23);
             x(3)+x(7)+x(11)+x(15)+x(19)+x(23);
             -x(4)-x(8)-x(12)-x(16)-x(20)-x(24);
             x(4)+x(8)+x(12)+x(16)+x(20)+x(24);
             -x(1)-x(2)-x(3)-x(4);
             x(1)+x(2)+x(3)+x(4);
             -x(5)-x(6)-x(7)-x(8);
             x(5)+x(6)+x(7)+x(8);
             -x(9)-x(10)-x(11)-x(12);
             x(9)+x(10)+x(11)+x(12);
             -x(13)-x(14)-x(15)-x(16);
             x(13)+x(14)+x(15)+x(16);
             -x(17)-x(18)-x(19)-x(20);
             x(17)+x(18)+x(19)+x(20);
             -x(21)-x(22)-x(23)-x(24);
             x(21)+x(22)+x(23)+x(24)];
cl = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
cu = [-29,29,-41,41,-13,13,-21,21,-8,8,-24,24,-20,20,-24,24,-16,16,-12,12]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCCCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','st_fp8');
opts.sense = 'min';
