% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:03:00
% Model: st_glmp_kk90

% Objective
fun = @(x)x(4)*x(5)+x(3);

% Bounds
lb = [0,3,-Inf,-Inf,-Inf]';
ub = [12,6,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[2*x(1)+3*x(2);
             3*x(1)-x(2);
             -x(1)+2*x(2);
             x(1)+2*x(2);
             x(1)-x(3);
             x(1)-x(2)-x(4);
             x(1)+x(2)-x(5)];
cl = [9,-Inf,-Inf,-Inf,0,-5,1]';
cu = [Inf,8,8,12,0,-5,1]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCC';

% Starting Guess
x0 = [NaN,3,NaN,NaN,NaN]';

% Options
opts = struct('probname','st_glmp_kk90');
opts.sense = 'min';
