% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:03:01
% Model: st_iqpbk1

% Objective
fun = @(x)0.845*x(1)*x(1)+7*x(1)+0.5*x(1)*x(2)+6*x(2)+x(1)*x(3)+5*x(3)+1.5*x(1)*x(4)+4*x(4)+2*x(1)*x(5)+3*x(5)+2.5*x(1)*x(6)+2*x(6)+3*x(1)*x(7)+x(7)+3.5*x(1)*x(8)+0.5*x(2)*x(1)+0.845*x(2)*x(2)+0.5*x(2)*x(3)+x(2)*x(4)+1.5*x(2)*x(5)+2*x(2)*x(6)+2.5*x(2)*x(7)+3*x(2)*x(8)+x(3)*x(1)+0.5*x(3)*x(2)+0.845*x(3)*x(3)+0.5*x(3)*x(4)+x(3)*x(5)+1.5*x(3)*x(6)+2*x(3)*x(7)+2.5*x(3)*x(8)+1.5*x(4)*x(1)+x(4)*x(2)+0.5*x(4)*x(3)+0.845*x(4)*x(4)+0.5*x(4)*x(5)+x(4)*x(6)+1.5*x(4)*x(7)+2*x(4)*x(8)+2*x(5)*x(1)+1.5*x(5)*x(2)+x(5)*x(3)+0.5*x(5)*x(4)+0.845*x(5)*x(5)+0.5*x(5)*x(6)+x(5)*x(7)+1.5*x(5)*x(8)+2.5*x(6)*x(1)+2*x(6)*x(2)+1.5*x(6)*x(3)+x(6)*x(4)+0.5*x(6)*x(5)+0.845*x(6)*x(6)+0.5*x(6)*x(7)+x(6)*x(8)+3*x(7)*x(1)+2.5*x(7)*x(2)+2*x(7)*x(3)+1.5*x(7)*x(4)+x(7)*x(5)+0.5*x(7)*x(6)+0.845*x(7)*x(7)+0.5*x(7)*x(8)+3.5*x(8)*x(1)+3*x(8)*x(2)+2.5*x(8)*x(3)+2*x(8)*x(4)+1.5*x(8)*x(5)+x(8)*x(6)+0.5*x(8)*x(7)+0.845*x(8)*x(8);

% Bounds
lb = [-1,-2.1,-3.2,-4.3,-5.4,-6.5,-7.6,-8.7]';
ub = [1,2,3,4,5,6,7,8]';

% Constraints
nlcon = @(x)[-x(1)+x(2);
             -x(2)+x(3);
             -x(3)+x(4);
             -x(4)+x(5);
             -x(5)+x(6);
             -x(6)+x(7);
             -x(7)+x(8)];
cl = [-1,-1.05,-1.1,-1.15,-1.2,-1.25,-1.3]';
cu = [Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','st_iqpbk1');
opts.sense = 'min';
