% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:03:02
% Model: st_ph2

% Objective
fun = @(x)6*x(1)-3*x(1)^2-2.5*x(2)^2+5*x(2)-2*x(3)^2+4*x(3)-1.5*x(4)^2+3*x(4)-x(5)^2+2*x(5)-0.5*x(6)^2+x(6);

% Bounds
lb = [0,0,0,0,0,0]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[6*x(1)+x(2)+9*x(4)+3*x(5)+5*x(6);
             x(1)+7*x(3)+6*x(4)+2*x(5)+2*x(6);
             5*x(1)+4*x(2)+x(3)+3*x(4)+8*x(5);
             9*x(1)+x(2)+2*x(4)+7*x(5)+6*x(6);
             2*x(1)+6*x(4)+3*x(5)+9*x(6)];
cl = [-Inf,-Inf,-Inf,-Inf,-Inf]';
cu = [96,72,84,100,80]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','st_ph2');
opts.sense = 'min';
