% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:03:01
% Model: st_pan1

% Objective
fun = @(x)1.25*x(1)-2.5*x(1)^2-5*x(2)^2+2.5*x(2)-7.5*x(3)^2+5*x(3);

% Bounds
lb = [0,0,0]';
ub = [Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[10*x(1)+0.2*x(2)-0.1*x(3);
             -0.3*x(1)+9*x(2)+0.2*x(3);
             -0.1*x(1)+0.4*x(2)+11*x(3);
             6*x(1)+8*x(2)+9*x(3)];
cl = [-Inf,-Inf,-Inf,-Inf]';
cu = [11,8,12,18]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [NaN,NaN,NaN]';

% Options
opts = struct('probname','st_pan1');
opts.sense = 'min';
