% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:13:10
% Model: argauss

% Objective
fun = @(x)-0;

% Bounds
lb = [-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[exp(-0.5*(3.5-x(3))^2*x(2))*x(1);
             exp(-0.5*(3-x(3))^2*x(2))*x(1);
             exp(-0.5*(2.5-x(3))^2*x(2))*x(1);
             exp(-0.5*(2-x(3))^2*x(2))*x(1);
             exp(-0.5*(1.5-x(3))^2*x(2))*x(1);
             exp(-0.5*(1-x(3))^2*x(2))*x(1);
             exp(-0.5*(0.5-x(3))^2*x(2))*x(1);
             exp(-0.5*(-x(3))^2*x(2))*x(1);
             exp(-0.5*(-0.5-x(3))^2*x(2))*x(1);
             exp(-0.5*(-1-x(3))^2*x(2))*x(1);
             exp(-0.5*(-1.5-x(3))^2*x(2))*x(1);
             exp(-0.5*(-2-x(3))^2*x(2))*x(1);
             exp(-0.5*(-2.5-x(3))^2*x(2))*x(1);
             exp(-0.5*(-3-x(3))^2*x(2))*x(1);
             exp(-0.5*(-3.5-x(3))^2*x(2))*x(1)];
cl = [0.0009,0.0044,0.0175,0.054,0.1295,0.242,0.3521,0.3989,0.3521,0.242,0.1295,0.054,0.0175,0.0044,0.0009]';
cu = [0.0009,0.0044,0.0175,0.054,0.1295,0.242,0.3521,0.3989,0.3521,0.242,0.1295,0.054,0.0175,0.0044,0.0009]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [NaN,NaN,NaN]';

% Options
opts = struct('probname','argauss');
opts.sense = 'min';
