% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 20:53:52
% Model: csfi1

% Objective
fun = @(x)-x(4);

% Bounds
lb = [7,0.0001,0,0,0]';
ub = [Inf,Inf,60,Inf,Inf]';

% Constraints
nlcon = @(x)[117.370892*x(4)/(x(2)*x(1))-x(5);
             0.0208333333333333*x(1)^2*x(5)-x(3);
             x(2)/x(1);
             x(1)*x(2);
             x(1)*x(2)];
cl = [0,0,-Inf,-Inf,200]';
cu = [0,0,2,250,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCC';

% Starting Guess
x0 = [7,0.0001,NaN,NaN,NaN]';

% Options
opts = struct('probname','csfi1');
opts.sense = 'min';
