% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 00:57:08
% Model: fletcher

% Objective
fun = @(x)x(1)*x(2);

% Bounds
lb = [-Inf,-Inf,-Inf,1]';
ub = [Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[(x(1)*x(3)+x(2)*x(4))^2/(x(1)^2+x(2)^2)-x(3)^2-x(4)^2;
             x(1)-x(3);
             x(2)-x(4);
             x(3)-x(4)];
cl = [-1,1,1,0]';
cu = [-1,Inf,Inf,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,1]';

% Options
opts = struct('probname','fletcher');
opts.sense = 'min';
