% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 00:59:15
% Model: genhs28

% Objective
fun = @(x)(x(1)+x(2))^2+(x(2)+x(3))^2+(x(3)+x(4))^2+(x(4)+x(5))^2+(x(5)+x(6))^2+(x(6)+x(7))^2+(x(7)+x(8))^2+(x(8)+x(9))^2+(x(9)+x(10))^2;

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(1)+2*x(2)+3*x(3);
             x(2)+2*x(3)+3*x(4);
             x(3)+2*x(4)+3*x(5);
             x(4)+2*x(5)+3*x(6);
             x(5)+2*x(6)+3*x(7);
             x(6)+2*x(7)+3*x(8);
             x(7)+2*x(8)+3*x(9);
             x(8)+2*x(9)+3*x(10)];
cl = [1,1,1,1,1,1,1,1]';
cu = [1,1,1,1,1,1,1,1]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','genhs28');
opts.sense = 'min';
