% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 12:35:50
% Model: heart6

% Objective
fun = @(x)-0;

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(3)*x(1)+x(4)*(-0.816-x(1))-x(5)*x(2)-x(6)*(-0.017-x(2));
             x(5)*x(1)+x(6)*(-0.816-x(1))+x(3)*x(2)+x(4)*(-0.017-x(2));
             (x(3)*x(3)-x(5)*x(5))*x(1)-2*x(2)*x(3)*x(5)+(x(4)*x(4)-x(6)*x(6))*(-0.816-x(1))-(-0.034-2*x(2))*x(4)*x(6);
             (x(3)*x(3)-x(5)*x(5))*x(2)+2*x(1)*x(3)*x(5)+(x(4)*x(4)-x(6)*x(6))*(-0.017-x(2))+(-1.632-2*x(1))*x(4)*x(6);
             x(1)*x(3)*(x(3)*x(3)-3*x(5)*x(5))+x(2)*x(5)*(x(5)*x(5)-3*x(3)*x(3))+(-0.816-x(1))*x(4)*(x(4)*x(4)-3*x(6)*x(6))+(-0.017-x(2))*x(6)*(x(6)*x(6)-3*x(4)*x(4));
             x(2)*x(3)*(x(3)*x(3)-3*x(5)*x(5))-x(1)*x(5)*(x(5)*x(5)-3*x(3)*x(3))+(-0.017-x(2))*x(4)*(x(4)*x(4)-3*x(6)*x(6))-(-0.816-x(1))*x(6)*(x(6)*x(6)-3*x(4)*x(4))];
cl = [-1.826,-0.754,-4.839,-3.259,-14.023,15.467]';
cu = [-1.826,-0.754,-4.839,-3.259,-14.023,15.467]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCC';

% Starting Guess
x0 = [0.01,0.01,1,1,1,1]';

% Options
opts = struct('probname','heart6');
opts.sense = 'min';
