% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 01:46:41
% Model: hs042

% Objective
fun = @(x)(-1+x(1))^2+(-2+x(2))^2+(-3+x(3))^2+(-4+x(4))^2;

% Bounds
lb = [2,0,0,0]';
ub = [2,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(3)^2+x(4)^2];
cl = 2';
cu = 2';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCC';

% Starting Guess
x0 = [2,NaN,NaN,NaN]';

% Options
opts = struct('probname','hs042');
opts.sense = 'min';
