% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 01:46:41
% Model: hs041

% Objective
fun = @(x)-x(1)*x(2)*x(3)+2;

% Bounds
lb = [1e-06,0,0,0]';
ub = [1,1,1,2]';

% Constraints
nlcon = @(x)[x(1)+2*x(2)+2*x(3)-x(4)];
cl = 0';
cu = 0';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCC';

% Starting Guess
x0 = [1e-06,NaN,NaN,NaN]';

% Options
opts = struct('probname','hs041');
opts.sense = 'min';
