% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 01:46:43
% Model: hs067

% Objective
fun = @(x)-0.063*x(4)*x(7)+5.04*x(1)+0.035*x(2)+10*x(3)+3.36*x(5);

% Bounds
lb = [1e-05,1e-05,1e-05,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [2000,16000,120,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(4);
             x(5);
             x(6);
             x(7);
             x(8);
             x(9);
             x(10);
             x(4);
             x(5);
             x(6);
             x(7);
             x(8);
             x(9);
             x(10);
             x(1)-1.22*x(4)+x(5);
             -(x(2)+x(5))/x(1)+x(8);
             -(1.12+0.01*(13.167*x(8)-0.6667*x(8)^2))*x(1)+x(4);
             -(1.098*x(8)-0.038*x(8)^2)-0.325*x(6)+x(7);
             -3*x(7)+x(10);
             x(9)+0.222*x(10);
             -98000*x(3)/(x(4)*x(9)+1000*x(3))+x(6)];
cl = [0,0,85,90,3,0.01,145,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,0,0,0,57.425,-133,35.82,0]';
cu = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,5000,2000,93,95,12,4,162,0,0,0,57.425,-133,35.82,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCC';

% Starting Guess
x0 = [1e-05,1e-05,1e-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','hs067');
opts.sense = 'min';
