% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 01:46:44
% Model: hs072

% Objective
fun = @(x)x(1)+x(2)+x(3)+x(4)+1;

% Bounds
lb = [0.001,0.001,0.001,0.001]';
ub = [Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[4/x(1)+2.25/x(2)+1/x(3)+0.25/x(4);
             0.16/x(1)+0.36/x(2)+0.64/x(3)+0.64/x(4);
             x(1);
             x(2);
             x(3);
             x(4)];
cl = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
cu = [0.0401,0.010085,400000,300000,200000,100000]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCC';

% Starting Guess
x0 = [0.001,0.001,0.001,0.001]';

% Options
opts = struct('probname','hs072');
opts.sense = 'min';
