% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 01:46:48
% Model: hs093

% Objective
fun = @(x)0.0204*x(1)*x(4)*(x(1)+x(2)+x(3))+0.0187*x(2)*x(3)*(x(1)+1.57*x(2)+x(4))+0.0607*x(1)*x(4)*x(5)^2*(x(1)+x(2)+x(3))+0.0437*x(2)*x(3)*x(6)^2*(x(1)+1.57*x(2)+x(4));

% Bounds
lb = [0,0,0,0,0,0]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[0.001*x(1)*x(2)*x(3)*x(4)*x(5)*x(6);
             0.00062*x(1)*x(4)*x(5)^2*(x(1)+x(2)+x(3))+0.00058*x(2)*x(3)*x(6)^2*(x(1)+1.57*x(2)+x(4))];
cl = [2.07,-Inf]';
cu = [Inf,1]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','hs093');
opts.sense = 'min';
