% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 01:47:03
% Model: hs106

% Objective
fun = @(x)x(1)+x(2)+x(3);

% Bounds
lb = [100,1000,1000,10,10,10,10,10]';
ub = [10000,10000,10000,1000,1000,1000,1000,1000]';

% Constraints
nlcon = @(x)[-0.0025*x(4)-0.0025*x(6);
             0.0025*x(4)-0.0025*x(5)-0.0025*x(7);
             0.01*x(5)-0.01*x(8);
             x(1)*x(6)-100*x(1)-833.3325*x(4);
             x(2)*x(7)-x(2)*x(4)+1250*x(4)-1250*x(5);
             x(3)*x(8)-x(3)*x(5)+2500*x(5)];
cl = [-1,-1,-1,-83333.33,0,1250000]';
cu = [Inf,Inf,Inf,Inf,Inf,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCC';

% Starting Guess
x0 = [100,1000,1000,10,10,10,10,10]';

% Options
opts = struct('probname','hs106');
opts.sense = 'min';
