% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 01:47:04
% Model: hs117

% Objective
fun = @(x)30*x(11)*x(11)-20*x(12)*x(11)-10*x(13)*x(11)+32*x(14)*x(11)-10*x(15)*x(11)+39*x(12)*x(12)-20*x(11)*x(12)-6*x(13)*x(12)-31*x(14)*x(12)+32*x(15)*x(12)-10*x(11)*x(13)-6*x(12)*x(13)+10*x(13)*x(13)-6*x(14)*x(13)-10*x(15)*x(13)+32*x(11)*x(14)-31*x(12)*x(14)-6*x(13)*x(14)+39*x(14)*x(14)-20*x(15)*x(14)+32*x(12)*x(15)-10*x(11)*x(15)-10*x(13)*x(15)-20*x(14)*x(15)+30*x(15)*x(15)+8*x(11)^3+16*x(12)^3+20*x(13)^3+12*x(14)^3+4*x(15)^3+40*x(1)+2*x(2)+0.25*x(3)+4*x(4)+4*x(5)+x(6)+40*x(7)+60*x(8)-5*x(9)-x(10);

% Bounds
lb = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[12*x(11)^2+60*x(11)+16*x(1)+3.5*x(3)-2*x(6)+x(7)+x(8)-x(9)-x(10)-40*x(12)-20*x(13)+64*x(14)-20*x(15);
             24*x(12)^2+78*x(12)-2*x(1)+2*x(2)+2*x(4)+9*x(5)+x(7)+2*x(8)-2*x(9)-x(10)-40*x(11)-12*x(13)-62*x(14)+64*x(15);
             30*x(13)^2+20*x(13)-2*x(3)+2*x(5)+4*x(6)+x(7)+3*x(8)-3*x(9)-x(10)-20*x(11)-12*x(12)-12*x(14)-20*x(15);
             18*x(14)^2+78*x(14)-x(1)-4*x(2)+4*x(4)-x(5)+x(7)+2*x(8)-4*x(9)-x(10)+64*x(11)-62*x(12)-12*x(13)-40*x(15);
             6*x(15)^2+60*x(15)-2*x(2)+x(4)+2.8*x(5)+x(7)+x(8)-5*x(9)-x(10)-20*x(11)+64*x(12)-20*x(13)-40*x(14)];
cl = [15,27,36,18,12]';
cu = [Inf,Inf,Inf,Inf,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','hs117');
opts.sense = 'min';
