% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 13:13:53
% Model: nonmsqrt

% Objective
fun = @(x)(-0.925959366733121+x(1)*x(1)+x(2)*x(1)+x(3)*x(1))^2+(0.157503469054834+x(1)*x(2)+x(2)*x(2)+x(3)*x(2))^2+(-0.837777972640949+x(1)*x(3)+x(2)*x(3)+x(3)*x(3))^2+(0.204157779584037+x(4)*x(4)+x(5)*x(4)+x(6)*x(4))^2+(0.677059435087132+x(4)*x(5)+x(5)*x(5)+x(6)*x(5))^2+(-0.637322980962176+x(4)*x(6)+x(5)*x(6)+x(6)*x(6))^2+(0.264878547815076+x(7)*x(7)+x(8)*x(7)+x(9)*x(7))^2+(0.701280412170914+x(7)*x(8)+x(8)*x(8)+x(9)*x(8))^2+(0.515703483969531+x(7)*x(9)+x(8)*x(9)+x(9)*x(9))^2;

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCC';

% Starting Guess
x0 = [0.168294196961579,-0.151360499061586,0.0824236970483513,-0.0575806633330131,-0.0264703500195546,-0.198355770688623,0.763002122207578,0.184005207639358,-0.125977598854891]';

% Options
opts = struct('probname','nonmsqrt');
opts.sense = 'min';
