% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 14:44:51
% Model: prodpl0

% Objective
fun = @(x)x(21)+2*x(22)+2*x(23)+3*x(24)+3*x(25)+2*x(26)+4*x(27)+5*x(28)+x(29)+2*x(30)+2*x(31)+3*x(32)+3*x(33)+2*x(34)+4*x(35)+5*x(36)+x(37)+2*x(38)+2*x(39)+3*x(40)+3*x(41)+2*x(42)+4*x(43)+5*x(44)+x(45)+2*x(46)+2*x(47)+3*x(48)+3*x(49)+2*x(50)+4*x(51)+5*x(52)+x(53)+2*x(54)+2*x(55)+3*x(56)+3*x(57)+2*x(58)+4*x(59)+5*x(60);

% Bounds
lb = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[-x(1)-x(2)-x(3)-x(4);
             -x(5)-x(6)-x(7)-x(8);
             -x(9)-x(10)-x(11)-x(12);
             -x(13)-x(14)-x(15)-x(16);
             -x(17)-x(18)-x(19)-x(20);
             x(1)-x(21)+x(22);
             x(2)-x(23)+x(24);
             x(3)-x(25)+x(26);
             x(4)-x(27)+x(28);
             x(5)+x(21)-x(29)+x(30);
             x(6)+x(23)-x(31)+x(32);
             x(7)+x(25)-x(33)+x(34);
             x(8)+x(27)-x(35)+x(36);
             x(9)+x(29)-x(37)+x(38);
             x(10)+x(31)-x(39)+x(40);
             x(11)+x(33)-x(41)+x(42);
             x(12)+x(35)-x(43)+x(44);
             x(13)+x(37)-x(45)+x(46);
             x(14)+x(39)-x(47)+x(48);
             x(15)+x(41)-x(49)+x(50);
             x(16)+x(43)-x(51)+x(52);
             x(17)+x(45)-x(53)+x(54);
             x(18)+x(47)-x(55)+x(56);
             x(19)+x(49)-x(57)+x(58);
             x(20)+x(51)-x(59)+x(60);
             -((x(4)-x(3)+x(7)+x(8))^2-0.01*(x(3)+x(4))^2);
             -((x(8)-x(7)+x(11)+x(12))^2-0.01*(x(7)+x(8))^2);
             -((x(12)-x(11)+x(15)+x(16))^2-0.01*(x(11)+x(12))^2);
             -((x(16)-x(15)+x(19)+x(20))^2-0.01*(x(15)+x(16))^2)];
cl = [-3,-6,-10,-2000,-18,1,1,1,1,2.667,1.667,2.667,3.333,2.667,2,3,3,2.667,2.667,2.667,2.667,2.667,2.333,2.333,2.333,0,0,0,0]';
cu = [Inf,Inf,Inf,Inf,Inf,1,1,1,1,2.667,1.667,2.667,3.333,2.667,2,3,3,2.667,2.667,2.667,2.667,2.667,2.333,2.333,2.333,Inf,Inf,Inf,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','prodpl0');
opts.sense = 'min';
