% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 05:03:36
% Model: s243

% Objective
fun = @(x)x(4)^2+x(5)^2+x(6)^2+x(7)^2;

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[-(0.87584*(x(1)*(2.95137*x(1)+4.87407*x(2)-2.0506*x(3))+x(2)*(2.95137*x(1)+4.87407*x(2)-2.0506*x(3))+x(3)*(2.95137*x(1)+4.87407*x(2)-2.0506*x(3)))-0.564255*x(1)+0.392417*x(2)-0.404979*x(3))+x(4);
             -(0.927589*x(1)-0.675975*(x(1)*(4.87407*x(1)+9.39321*x(2)-3.93181*x(3))+x(2)*(4.87407*x(1)+9.39321*x(2)-3.93181*x(3))+x(3)*(4.87407*x(1)+9.39321*x(2)-3.93181*x(3)))-0.0735084*x(2)+0.535493*x(3))+x(5);
             -(0.658799*x(1)-0.239524*(x(1)*(-2.0506*x(1)-3.93189*x(2)+2.64745*x(3))+x(2)*(-2.0506*x(1)-3.93189*x(2)+2.64745*x(3))+x(3)*(-2.0506*x(1)-3.93189*x(2)+2.64745*x(3)))-0.636666*x(2)-0.681091*x(3))+x(6);
             0.869487*x(1)-0.586387*x(2)-0.289826*x(3)+x(7)];
cl = [0.14272,-0.184918,-0.521869,-0.685306]';
cu = [0.14272,-0.184918,-0.521869,-0.685306]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','s243');
opts.sense = 'min';
