% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 05:03:37
% Model: s277

% Objective
fun = @(x)2.08333333333333*x(1)+1.28333333333333*x(2)+0.95*x(3)+0.759523809523809*x(4);

% Bounds
lb = [0,0,0,0]';
ub = [Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[2.08333333333333*x(1);
             1.28333333333333*x(2);
             0.95*x(3);
             0.759523809523809*x(4)];
cl = [2.08333333333333,1.28333333333333,0.95,0.759523809523809]';
cu = [Inf,Inf,Inf,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','s277');
opts.sense = 'min';
