% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 05:03:38
% Model: s278

% Objective
fun = @(x)2.45*x(1)+1.59285714285714*x(2)+1.21785714285714*x(3)+0.995634920634921*x(4)+0.845634920634921*x(5)+0.736544011544012*x(6);

% Bounds
lb = [0,0,0,0,0,0]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[2.45*x(1);
             1.59285714285714*x(2);
             1.21785714285714*x(3);
             0.995634920634921*x(4);
             0.845634920634921*x(5);
             0.736544011544012*x(6)];
cl = [2.45,1.59285714285714,1.21785714285714,0.995634920634921,0.845634920634921,0.736544011544012]';
cu = [Inf,Inf,Inf,Inf,Inf,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','s278');
opts.sense = 'min';
