% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 05:03:39
% Model: s289

% Objective
fun = @(x)-exp(-(0.0166666666666667*x(1)^2+0.0166666666666667*x(2)^2+0.0166666666666667*x(3)^2+0.0166666666666667*x(4)^2+0.0166666666666667*x(5)^2+0.0166666666666667*x(6)^2+0.0166666666666667*x(7)^2+0.0166666666666667*x(8)^2+0.0166666666666667*x(9)^2+0.0166666666666667*x(10)^2+0.0166666666666667*x(11)^2+0.0166666666666667*x(12)^2+0.0166666666666667*x(13)^2+0.0166666666666667*x(14)^2+0.0166666666666667*x(15)^2+0.0166666666666667*x(16)^2+0.0166666666666667*x(17)^2+0.0166666666666667*x(18)^2+0.0166666666666667*x(19)^2+0.0166666666666667*x(20)^2+0.0166666666666667*x(21)^2+0.0166666666666667*x(22)^2+0.0166666666666667*x(23)^2+0.0166666666666667*x(24)^2+0.0166666666666667*x(25)^2+0.0166666666666667*x(26)^2+0.0166666666666667*x(27)^2+0.0166666666666667*x(28)^2+0.0166666666666667*x(29)^2+0.0166666666666667*x(30)^2))+1;

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = [];
cl = [];
cu = [];

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','s289');
opts.sense = 'min';
