% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 05:03:40
% Model: s329

% Objective
fun = @(x)(-10+x(1))^3+(-20+x(2))^3;

% Bounds
lb = [13,0]';
ub = [16,15]';

% Constraints
nlcon = @(x)[(-5+x(1))^2+(-5+x(2))^2;
             (-6+x(1))^2+(-5+x(2))^2;
             (-(-6+x(1))^2)-(-5+x(2))^2];
cl = [100,0,-82.81]';
cu = [Inf,Inf,-82.81]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CC';

% Starting Guess
x0 = [13,NaN]';

% Options
opts = struct('probname','s329');
opts.sense = 'min';
