% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 05:03:41
% Model: s347

% Objective
fun = @(x)8204.37*log(x(4))+9008.72*log(x(5))+9330.46*log(x(6));

% Bounds
lb = [0,0,0,1e-06,1e-06,1e-06]';
ub = [1,1,1,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(1)+x(2)+x(3);
             -(0.03+x(1)+x(2)+x(3))/(0.03+0.09*x(1)+x(2)+x(3))+x(4);
             -(0.03+x(2)+x(3))/(0.03+0.07*x(2)+x(3))+x(5);
             -(0.03+x(3))/(0.03+0.13*x(3))+x(6)];
cl = [1,0,0,0]';
cu = [1,0,0,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,1e-06,1e-06,1e-06]';

% Options
opts = struct('probname','s347');
opts.sense = 'min';
