% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 05:03:42
% Model: s353

% Objective
fun = @(x)-24.55*x(1)-26.75*x(2)-39*x(3)-40.5*x(4);

% Bounds
lb = [0,0,0,0,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[-((0.53*x(1))^2+(0.44*x(2))^2+(4.5*x(3))^2+(0.79*x(4))^2)+x(5);
             2.3*x(1)+5.6*x(2)+11.1*x(3)+1.3*x(4);
             12*x(1)+11.9*x(2)+41.8*x(3)+52.1*x(4)-1.645*x(5);
             x(1)+x(2)+x(3)+x(4)];
cl = [0,5,12,1]';
cu = [0,Inf,Inf,1]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','s353');
opts.sense = 'min';
