% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 05:03:42
% Model: s354

% Objective
fun = @(x)(x(1)+10*x(2))^2+5*(x(3)-x(4))^2+(x(2)-2*x(3))^4+10*(x(1)-x(4))^4;

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf]';
ub = [20,20,20,20]';

% Constraints
nlcon = @(x)[x(1)+x(2)+x(3)+x(4)];
cl = 1';
cu = Inf';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','s354');
opts.sense = 'min';
