% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-Jan-2014 05:03:45
% Model: s376

% Objective
fun = @(x)-(-1200+3000*x(1)+280000*x(2))/(0.002+x(1)+60*x(2));

% Bounds
lb = [0,0,5e-05,10,5e-05,5e-05,5e-05,5e-05,5e-05,5e-05]';
ub = [10,0.1,0.0081,1000,0.0017,0.0013,0.0027,0.002,1,1]';

% Constraints
nlcon = @(x)[-0.75/(x(3)*x(4))+x(1);
             -x(9)/(x(5)*x(4))+x(1);
             (-x(10)/(x(6)*x(4)))-10/x(4)+x(1);
             (-0.19/(x(4)*x(7)))-10/x(4)+x(1);
             -0.125/(x(4)*x(8))+x(1);
             -0.00131*exp(0.666*log(x(5)))*x(9)*exp(1.5*log(x(4)))+10000*x(2);
             -0.001038*exp(1.6*log(x(6)))*x(10)*x(4)^3+10000*x(2);
             -0.000223*exp(0.666*log(x(7)))*exp(1.5*log(x(4)))+10000*x(2);
             -7.6e-5*exp(3.55*log(x(8)))*exp(5.66*log(x(4)))+10000*x(2);
             -0.000698*exp(1.2*log(x(3)))*x(4)^2+10000*x(2);
             -5e-5*exp(1.6*log(x(3)))*x(4)^3+10000*x(2);
             -6.54e-6*exp(2.42*log(x(3)))*exp(4.17*log(x(4)))+10000*x(2);
             -0.000257*exp(0.666*log(x(3)))*exp(1.5*log(x(4)))+10000*x(2);
             (-2.003*x(4)*x(5))-1.885*x(6)*x(4)-0.184*x(8)*x(4)-2*exp(0.803*log(x(3)))*x(4);
             x(9)+x(10)];
cl = [0,0,0,0,0,0,0,0,0,0,0,0,0,-30,0.255]';
cu = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,0.255]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,5e-05,10,5e-05,5e-05,5e-05,5e-05,5e-05,5e-05]';

% Options
opts = struct('probname','s376');
opts.sense = 'min';
