% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 01-Feb-2014 23:37:19
% Model: vanderm4

% Objective
fun = @(x)-0;

% Bounds
lb = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[(-1.99609375+x(1)+x(2)+x(3)+x(4)+x(5)+x(6)+x(7)+x(8)+x(9))^2;
             (-1.33332824707031+x(1)^2+x(2)^2+x(3)^2+x(4)^2+x(5)^2+x(6)^2+x(7)^2+x(8)^2+x(9)^2)^2;
             (-1.14285713434219+x(1)^3+x(2)^3+x(3)^3+x(4)^3+x(5)^3+x(6)^3+x(7)^3+x(8)^3+x(9)^3)^2;
             (-1.06666666665114+x(1)^4+x(2)^4+x(3)^4+x(4)^4+x(5)^4+x(6)^4+x(7)^4+x(8)^4+x(9)^4)^2;
             (-1.0322580645161+x(1)^5+x(2)^5+x(3)^5+x(4)^5+x(5)^5+x(6)^5+x(7)^5+x(8)^5+x(9)^5)^2;
             (-1.01587301587302+x(1)^6+x(2)^6+x(3)^6+x(4)^6+x(5)^6+x(6)^6+x(7)^6+x(8)^6+x(9)^6)^2;
             (-1.00787401574803+x(1)^7+x(2)^7+x(3)^7+x(4)^7+x(5)^7+x(6)^7+x(7)^7+x(8)^7+x(9)^7)^2;
             (-1.00392156862745+x(1)^8+x(2)^8+x(3)^8+x(4)^8+x(5)^8+x(6)^8+x(7)^8+x(8)^8+x(9)^8)^2;
             (-1.00195694716243+x(1)^9+x(2)^9+x(3)^9+x(4)^9+x(5)^9+x(6)^9+x(7)^9+x(8)^9+x(9)^9)^2;
             -x(1)+x(2);
             -x(2)+x(3);
             -x(3)+x(4);
             -x(4)+x(5);
             -x(5)+x(6);
             -x(6)+x(7);
             -x(7)+x(8);
             -x(8)+x(9)];
cl = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]';
cu = [0,0,0,0,0,0,0,0,0,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCC';

% Starting Guess
x0 = [NaN,0.111111111111111,0.222222222222222,0.333333333333333,0.444444444444444,0.555555555555556,0.666666666666667,0.777777777777778,0.888888888888889]';

% Options
opts = struct('probname','vanderm4');
opts.sense = 'min';
