% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 01-Feb-2014 23:50:35
% Model: zy2

% Objective
fun = @(x)x(1)^3-6*x(1)^2+11*x(1)+x(2)+x(3);

% Bounds
lb = [0,0,0]';
ub = [Inf,Inf,5]';

% Constraints
nlcon = @(x)[-(x(1)^2+x(2)^2+x(3)^2);
             x(1)^2+x(2)^2+x(3)^2];
cl = [-Inf,-Inf]';
cu = [-4,10]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [0.1,0.1,3]';

% Options
opts = struct('probname','zy2');
opts.sense = 'min';
