% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 21-Jun-2014 09:14:32
% Model: FLay03M

% Objective
fun = @(x)2*x(13)+2*x(14);

% Bounds
lb = [0,0,0,0,0,0,1,1,1,1,1,1,0,0,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
ub = [29,29,29,29,29,29,40,50,60,40,50,60,30,30,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[-x(1)-x(7)+x(13);
             -x(2)-x(8)+x(13);
             -x(3)-x(9)+x(13);
             -x(4)-x(10)+x(14);
             -x(5)-x(11)+x(14);
             -x(6)-x(12)+x(14);
             40/x(10)-x(7);
             50/x(11)-x(8);
             60/x(12)-x(9);
             x(1)-x(2)+x(7)+69*x(15);
             x(1)-x(3)+x(7)+69*x(16);
             x(2)-x(3)+x(8)+79*x(17);
             -x(1)+x(2)+x(8)+79*x(18);
             -x(1)+x(3)+x(9)+89*x(19);
             -x(2)+x(3)+x(9)+89*x(20);
             x(4)-x(5)+x(10)+69*x(21);
             x(4)-x(6)+x(10)+69*x(22);
             x(5)-x(6)+x(11)+79*x(23);
             -x(4)+x(5)+x(11)+79*x(24);
             -x(4)+x(6)+x(12)+89*x(25);
             -x(5)+x(6)+x(12)+89*x(26);
             x(15)+x(18)+x(21)+x(24);
             x(16)+x(19)+x(22)+x(25);
             x(17)+x(20)+x(23)+x(26)];
cl = [0,0,0,0,0,0,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,1,1,1]';
cu = [Inf,Inf,Inf,Inf,Inf,Inf,0,0,0,69,69,79,79,89,89,69,69,79,79,89,89,1,1,1]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCBBBBBBBBBBBB';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','FLay03M');
opts.sense = 'min';
