% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 21-Jun-2014 09:14:31
% Model: FLay02M

% Objective
fun = @(x)2*x(9)+2*x(10);

% Bounds
lb = [0,0,0,0,1,1,1,1,0,0,-Inf,-Inf,-Inf,-Inf]';
ub = [29,29,29,29,40,50,40,50,30,30,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[-x(1)-x(5)+x(9);
             -x(2)-x(6)+x(9);
             -x(3)-x(7)+x(10);
             -x(4)-x(8)+x(10);
             40/x(7)-x(5);
             50/x(8)-x(6);
             x(1)-x(2)+x(5)+69*x(11);
             -x(1)+x(2)+x(6)+79*x(12);
             x(3)-x(4)+x(7)+69*x(13);
             -x(3)+x(4)+x(8)+79*x(14);
             x(11)+x(12)+x(13)+x(14)];
cl = [0,0,0,0,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,1]';
cu = [Inf,Inf,Inf,Inf,0,0,69,79,69,79,1]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCBBBB';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,1,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','FLay02M');
opts.sense = 'min';
