% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 13:50:26
% Model: bearing

% Objective
fun = @(x)x(6)+x(7);

% Bounds
lb = [1,1,1,1,1,0.0001,0.0001,1,-Inf,100,1,0.0001,0.01]';
ub = [16,16,16,16,1000,Inf,Inf,Inf,50,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[-1.42857142857143*x(4)*x(5)+10000*x(7);
             10*x(6)*x(8)-0.00968946189201592*(x(1)^4-x(2)^4)*x(3);
             143.3076*x(9)*x(4)-10000*x(6);
             3.1415927*(0.001*x(8))^3*x(5)-6e-6*x(3)*x(4)*x(12);
             101000*x(11)*x(12)-1.57079635*x(5)*x(13);
             0.434294481903525*log(0.8+8.112*x(3))-10964781961.4318*x(10)^(-3.55);
             -0.5*x(9)+x(10);
             x(1)-x(2);
             0.0307*x(4)^2-0.3864*(0.0062831854*x(1)*x(8))^2*x(5);
             101000*x(11)-15707.9635*x(13);
             -(log(x(1))-log(x(2)))+x(12);
             -(x(1)^2-x(2)^2)+x(13)];
cl = [0,0,0,0,0,0,560,0,-Inf,-Inf,0,0]';
cu = [0,0,0,0,0,0,560,Inf,0,0,0,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCC';

% Starting Guess
x0 = [6,5,6,3,1000,1.6,0.3,1,50,600,1,0.0001,0.01]';

% Options
opts = struct('probname','bearing');
opts.sense = 'min';
