% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 13:53:51
% Model: ex14_1_9

% Objective
fun = @(x)x(2);

% Bounds
lb = [100,-Inf]';
ub = [1000,Inf]';

% Constraints
nlcon = @(x)[4510067.11409396*exp(-7548.11926028431/x(1))*x(1)+0.00335570469798658*x(1)-2020510067.11409*exp(-7548.11926028431/x(1))-x(2);
             (-4510067.11409396*exp(-7548.11926028431/x(1))*x(1))-0.00335570469798658*x(1)+2020510067.11409*exp(-7548.11926028431/x(1))-x(2)];
cl = [-Inf,-Inf]';
cu = [1,-1]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CC';

% Starting Guess
x0 = [100,NaN]';

% Options
opts = struct('probname','ex14_1_9');
opts.sense = 'min';
