% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 13:53:52
% Model: ex2_1_2

% Objective
fun = @(x)(-0.5*(x(1)*x(1)+x(2)*x(2)+x(3)*x(3)+x(4)*x(4)+x(5)*x(5)))-10.5*x(1)-7.5*x(2)-3.5*x(3)-2.5*x(4)-1.5*x(5)-10*x(6);

% Bounds
lb = [0,0,0,0,0,0]';
ub = [1,1,1,1,1,Inf]';

% Constraints
nlcon = @(x)[6*x(1)+3*x(2)+3*x(3)+2*x(4)+x(5);
             10*x(1)+10*x(3)+x(6)];
cl = [-Inf,-Inf]';
cu = [6.5,20]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCC';

% Starting Guess
x0 = [NaN,1,NaN,1,1,20]';

% Options
opts = struct('probname','ex2_1_2');
opts.sense = 'min';
