% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 13:53:54
% Model: ex4_1_8

% Objective
fun = @(x)x(2)^2-7*x(2)-12*x(1);

% Bounds
lb = [0,0]';
ub = [2,3]';

% Constraints
nlcon = @(x)[-2*x(1)^4-x(2)];
cl = -2';
cu = -2';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CC';

% Starting Guess
x0 = [0.7175,1.47]';

% Options
opts = struct('probname','ex4_1_8');
opts.sense = 'min';
