% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 13:53:54
% Model: ex4_1_9

% Objective
fun = @(x)-x(1)-x(2);

% Bounds
lb = [0,0]';
ub = [3,4]';

% Constraints
nlcon = @(x)[8*x(1)^3-2*x(1)^4-8*x(1)^2+x(2);
             32*x(1)^3-4*x(1)^4-88*x(1)^2+96*x(1)+x(2)];
cl = [-Inf,-Inf]';
cu = [2,36]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CC';

% Starting Guess
x0 = [2.3295,3.17846]';

% Options
opts = struct('probname','ex4_1_9');
opts.sense = 'min';
