% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 13:53:54
% Model: ex6_1_1

% Objective
fun = @(x)(log(x(1))-log(x(1)+x(3)))*x(1)+(log(x(3))-log(x(1)+x(3)))*x(3)+(log(x(2))-log(x(2)+x(4)))*x(2)+(log(x(4))-log(x(2)+x(4)))*x(4)+0.925356626778358*x(1)*x(7)+0.746014540096753*x(3)*x(5)+0.925356626778358*x(2)*x(8)+0.746014540096753*x(4)*x(6);

% Bounds
lb = [1e-07,1e-07,1e-07,1e-07,0,0,0,0]';
ub = [0.5,0.5,0.5,0.5,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(5)*(x(1)+0.159040857374844*x(3))-x(1);
             x(6)*(x(2)+0.159040857374844*x(4))-x(2);
             x(7)*(0.307941026821595*x(1)+x(3))-x(3);
             x(8)*(0.307941026821595*x(2)+x(4))-x(4);
             x(1)+x(2);
             x(3)+x(4)];
cl = [0,0,0,0,0.5,0.5]';
cu = [0,0,0,0,0.5,0.5]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCC';

% Starting Guess
x0 = [0.4993,0.0007,0.3441,0.1559,0.901221308981222,0.0274569351394739,0.691165161172019,0.998619236157215]';

% Options
opts = struct('probname','ex6_1_1');
opts.sense = 'min';
