% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 13:53:54
% Model: ex6_2_12

% Objective
fun = @(x)log(x(1)/(8*x(1)+x(3)))*x(1)+log(x(3)/(8*x(1)+x(3)))*x(3)+0.0696225416798359*x(1)+0.752006*x(3)+log(8*x(1)+1.6*x(3))*(8*x(1)+1.6*x(3))+5*log(x(1)/(5.00000397494442*x(1)+0.480353357956269*x(3)))*x(1)+3*log(x(1)/(8.96062592375197*x(1)+1.13841069150863*x(3)))*x(1)+1.6*log(x(3)/(1.69889877049372*x(1)+1.6*x(3)))*x(3)+log(x(2)/(8*x(2)+x(4)))*x(2)+log(x(4)/(8*x(2)+x(4)))*x(4)+0.0696225416798359*x(2)+0.752006*x(4)+log(8*x(2)+1.6*x(4))*(8*x(2)+1.6*x(4))+5*log(x(2)/(5.00000397494442*x(2)+0.480353357956269*x(4)))*x(2)+3*log(x(2)/(8.96062592375197*x(2)+1.13841069150863*x(4)))*x(2)+1.6*log(x(4)/(1.69889877049372*x(2)+1.6*x(4)))*x(4)-8*log(x(1))*x(1)-1.6*log(x(3))*x(3)-8*log(x(2))*x(2)-1.6*log(x(4))*x(4);

% Bounds
lb = [1e-07,1e-07,1e-07,1e-07]';
ub = [0.5,0.5,0.5,0.5]';

% Constraints
nlcon = @(x)[x(1)+x(2);
             x(3)+x(4)];
cl = [0.5,0.5]';
cu = [0.5,0.5]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCC';

% Starting Guess
x0 = [0.4994,0.0006,0.1179,0.3821]';

% Options
opts = struct('probname','ex6_2_12');
opts.sense = 'min';
