% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 13:53:54
% Model: ex6_2_6

% Objective
fun = @(x)log(3.9235*x(1)+6.0909*x(2)+0.92*x(3))*(26.9071667605344*x(1)+41.7710875549227*x(2)+6.30931398488382*x(3))+0.668686155614739*x(1)-1.14374230885457*x(2)+2.8906196099828*x(3)+9.58716676053442*log(x(1))*x(1)+16.9310875549227*log(x(2))*x(2)+0.309313984883821*log(x(3))*x(3)-9.58716676053442*log(3.9235*x(1)+6.0909*x(2)+0.92*x(3))*x(1)-16.9310875549227*log(3.9235*x(1)+6.0909*x(2)+0.92*x(3))*x(2)-0.309313984883821*log(3.9235*x(1)+6.0909*x(2)+0.92*x(3))*x(3)+18.32*log(x(1))*x(1)+25.84*log(x(2))*x(2)+7*log(x(3))*x(3)-18.32*log(3.664*x(1)+5.168*x(2)+1.4*x(3))*x(1)-25.84*log(3.664*x(1)+5.168*x(2)+1.4*x(3))*x(2)-7*log(3.664*x(1)+5.168*x(2)+1.4*x(3))*x(3)+log(4.0643*x(1)+5.7409*x(2)+1.6741*x(3))*(4.0643*x(1)+5.7409*x(2)+1.6741*x(3))+4.0643*log(x(1))*x(1)+5.7409*log(x(2))*x(2)+1.6741*log(x(3))*x(3)-4.0643*log(4.0643*x(1)+3.22644664511275*x(2)+1.44980651607875*x(3))*x(1)-5.7409*log(5.31147575751424*x(1)+5.7409*x(2)+0.00729924451284409*x(3))*x(2)-1.6741*log(2.25846661774355*x(1)+3.70876916588753*x(2)+1.6741*x(3))*x(3)-30.9714667605344*log(x(1))*x(1)-47.5119875549227*log(x(2))*x(2)-7.98341398488382*log(x(3))*x(3);

% Bounds
lb = [1e-06,1e-06,1e-06]';
ub = [1,1,1]';

% Constraints
nlcon = @(x)[x(1)+x(2)+x(3)];
cl = 1';
cu = 1';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [0.51802,0.0511,0.43088]';

% Options
opts = struct('probname','ex6_2_6');
opts.sense = 'min';
