% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 13:53:54
% Model: ex7_2_1

% Objective
fun = @(x)0.035*x(1)*x(6)-0.063*x(3)*x(5)+1.715*x(1)+4.0565*x(3)+10*x(2)+3000;

% Bounds
lb = [1500,1,3000,85,90,3,145]';
ub = [2000,120,3500,93,95,12,162]';

% Constraints
nlcon = @(x)[0.0059553571*x(6)^2+0.88392857*x(3)/x(1)-0.1175625*x(6);
             1.1088*x(1)/x(3)+0.1303533*x(1)/x(3)*x(6)-0.0066033*x(1)/x(3)*x(6)^2;
             0.00066173269*x(6)^2-0.019120592*x(6)-0.0056595559*x(4)+0.017239878*x(5);
             56.85075/x(5)+1.08702*x(6)/x(5)+0.32175*x(4)/x(5)-0.03762*x(6)^2/x(5);
             2462.3121*x(2)/x(3)/x(4)-25.125634*x(2)/x(3)+0.006198*x(7);
             161.18996/x(7)+5000*x(2)/x(3)/x(7)-489510*x(2)/x(3)/x(4)/x(7);
             44.333333/x(5)+0.33*x(7)/x(5);
             0.022556*x(5)-0.007595*x(7);
             -0.0005*x(1)+0.00061*x(3);
             0.819672*x(1)/x(3)+0.819672/x(3);
             24500*x(2)/x(3)/x(4)-250*x(2)/x(3);
             1.2244898e-5*x(3)/x(2)*x(4)+0.010204082*x(4);
             6.25e-5*x(1)*x(6)+6.25e-5*x(1)-7.625e-5*x(3);
             1.22*x(3)/x(1)+1/x(1)-x(6)];
cl = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
cu = [1,1,1,1,1,1,1,1,1,1,1,1,1,1]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCC';

% Starting Guess
x0 = [1500,1,3000,85,90,3,145]';

% Options
opts = struct('probname','ex7_2_1');
opts.sense = 'min';
