% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 13:53:55
% Model: ex7_3_3

% Objective
fun = @(x)x(5);

% Bounds
lb = [-Inf,-Inf,-Inf,0,-Inf]';
ub = [Inf,Inf,Inf,10,Inf]';

% Constraints
nlcon = @(x)[9.625*x(1)*x(4)-4*x(1)-78*x(4)+16*x(2)*x(4)-x(2)+16*x(4)^2+x(3);
             16*x(1)*x(4)-19*x(1)-24*x(4)-8*x(2)-x(3);
             x(1)-0.25*x(5);
             -x(1)-0.25*x(5);
             -x(2)-0.5*x(5);
             x(2)-0.5*x(5);
             -x(3)-1.5*x(5);
             x(3)-1.5*x(5)];
cl = [-12,-44,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
cu = [-12,-44,2.25,-2.25,-1.5,1.5,-1.5,1.5]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','ex7_3_3');
opts.sense = 'min';
