% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 14:33:58
% Model: ex9_2_5

% Objective
fun = @(x)(-3+x(2))*(-3+x(2))+(-2+x(1))*(-2+x(1));

% Bounds
lb = [-Inf,0,0,0,0,0,0,0]';
ub = [Inf,8,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(1)-2*x(2)+x(3);
             -2*x(1)+x(2)+x(4);
             2*x(1)+x(2)+x(5);
             x(3)*x(6);
             x(4)*x(7);
             x(5)*x(8);
             2*x(1)+x(6)-2*x(7)+2*x(8)];
cl = [1,2,14,0,0,0,10]';
cu = [1,2,14,0,0,0,10]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','ex9_2_5');
opts.sense = 'min';
