% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 15:32:31
% Model: mathopt2

% Objective
fun = @(x)(2*x(1)^2-x(2))^2+(x(2)-6*x(1)^2)^2;

% Bounds
lb = [-Inf,-Inf]';
ub = [Inf,Inf]';

% Constraints
nlcon = @(x)[x(1)-(x(1)*x(2)+10*x(2));
             x(1)-3*x(2);
             x(1)+x(2);
             -x(1)+x(2)];
cl = [0,0,-Inf,-Inf]';
cu = [0,0,1,2]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CC';

% Starting Guess
x0 = [10,-10]';

% Options
opts = struct('probname','mathopt2');
opts.sense = 'min';
