% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 16:07:55
% Model: nemhaus

% Objective
fun = @(x)2*x(1)*x(3)+4*x(1)*x(4)+3*x(1)*x(5)+6*x(2)*x(3)+2*x(2)*x(4)+3*x(2)*x(5)+5*x(3)*x(4)+3*x(3)*x(5)+3*x(4)*x(5);

% Bounds
lb = [0,0,0,0,0]';
ub = [Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(1);
             x(2);
             x(3);
             x(4);
             x(5)];
cl = [1,1,1,1,1]';
cu = [1,1,1,1,1]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','nemhaus');
opts.sense = 'min';
