% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:01:28
% Model: prob06

% Objective
fun = @(x)x(1);

% Bounds
lb = [1,1]';
ub = [5.5,5.5]';

% Constraints
nlcon = @(x)[0.25*x(1)-0.0625*x(1)^2-0.0625*x(2)^2+0.5*x(2);
             0.0714285714285714*x(1)^2+0.0714285714285714*x(2)^2-0.428571428571429*x(1)-0.428571428571429*x(2)];
cl = [-Inf,-Inf]';
cu = [1,-1]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CC';

% Starting Guess
x0 = [1,1]';

% Options
opts = struct('probname','prob06');
opts.sense = 'min';
