% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:02:58
% Model: st_bpaf1b

% Objective
fun = @(x)x(1)*x(6)+2*x(1)-2*x(6)+x(2)*x(7)+4*x(2)-x(7)+x(3)*x(8)+8*x(3)-2*x(8)+x(4)*x(9)-x(4)-4*x(9)+x(5)*x(10)-3*x(5)+5*x(10);

% Bounds
lb = [0,0,0,0,0,0,0,0,0,0]';
ub = [20,20,20,20,20,20,20,20,20,20]';

% Constraints
nlcon = @(x)[-8*x(1)-6*x(3)+7*x(4)-7*x(5);
             -6*x(1)+2*x(2)-3*x(3)+9*x(4)-3*x(5);
             6*x(1)-7*x(3)-8*x(4)+2*x(5);
             -x(1)+x(2)-8*x(3)-7*x(4)-5*x(5);
             4*x(1)-7*x(2)+4*x(3)+5*x(4)+x(5);
             5*x(7)-4*x(8)+9*x(9)-7*x(10);
             7*x(6)+4*x(7)+3*x(8)+7*x(9)+5*x(10);
             6*x(6)+x(7)-8*x(8)+8*x(9);
             -3*x(6)+2*x(7)+7*x(8)+x(10);
             -2*x(6)-3*x(7)+8*x(8)+5*x(9)-2*x(10)];
cl = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
cu = [1,3,5,4,0,0,7,3,6,2]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','st_bpaf1b');
opts.sense = 'min';
