% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:02:58
% Model: st_bsj2

% Objective
fun = @(x)2*x(1)-x(1)^2-x(2)^2-x(3)^2+2*x(3);

% Bounds
lb = [0,0,0]';
ub = [Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(1)+x(2)-x(3);
             -x(1)+x(2)-x(3);
             12*x(1)+5*x(2)+12*x(3);
             12*x(1)+12*x(2)+7*x(3);
             -6*x(1)+x(2)+x(3)];
cl = [-Inf,-Inf,-Inf,-Inf,-Inf]';
cu = [1,-1,34.8,29.1,-4.1]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [NaN,NaN,NaN]';

% Options
opts = struct('probname','st_bsj2');
opts.sense = 'min';
