% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:02:59
% Model: st_e25

% Objective
fun = @(x)(0.217796+0.813396*x(1)+0.67444*x(2)+0.305038*x(3)+0.129742*x(4))*(0.091947+0.224508*x(1)+0.063458*x(2)+0.93223*x(3)+0.528736*x(4));

% Bounds
lb = [0,0,0,0]';
ub = [Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[0.488509*x(1)+0.063565*x(2)+0.945686*x(3)+0.210704*x(4);
             -0.324014*x(1)-0.501754*x(2)-0.719204*x(3)+0.099562*x(4);
             0.445225*x(1)-0.346896*x(2)+0.637939*x(3)-0.257623*x(4);
             -0.202821*x(1)+0.647361*x(2)+0.920135*x(3)+0.983091*x(4);
             -0.88642*x(1)-0.802444*x(2)-0.305441*x(3)-0.180123*x(4);
             -0.515399*x(1)-0.42482*x(2)+0.897498*x(3)+0.187268*x(4);
             -0.591515*x(1)+0.060581*x(2)-0.427365*x(3)+0.579388*x(4);
             0.423524*x(1)+0.940496*x(2)-0.437944*x(3)-0.742941*x(4)];
cl = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,-Inf]';
cu = [3.562809,-0.052215,0.42792,0.84095,-1.353686,2.137251,-0.290987,0.37362]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','st_e25');
opts.sense = 'min';
