% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:02:59
% Model: st_e16

% Objective
fun = @(x)1200*(800/(258.333333333333+2.5*(0.666666666666667*((320-x(10))*(300-x(9)))^0.5-0.166666666666667*x(9)-0.166666666666667*x(10))))^0.6+1200*(5000/(106.666666666667+0.666666666666667*((340-x(12))*(300-x(11)))^0.5-0.166666666666667*x(11)-0.166666666666667*x(12)))^0.6;

% Bounds
lb = [0,0,0,0,0,0,0,0,100,100,100,100]';
ub = [10,10,10,10,10,10,10,10,290,310,290,330]';

% Constraints
nlcon = @(x)[x(1)+x(2);
             x(1)-x(3)+x(6);
             x(2)-x(4)+x(5);
             -x(3)+x(5)+x(7);
             -x(4)+x(6)+x(8);
             x(12)*x(6)-x(9)*x(3)+100*x(1);
             x(10)*x(5)-x(11)*x(4)+100*x(2);
             x(3)*(x(10)-x(9));
             x(4)*(x(12)-x(11))];
cl = [10,0,0,0,0,0,0,800,1000]';
cu = [10,0,0,0,0,0,0,800,1000]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100,100,100,100]';

% Options
opts = struct('probname','st_e16');
opts.sense = 'min';
