% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:02:58
% Model: st_e11

% Objective
fun = @(x)35*x(1)^0.6+35*x(2)^0.6;

% Bounds
lb = [0,0,0]';
ub = [34,17,300]';

% Constraints
nlcon = @(x)[600*x(1)-x(1)*x(3)-50*x(3);
             600*x(2)+50*x(3)];
cl = [-5000,15000]';
cu = [-5000,15000]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCC';

% Starting Guess
x0 = [NaN,NaN,NaN]';

% Options
opts = struct('probname','st_e11');
opts.sense = 'min';
