% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:02:58
% Model: st_e05

% Objective
fun = @(x)x(1)+x(2)+x(3);

% Bounds
lb = [0,0,0,100,100]';
ub = [15834,36250,10000,300,400]';

% Constraints
nlcon = @(x)[100000*x(4)-120*x(1)*(300-x(4));
             100000*x(5)-80*x(2)*(400-x(5))-100000*x(4);
             -4000*x(3)-100000*x(5)];
cl = [10000000,0,-50000000]';
cu = [10000000,0,-50000000]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,100,100]';

% Options
opts = struct('probname','st_e05');
opts.sense = 'min';
