% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:03:00
% Model: st_glmp_kk92

% Objective
fun = @(x)x(3)*x(4);

% Bounds
lb = [-3,-3,-Inf,-Inf]';
ub = [1,4,Inf,Inf]';

% Constraints
nlcon = @(x)[-4*x(1)+x(2);
             -4*x(1)-2*x(2);
             x(1)-2*x(2);
             x(1)-x(2);
             x(1)+x(2);
             2*x(1)+x(2);
             x(1)+x(2)-x(3);
             x(1)-x(2)-x(4)];
cl = [-Inf,-Inf,-Inf,-Inf,-Inf,-Inf,0,0]';
cu = [12,12,6,3,2,2,0,0]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','st_glmp_kk92');
opts.sense = 'min';
