% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 30-Jan-2014 17:04:31
% Model: weapons

% Objective
fun = @(x)-(-60*0.84^x(7)*0.96^x(25)*0.92^x(52)-50*0.95^x(1)*0.83^x(8)*0.95^x(26)*0.94^x(53)-50*0.85^x(9)*0.96^x(27)*0.92^x(54)-75*0.84^x(10)*0.96^x(28)*0.95^x(55)-40*0.85^x(11)*0.96^x(29)*0.95^x(56)-60*0.85^x(2)*0.81^x(12)*0.9^x(30)*0.98^x(57)-35*0.9^x(3)*0.81^x(13)*0.92^x(31)*0.98^x(58)-30*0.85^x(4)*0.82^x(14)*0.91^x(32)-25*0.8^x(5)*0.8^x(15)*0.92^x(33)-150*0.86^x(16)*0.95^x(34)*0.96^x(45)*0.9^x(59)-30*0.99^x(35)*0.91^x(46)*0.95^x(60)-45*0.98^x(17)*0.98^x(36)*0.92^x(47)*0.96^x(61)-125*0.99^x(37)*0.91^x(48)*0.91^x(62)-200*0.88^x(18)*0.98^x(38)*0.92^x(49)*0.98^x(63)-200*0.87^x(19)*0.97^x(39)*0.98^x(50)*0.99^x(64)-130*0.88^x(20)*0.98^x(40)*0.93^x(51)*0.99^x(65)-100*0.85^x(21)*0.95^x(41)-100*0.95^x(6)*0.84^x(22)*0.92^x(42)-100*0.85^x(23)*0.93^x(43)-150*0.85^x(24)*0.92^x(44))-1755;

% Bounds
lb = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(1)+x(2)+x(3)+x(4)+x(5)+x(6);
             x(7)+x(8)+x(9)+x(10)+x(11)+x(12)+x(13)+x(14)+x(15)+x(16)+x(17)+x(18)+x(19)+x(20)+x(21)+x(22)+x(23)+x(24);
             x(25)+x(26)+x(27)+x(28)+x(29)+x(30)+x(31)+x(32)+x(33)+x(34)+x(35)+x(36)+x(37)+x(38)+x(39)+x(40)+x(41)+x(42)+x(43)+x(44);
             x(45)+x(46)+x(47)+x(48)+x(49)+x(50)+x(51);
             x(52)+x(53)+x(54)+x(55)+x(56)+x(57)+x(58)+x(59)+x(60)+x(61)+x(62)+x(63)+x(64)+x(65);
             x(7)+x(25)+x(52);
             x(2)+x(12)+x(30)+x(57);
             x(16)+x(34)+x(45)+x(59);
             x(18)+x(38)+x(49)+x(63);
             x(19)+x(39)+x(50)+x(64);
             x(20)+x(40)+x(51)+x(65);
             x(24)+x(44)];
cl = [-Inf,-Inf,-Inf,-Inf,-Inf,30,100,40,50,70,35,10]';
cu = [200,100,300,150,250,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC';

% Starting Guess
x0 = [10,10,10,10,10,10,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,7.5,7.5,7.5,7.5,7.5,7.5,7.5,12.5,12.5,12.5,12.5,12.5,12.5,12.5,12.5,12.5,12.5,12.5,12.5,12.5,12.5]';

% Options
opts = struct('probname','weapons');
opts.sense = 'min';
