#!/bin/sh
# dvi2pdf
# Convert DVI to PDF.
#
# Based on ps2pdf

OPTIONS=""
while true
do
	case "$1" in
	-*) OPTIONS="$OPTIONS $1" ;;
	*)  break ;;
	esac
	shift
done

if [ $# -lt 1 -o $# -gt 2 ]; then
	echo "Usage: `basename $0` [options...] input.dvi [output.pdf]" 1>&2
	exit 1
fi

infile=$1;

if [ $# -eq 1 ]
then
	case "${infile}" in
	  *.dvi)	base=`basename ${infile} .dvi` ;;
	  *)		base=`basename ${infile}` ;;
	esac
	outfile=${base}.pdf
else
	outfile=$2
fi

# Doing an initial 'save' helps keep fonts from being flushed between pages.
exec dvips -Ppdf -j0 -q -f $infile | gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=$outfile -sPAPERSIZE=a4 $OPTIONS -c save pop -

# echo "If this gives poor results, use dvi2pdf.old"

# The following should be better. How to get a4?
# exec dvips -f $infile | ps2pdf - $outfile 