% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-May-2015 23:17:09
% Model: inf_nlp_15

% Objective
fun = @(x)log(1+0.4*x(1))+log(1+0.6*x(2))+log(1+0.2*x(3));

% Bounds
lb = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]';
ub = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf]';

% Constraints
nlcon = @(x)[x(1)+x(2)+x(3)+x(4)+x(5)+x(6);
             x(7)+x(8)+x(9)+x(10)+x(11)+x(12);
             x(13)+x(14)+x(15)+x(16)+x(17)+x(18);
             x(1)+1.2*x(2)+1.7*x(3)+0.7*x(10)+1.6*x(11)+1.45*x(12)+x(16)+x(17)+0.8*x(18)];
cl = [10,10,10,100]';
cu = [10,10,10,Inf]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCCCCC';

% Starting Guess
x0 = [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]';

% Options
opts = struct('probname','inf_nlp_15');
opts.sense = 'max';
