% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-May-2015 23:06:19
% Model: inf_nlp_100

% Objective
fun = @(x)6.5*x(1)-0.5*x(1)*x(1)-x(2)-2*x(3)-3*x(4)-2*x(5)-x(6);

% Bounds
lb = [0,0.9999,1.2237,1.2105,0,0]';
ub = [0,0.9999,1.2237,1.2105,0,0]';

% Constraints
nlcon = @(x)[x(1)+2*x(2)+8*x(3)+x(4)+3*x(5)+5*x(6);
             -8*x(1)-4*x(2)-2*x(3)+2*x(4)+4*x(5)-x(6);
             2*x(1)+0.5*x(2)+0.2*x(3)-3*x(4)-x(5)-4*x(6);
             0.2*x(1)+2*x(2)+0.1*x(3)-4*x(4)+2*x(5)+2*x(6);
             -0.1*x(1)-0.5*x(2)+2*x(3)+5*x(4)-5*x(5)+3*x(6)];
cl = [-Inf,-Inf,-Inf,-Inf,-Inf]';
cu = [16,-1,24,12,3]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCC';

% Starting Guess
x0 = [NaN,0.9999,1.2237,1.2105,NaN,NaN]';

% Options
opts = struct('probname','inf_nlp_100');
opts.sense = 'min';
