% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 31-May-2015 23:13:54
% Model: inf_nlp_117

% Objective
fun = @(x)12*(0.00184*x(1)*x(1)+9.2*x(1))+12*(0.00184*x(2)*x(2)+9.2*x(2))+12*(0.00184*x(3)*x(3)+9.2*x(3))+12*(0.00184*x(4)*x(4)+9.2*x(4))+12*(0.00184*x(5)*x(5)+9.2*x(5))+12*(0.00184*x(6)*x(6)+9.2*x(6))+41400;

% Bounds
lb = [150,150,150,150,150,150,0,0,0,0,0,0,1000,1000,1000,1000,1000,1000]';
ub = [1500,1500,1500,1500,1500,1500,1000,1000,1000,1000,1000,1000,1100,1100,1100,1100,1100,1100]';

% Constraints
nlcon = @(x)[-x(1)-x(7)-x(13);
             -x(2)-x(8)-x(14);
             -x(3)-x(9)-x(15);
             -x(4)-x(10)-x(16);
             -x(5)-x(11)-x(17);
             -x(6)-x(12)-x(18)];
cl = [-1200,-1500,-1100,-1800,-950,-1300]';
cu = [-1200,-1500,-1100,-1800,-950,-1300]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CCCCCCCCCCCCCCCCCC';

% Starting Guess
x0 = [150,150,150,150,150,150,NaN,NaN,NaN,NaN,NaN,NaN,1000,1000,1000,1000,1000,1000]';

% Options
opts = struct('probname','inf_nlp_117');
opts.sense = 'min';
