% This BARON input file was generated by the MATLAB/BARON interface.
% The BARON/MATLAB interface was developed by J. Currie.  The interface
% is provided free of charge and with no warranties from The Optimization
% Firm, http://www.minlp.com.
% Interface version: v1.51 [17-Dec-2013]
% File generated: 13-May-2015 18:54:19
% Model: inf_lp_40

% Objective
fun = @(x)-11*x(1)-12*x(2)-20;

% Bounds
lb = [0,0]';
ub = [Inf,Inf]';

% Constraints
nlcon = @(x)[x(1);
             x(2);
             2*x(1)-x(2);
             -x(1)+2*x(2)];
cl = [-Inf,-Inf,-Inf,-Inf]';
cu = [1,1,-1,-1]';

% Variables (C = continuous, B = binary, I = integer)
xtype = 'CC';

% Starting Guess
x0 = [NaN,NaN]';

% Options
opts = struct('probname','inf_lp_40');
opts.sense = 'min';
